Cleanup
cms-gem-daq-project/ctp7_modules pull request #105
Opened 2019-03-22 17:10 UTC by jsturdy

## Description

* Replace all `localArgs` initialization with `GETLOCALARGS`
* Clean up some (not all) formatting mismatches
* Close all RPC callbacks with `rtxn.abort()`

### Types of changes
- [x] Cosmetic/cleanup

## Motivation and Context
Needed to happen, did it now to just be done with it

2019-03-22 19:04 UTC, mexanick requested changes
few minor edits. otherwise looks good =)

2019-03-22 19:04 UTC, mexanick commented on src/calibration_routines.cpp
> +    std::this_thread::sleep_for (std::chrono::seconds(1)); //I noticed that DAC values behave weirdly immediately after VFAT is placed in run mode (probably voltage/current takes a moment to stabaliz
automated search/replace? ;)

2019-03-22 19:04 UTC, mexanick commented on src/calibration_routines.cpp
> +    if ( (notmask & goodVFATs) != notmask) {
extra space between opening parentheses

2019-03-22 19:04 UTC, mexanick commented on src/calibration_routines.cpp
> +    if ( (notmask & goodVFATs) != notmask) {
extra space between parentheses

2019-03-22 19:04 UTC, mexanick commented on src/calibration_routines.cpp
> +    if ( fw_version_check("checkSbitRateWithCalPulse", la) < 3) {
extra space after opening bracket

2019-03-22 19:04 UTC, mexanick commented on src/daq_monitor.cpp
> +  if (request->get_key_exists("doReset") ) {
extra spaces between closing brackets

2019-03-22 19:04 UTC, mexanick commented on src/daq_monitor.cpp
> +  if (request->get_key_exists("doReset") ) {
extra space between closing brackets

2019-03-24 21:39 UTC, jsturdy commented on src/calibration_routines.cpp
> +    std::this_thread::sleep_for (std::chrono::seconds(1)); //I noticed that DAC values behave weirdly immediately after VFAT is placed in run mode (probably voltage/current takes a moment to stabaliz
Indeed... I'll fix

2019-03-24 21:40 UTC, jsturdy commented on src/calibration_routines.cpp
> +    if ( (notmask & goodVFATs) != notmask) {
Error was not introduced in this PR

2019-03-24 21:40 UTC, jsturdy commented on src/calibration_routines.cpp
> +    if ( (notmask & goodVFATs) != notmask) {
Error was not introduced in this PR

2019-03-24 21:40 UTC, jsturdy commented on src/calibration_routines.cpp
> +    if ( fw_version_check("checkSbitRateWithCalPulse", la) < 3) {
Error was not introduced in this PR

2019-03-24 21:40 UTC, jsturdy commented on src/daq_monitor.cpp
> +  if (request->get_key_exists("doReset") ) {
Error was not introduced in this PR

2019-03-24 21:40 UTC, jsturdy commented on src/daq_monitor.cpp
> +  if (request->get_key_exists("doReset") ) {
Error was not introduced in this PR

2019-03-24 21:46 UTC, jsturdy commented
Fixed the error introduced, did not touch the persisting style error.
There are plenty of other style issues that need cleanup (inconsistent spacing, overabundance of comments for control flow, `if/else` block style consistency, etc.) that are not addressed here.

2019-03-25 09:15 UTC, mexanick approved these changes
Ok. I mentioned few other style errors as I see you've started to hit them =) 
I agree, they should be addressed in a separate PR and before doing that we should publish coding style guidelines and eventually attach a cpp/py lint to the CI. Actually, I see that certain changes you've introduced aren't following google code style (nothing bad, just different), so I believe we really need to publish our style conventions.

2019-03-25 09:32 UTC, jsturdy commented
@lmoureaux started to put my comments into the `cmsgemos` `CONTRIBUTING.md` guidelines when he started work on the `gemonlinedb` package; and as mentioned in a few threads, my style choices are a semi-random mish-mash of various styles :-D
We can try to standardize those more.

2019-03-25 09:32 UTC, merged