WIP: Implement correct packaging
cms-gem-daq-project/ctp7_modules pull request #114
Opened 2019-04-05 14:37 UTC by mexanick

The PR is ready for review, but will require a config submodule bump after merge of https://github.com/cms-gem-daq-project/gembuild/pull/2
## Description

Implements correct packaging, dependencies handling (almost! we may need to update dependencies list) and post-install linking scripts
Fixes #78 and #28 
Requires https://github.com/cms-gem-daq-project/gembuild/pull/2
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Required for proper versioning and system setup
## How Has This Been Tested?

Installed on `eagle64`
### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2019-04-06 09:11 UTC, jsturdy requested changes

2019-04-06 09:11 UTC, jsturdy commented on include/packageinfo.h
> +#define CTP7_MODULES_REQUIRED_PACKAGE_LIST reedmuller
Isn't `xhal` supposed to be on the card as well?

2019-04-06 09:11 UTC, jsturdy commented on scripts/postinstall.sh
> +    ln -sf $install_path/lib/$i /mnt/persistent/rpcmodules/$i
Rather simpler to do
```sh
ln -sf $install_path/lib/*.so /mnt/persistent/rpcmodules/
```

2019-04-06 09:11 UTC, jsturdy commented on scripts/postinstall.sh
> +    ln -sf $install_path/lib/$i /mnt/persistent/rpcmodules/$i
Additionally, probably should have the post kill and restart `rpcsvc` as the appropriate user

2019-04-06 10:36 UTC, bdorney commented
I don't think I'm knowledgable enough about `gembuild` and the `make` process in general to review this PR.

2019-04-06 10:43 UTC, mexanick commented on scripts/postinstall.sh
> +    ln -sf $install_path/lib/$i /mnt/persistent/rpcmodules/$i
good points! Especially the latter =)) Will implement

2019-04-06 10:45 UTC, mexanick commented on include/packageinfo.h
> +#define CTP7_MODULES_REQUIRED_PACKAGE_LIST reedmuller
it is, and a number of other libs (xerces-c, lmdb - but they aren't packaged yet... I have to think about this) - thus a PR was marked as WIP. I just need a minute to think which exact libs we need.

2019-04-06 10:46 UTC, mexanick commented
> I don't think I'm knowledgable enough about `gembuild` and the `make` process in general to review this PR.

I wanted to advertise your attention, that this long-requested functionality is now available

2019-04-06 10:55 UTC, jsturdy commented on include/packageinfo.h
> +#define CTP7_MODULES_REQUIRED_PACKAGE_LIST reedmuller
OK, but this situation was discussed during the SW developers meeting.
If the discussion is not finalized, the appropriate location is an issue, rather than a PR :-)

2019-04-08 12:22 UTC, mexanick commented
@jsturdy your suggestions implemented

2019-04-08 12:41 UTC, jsturdy approved these changes

2019-04-08 12:47 UTC, merged

2019-04-08 14:36 UTC, bdorney commented
What are the consequences of this being merged? e.g. do the build instructions reported:

- [gembuild](https://github.com/cms-gem-daq-project/sw_utils/blob/develop/v3ElectronicsUserGuide.md#build-prerequisites-the-gembuild-repo)
- [ctp7_modules](https://github.com/cms-gem-daq-project/sw_utils/blob/develop/v3ElectronicsUserGuide.md#ctp7_modoules)

Need to be updated?

What post build actions are now required? e.g. previously:

```
<make package>
cd ctp7_modules/lib
scp *.so <ctp7>
<restart rpcsvc>
```

Was all that was required, does this procedure change...?

2019-04-08 14:36 UTC, bdorney commented
@jsturdy @mexanick

2019-04-08 14:39 UTC, jsturdy commented
> What are the consequences of this being merged? e.g. do the build instructions reported:

None, this only impacts the RPM