#100 : added 5 modules to read  SACADC sensors
cms-gem-daq-project/ctp7_modules pull request #120
Opened 2019-05-07 18:05 UTC by ram1123

Added modules to read a specific SCA ADC or the similar type of SCA SCA sensors together, like temperature, voltage, etc.

## Description

There are 31 SCA ADC sensors defined ([here](https://github.com/ram1123/ctp7_modules/blob/f7590d67eeb06326ccaafe0d4aaf28fd1f52ecf8/include/amc/sca_enums.h#L211-L264)).  As requested in issue [#100](https://github.com/cms-gem-daq-project/ctp7_modules/issues/100), to create several function to read each ADC and all ADC, I added five different functions named `readSCAADCSensor`, `readSCAADCTemperatureSensors`, `readSCAADCVoltageSensors`,  `readSCAADCSignalStrengthSensors` and `readAllSCAADCSensors` to read individual sensors,  temperature sensors,  voltage related sensors, signal strength sensors and all sensors, respectively.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

## How Has This Been Tested?

All added modules are tested using a macro named `blaster.cxx`.

```cpp
#include <iostream>
#include <fstream>
#include <random>
#include <iomanip>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <errno.h>
#include <xhal/rpc/wiscrpcsvc.h>

using namespace wisc;

int main(int argc, char *argv[])
{
  RPCSvc rpc;
  try {
    rpc.connect(argv[1]);
  } catch (RPCSvc::ConnectionFailedException &e) {
    printf("Caught RPCErrorException: %s\n", e.message.c_str());
    return 1;
  } catch (RPCSvc::RPCException &e) {
    printf("Caught exception: %s\n", e.message.c_str());
    return 1;
  }

#define STANDARD_CATCH                                                  \
  catch (RPCSvc::NotConnectedException &e) {                            \
    printf("Caught NotConnectedException: %s\n", e.message.c_str());    \
    return 1;                                                           \
  } catch (RPCSvc::RPCErrorException &e) {                              \
    printf("Caught RPCErrorException: %s\n", e.message.c_str());        \
    return 1;                                                           \
  } catch (RPCSvc::RPCException &e) {                                   \
    printf("Caught exception: %s\n", e.message.c_str());                \
    return 1;                                                           \
  }

#define ASSERT(x) do {                                                  \
    if (!(x)) {                                                         \
      printf("Assertion Failed on line %u: %s\n", __LINE__, #x);        \
      return 1;                                                         \
    }                                                                   \
  } while (0)

  RPCMsg req, rsp;

  try {
    ASSERT(rpc.load_module("amc", "amc v1.0.1"));
  } STANDARD_CATCH;

  //req = RPCMsg("amc.readSCAADCSensor");
  req = RPCMsg("amc.readSCAADCTemperatureSensors");

  //errno = 0;
  //uint32_t sz = strtoul(argv[2], nullptr, 16);

  //if (errno != 0 /*|| *p != '\0'*/ || sz > INT_MAX) {
  //  errno = 0;
  //  sz = strtoul(argv[2], nullptr, 10);
  //  if (errno != 0 /*|| *p != '\0'*/ || sz > INT_MAX) {
  //    sz = 0;
  //  } else {
  //    // pass
  //  }
  //} else {
  //  // pass
  //}

  errno = 0;
  uint32_t ty = strtoul(argv[2], nullptr, 16);

  if (errno != 0 /*|| *p != '\0'*/ || ty > INT_MAX) {
    ty = 0;
  } else {
    // pass
  }

  //req.set_word("ch", 	sz);
  req.set_word("ohMask",ty);

  try {
    std::cout << "calling amc.readSCAADCTemperatureSensors on " << std::string(argv[1]) << " with " << ty << "...";
    //std::cout << "calling amc.readSCAADCTemperatureSensors on " << std::string(argv[1]) << " with " << sz << " and " << ty << "...";
    rsp = rpc.call_method(req);
    std::cout << "done!" << std::endl;
    if (rsp.get_key_exists("error")) {
      std::cout << "RPC ERROR:" << rsp.get_string("error") << std::endl;
      return 0;
    }

  
  return 0;
}
```

then running its executable after setting the environment and monitoring the log.

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-05-08 07:32 UTC, jsturdy requested changes

2019-05-08 07:32 UTC, jsturdy commented on include/amc/sca_enums.h
> +      VTTX_CSC 	     = 0x00, ///< Transceiver block next to the CSC VTTX
Oops, these should have `_PT100`, like the other temp sensors

2019-05-08 07:32 UTC, jsturdy commented on include/utils.h
> +uint32_t bitCheck(uint32_t ohMask, int bit);
I would generalize this such that the input parameter is **not** related to the `OptoHybrid`, rather, it is simply a mask/word.
Functionally no change, but semantically, it is more general.

2019-05-08 07:32 UTC, jsturdy commented on src/amc/sca.cpp
> +  for(auto const& val : result){
please use (note the spaces) everywhere inside functions
```c++
for (specifier) {

if (condition) {

while (condition) {
```

2019-05-08 07:32 UTC, jsturdy commented on src/amc/sca.cpp
> +      count++;
prefer pre-increment, as mentioned several times previously

2019-05-08 07:32 UTC, jsturdy commented on src/amc/sca.cpp
> +  int count;
`count` is a rather poorly chosen name, maybe `ohIdx`?

2019-05-08 07:32 UTC, jsturdy commented on src/utils.cpp
> +  if ( (ohMask >> bit) & 1 ){
You should probably also have a safety check to ensure you don't shift off the end if `bit > 31`

2019-05-08 07:32 UTC, jsturdy commented on src/amc/sca.cpp
> +  int count = 0;
`count` is a rather poorly chosen name, maybe `ohIdx`? (here and elsewhere where it is used the same way)

2019-05-08 07:32 UTC, jsturdy commented on src/amc/sca.cpp
> +std::vector<uint32_t> scaADCCommand(localArgs* la, SCAADCChannelT const& ch, uint8_t const& len, uint32_t data, uint16_t const& ohMask)
I think you can also remove `len` and `data` from this function (and your subsequent usage)
I don't think for the ADC we'll need to change these values

2019-05-08 07:32 UTC, jsturdy commented on include/amc/sca.h
> + *  \param response RPC response message
Here, and other new functions, state the output key name, type, and describe the format (as mentioned previously, the documentation style utilized by @lpetre-ulb in `gbt.h` is rather quite good)

2019-05-08 07:32 UTC, jsturdy commented on include/amc/sca.h
> + *  - ch : Name of ADC channel to read from SCAADCChannelT
Here, and other new functions, move this into the `\param request` documentation section, state the key name and type

2019-05-08 09:16 UTC, ram1123 commented on include/amc/sca.h
> + *  \param response RPC response message
Is the following message fine?

```cpp
/*!
 *  \fn void readAllSCAADCSensors(const RPCMsg *request, RPCMsg *response)
 *  \brief Read all connected SCA ADC sensors. 
 *  \param[in] request RPC response message
 *  \param[out] response RPC response message
 *
 *  The method expects the following RPC keys:
 *  - `word ohMask` : This specifies which OH's to read from
 *
 *  The method returns the following RPC keys:
 *  - `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26:24><0s 23:21><ADC ID 20:16><0's 15:12><data 11:0>
 */
void readAllSCAADCSensors(const RPCMsg *request, RPCMsg *response);
```

2019-05-08 10:49 UTC, ram1123 commented on src/utils.cpp
> +  if ( (ohMask >> bit) & 1 ){
Is this fine?

```cpp
uint32_t bitCheck(uint32_t word, int bit)
{
  if (bit > 31)
    throw invalid_argument("In function: uint32_t bitCheck(uint32_t word, int bit), the shifting bit (named bit) should not be more than 31");
  if ( (word >> bit) & 1 ) {
    return 1;
  } else {
    return 0;
  }
}
```

2019-05-08 12:31 UTC, jsturdy commented on include/amc/sca.h
> + *  \param response RPC response message
Yes, but please group them with the `\param` block to which they belong, i.e.,
```c++
\param[in] request RPC request message, with the following keys
           * `word ohMask` : blah
\param[out] response RPC response message, with the following keys
           * `word_array data` : blah
```

2019-05-08 12:33 UTC, jsturdy commented on src/utils.cpp
> +  if ( (ohMask >> bit) & 1 ){
I'd shorten the message to:
`Invalid request to shift word by more than 31 bits`

2019-05-09 07:48 UTC, bdorney commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
From the text here I don't understand how each output data word is to be decoded.  Specifically:

```
OH masked 1, otherwise 0 27
```

2019-05-09 07:48 UTC, bdorney commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
same

2019-05-09 07:48 UTC, bdorney commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
same

2019-05-09 07:49 UTC, bdorney commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
Assume my top level comment applied to all instances of this documentation line.

2019-05-09 07:50 UTC, bdorney commented on include/amc/sca_enums.h
> +      //ADC_CH29 = 0x1D, ///< ADC channel 29
If they are not connected then we should just delete these lines and not push large comment blocks to the repo.

However if we expect that these ADC channels would be accessible on GE2/1 then they should not be uncommented but left with a note of "GE2/1 only"

2019-05-09 07:55 UTC, bdorney commented on src/amc/sca.cpp
> +std::vector<uint32_t> scaADCCommand(localArgs* la, SCAADCChannelT const& ch, uint16_t const& ohMask)
This is a local function? e.g. it doesn't take the RPC message/response parameters?

If so would suggest to change name to follow previous naming convention; e.g. `scaADCCommandLocal`.

2019-05-09 08:02 UTC, bdorney commented on src/amc/sca.cpp
> +  if (ch == SCAADCChannel::VTTX_CSC_PT100 || ch == SCAADCChannel::VTTX_GEM_PT100 || ch == SCAADCChannel::SCA_PT100 || ch == SCAADCChannel::V6_FPGA_PT100 )	// Hardcoded channel numbers
This could be simplified with the unordered map I suggest above, e.g.

```C++
if (map_connChan.count(ch))
{
   //do stuff
}
```

2019-05-09 08:03 UTC, bdorney commented on include/amc/sca_enums.h
> +      VTRX_RSSI1     = 0x15, ///< ADC channel 21, VTRx rssi1
if (ch == SCAADCChannel::VTTX_CSC_PT100 || ch == SCAADCChannel::VTTX_GEM_PT100 || ch == SCAADCChannel::SCA_PT100 || ch == SCAADCChannel::V6_FPGA_PT100 )

To this struct I would suggest to add an `std::unordered_map<int,bool>` which is filled by the `ADCChannel` constructor (which you would have to create) which would have:

```C++
map_connChan[VTTX_CSC_PT100] = true;
map_connChan[VTTX_GEM_PT100] = true;
...
...
```

This would greatly simplify some of your if statements below (e.g. my comment [here](https://github.com/cms-gem-daq-project/ctp7_modules/pull/120/files#r282377698)).

2019-05-09 08:03 UTC, bdorney commented on src/amc/sca.cpp
> +  if (ch == SCAADCChannel::VTTX_CSC_PT100 || ch == SCAADCChannel::VTTX_GEM_PT100 || ch == SCAADCChannel::SCA_PT100 || ch == SCAADCChannel::V6_FPGA_PT100 )	// Hardcoded channel numbers
same

2019-05-09 08:05 UTC, bdorney requested changes
some changes requested to simplify code base and improve documentation.

2019-05-09 08:07 UTC, jsturdy commented on include/amc/sca_enums.h
> +      //ADC_CH29 = 0x1D, ///< ADC channel 29
I specifically asked to **not** remove these `enum`s for now

2019-05-09 08:13 UTC, jsturdy commented on include/amc/sca_enums.h
> +      VTRX_RSSI1     = 0x15, ///< ADC channel 21, VTRx rssi1
Where the purpose of the map is to do what?
If to tell whether the sensor uses a current source, it's probably cleaner to just add a function to the struct that returns `true` if the `enum` is a temperature sensor or not, i.e., something like:
```c++
useCurrentSource(SCAADCChannelT sensor)
{
  switch(sensor) {
    case(SCAADCChannel::VTTX_CSC_PT100: return true;
    default: return false
  }
}
```

2019-05-09 08:19 UTC, jsturdy commented on src/amc/sca.cpp
> +std::vector<uint32_t> scaADCCommand(localArgs* la, SCAADCChannelT const& ch, uint16_t const& ohMask)
This change *could* be made in a separate PR (the nomenclature is my doing, and this function is **not** the only one exhibiting this)

2019-05-09 11:27 UTC, ram1123 commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
@bdorney ,

Is this fine:

- `word_array data` : It contains 27 bit information. Bit 0 to 11 contains output data, 12 to 15 are zeros, 16 to 20 contains SCA-ADC ID, 21 to 23 are zeros, 24 to 26 contains the ohMask word and bit 27 contains information about a particular OH is masked (0) or not(1).

2019-05-09 12:10 UTC, ram1123 commented on src/utils.cpp
> +}
@jsturdy ,

Is it good to change the function `bitCheck` like below?

```cpp
uint32_t bitCheck(uint32_t word, int bit)
{
   if (bit > 31)
      throw std::invalid_argument("Invalid request to shift word by more than 31 bits");
   return (((word >> bit) & 1) ? 1 : 0);
}

2019-05-09 12:58 UTC, jsturdy commented on src/utils.cpp
> +}
You just need to do (no need for the conditional):
```c++
return (word>>bit) & 0x1;
```
but otherwise, I think that's fine, maybe add "...shift 32-bit word by..." for clarity

2019-05-09 12:59 UTC, jsturdy commented
One other comment I missed from @bdorney regarding the PT100 sensors, the one we've labeled as `SCA_PT100` should be `GBT0_PT100`, according to Yifan

2019-05-09 13:02 UTC, ram1123 commented
> One other comment I missed from @bdorney regarding the PT100 sensors, the one we've labeled as `SCA_PT100` should be `GBT0_PT100`, according to Yifan

done.

2019-05-09 13:03 UTC, jsturdy commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
I think we can clean up the documentation by doing:
```c++
*  \param[out] response RPC response message with the following keys:
 *  	- `word_array data` : ADC data is returned as an array of 32-bit words.
                              Data is formatted as: <present 27><link ID 26:24><0s 23:21><ADC ID 20:16><0's 15:12><data 11:0>

```

2019-05-09 13:09 UTC, ram1123 commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
For me 2nd option seems better. I will wait for @bdorney comment.

2019-05-09 13:11 UTC, ram1123 commented on include/amc/sca_enums.h
> +      VTRX_RSSI1     = 0x15, ///< ADC channel 21, VTRx rssi1
@bdorney & @jsturdy ,

Finally, what we are planning to do?

2019-05-09 15:49 UTC, jsturdy commented on include/amc/sca_enums.h
> +      VTRX_RSSI1     = 0x15, ///< ADC channel 21, VTRx rssi1
Implement my suggestion, but make the function, e.g.,
```c++
struct 
  enum EADChannel {
    // blah
  } ADCChannel;

  static constexpr bool useCurrentSource(EADCChannel sensor)
{
  switch(sensor) {
    case(VTTX_CSC_PT100: return true;
    default: return false
  }
}
```

Then when using, you'll do, e.g.,
```c++
if (SCAADCChannel::useCurrentSource(ch)) {
  // something
}
```

2019-05-10 10:31 UTC, ram1123 commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
Hi @bdorney ,

I am implementing the @jsturdy suggestion:

```cpp
*  \param[out] response RPC response message with the following keys:
*    - `word_array data` : ADC data is returned as an array of 32-bit words formatted as:
                           bit [27]: data present
                           bits [26:24]: link ID
                           bits [23:21]: constant 0's
                           bits [20:16]: ADC channel ID
                           bits [15:12]: constant 0's
                           bits [11:0]: ADC data
```

2019-05-10 10:34 UTC, ram1123 commented on include/amc/sca_enums.h
> +      VTRX_RSSI1     = 0x15, ///< ADC channel 21, VTRx rssi1
I implemented it like (as per @jsturdy suggestation):

```cpp
struct ADCChannel {
  enum EADChannel {
    // blah
  } ADCChannel;
    
static bool useCurrentSource(EADCChannel sensor)
    {
       switch (sensor) {
          case (VTTX_CSC_PT100): return true;
	  case (VTTX_GEM_PT100): return true;
	  case (GBT0_PT100):	 return true;
	  case (V6_FPGA_PT100):	 return true;
	  default:		 return false;
       }
    }
}
```

Then it is used as:

```cpp
  // enable the current sink if reading the temperature ADCs
  if (SCAADCChannel::useCurrentSource(ch))
    sendSCACommand(la, SCAChannel::ADC, SCAADCCommand::ADC_W_CURR, 0x4, 0x1<<ch, ohMask);
```

2019-05-10 10:34 UTC, ram1123 commented on src/amc/sca.cpp
> +  if (ch == SCAADCChannel::VTTX_CSC_PT100 || ch == SCAADCChannel::VTTX_GEM_PT100 || ch == SCAADCChannel::SCA_PT100 || ch == SCAADCChannel::V6_FPGA_PT100 )	// Hardcoded channel numbers
I implemented it like (as per @jsturdy suggestation):

```cpp
struct ADCChannel {
  enum EADChannel {
    // blah
  } ADCChannel;
    
static bool useCurrentSource(EADCChannel sensor)
    {
       switch (sensor) {
          case (VTTX_CSC_PT100): return true;
	  case (VTTX_GEM_PT100): return true;
	  case (GBT0_PT100):	 return true;
	  case (V6_FPGA_PT100):	 return true;
	  default:		 return false;
       }
    }
}
```

Then it is used as:

```cpp
  // enable the current sink if reading the temperature ADCs
  if (SCAADCChannel::useCurrentSource(ch))
    sendSCACommand(la, SCAChannel::ADC, SCAADCCommand::ADC_W_CURR, 0x4, 0x1<<ch, ohMask);
```

2019-05-10 10:35 UTC, ram1123 commented on src/amc/sca.cpp
> +  if (ch == SCAADCChannel::VTTX_CSC_PT100 || ch == SCAADCChannel::VTTX_GEM_PT100 || ch == SCAADCChannel::SCA_PT100 || ch == SCAADCChannel::V6_FPGA_PT100 )	// Hardcoded channel numbers
I implemented it like (as per @jsturdy suggestation):

```cpp
struct ADCChannel {
  enum EADChannel {
    // blah
  } ADCChannel;
    
static bool useCurrentSource(EADCChannel sensor)
    {
       switch (sensor) {
          case (VTTX_CSC_PT100): return true;
	  case (VTTX_GEM_PT100): return true;
	  case (GBT0_PT100):	 return true;
	  case (V6_FPGA_PT100):	 return true;
	  default:		 return false;
       }
    }
}
```

Then it is used as:

```cpp
  // enable the current sink if reading the temperature ADCs
  if (SCAADCChannel::useCurrentSource(ch))
    sendSCACommand(la, SCAChannel::ADC, SCAADCCommand::ADC_W_CURR, 0x4, 0x1<<ch, ohMask);
```

2019-05-10 10:36 UTC, ram1123 commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
implementing  @jsturdy's suggestion:

```cpp
*  \param[out] response RPC response message with the following keys:
*    - `word_array data` : ADC data is returned as an array of 32-bit words formatted as:
                           bit [27]: data present
                           bits [26:24]: link ID
                           bits [23:21]: constant 0's
                           bits [20:16]: ADC channel ID
                           bits [15:12]: constant 0's
                           bits [11:0]: ADC data
```

2019-05-10 10:36 UTC, ram1123 commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
implementing  @jsturdy's suggestion:

```cpp
*  \param[out] response RPC response message with the following keys:
*    - `word_array data` : ADC data is returned as an array of 32-bit words formatted as:
                           bit [27]: data present
                           bits [26:24]: link ID
                           bits [23:21]: constant 0's
                           bits [20:16]: ADC channel ID
                           bits [15:12]: constant 0's
                           bits [11:0]: ADC data
```

2019-05-10 10:36 UTC, ram1123 commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
implementing  @jsturdy's suggestion:

```cpp
*  \param[out] response RPC response message with the following keys:
*    - `word_array data` : ADC data is returned as an array of 32-bit words formatted as:
                           bit [27]: data present
                           bits [26:24]: link ID
                           bits [23:21]: constant 0's
                           bits [20:16]: ADC channel ID
                           bits [15:12]: constant 0's
                           bits [11:0]: ADC data
```

2019-05-14 06:34 UTC, bdorney commented on include/amc/sca.h
> + *  	- `word_array data` : Array of word contaning the information of masked/unmasked OH, link ID, SCA ADC sensor number and the data. This is formatted like: <OH masked 1, otherwise 0 27><link ID 26
Yes sorry for late reply; the proposed change is good.  It's much clearer now.  Thanks to you both.

2019-05-14 09:36 UTC, jsturdy submitted a review, later dismissed
I think this is OK on my side now.
@bdorney, @mexanick, @evka85?

2019-05-14 11:24 UTC, bdorney commented on include/amc/sca_enums.h
> +	  case (VTTX_GEM_PT100): return true;
looks like you have an extra space on line 269, e.g. compare to line 270.

2019-05-14 11:35 UTC, bdorney commented on src/amc/sca.cpp
> +      response->set_word_array("data",outData.data(), outData.size());
Seems like you're using the `RPCMsg::set_word_array` method that's for arrays, but this is an overloaded method that also works for `std::vector` objects,  why not just use that one, e.g. `RPCMsg:: set_word_array(std::string key, const std::vector<uint32_t> &data)` .  So line 260 would become:

```C++
    response->set_word_array("data", outData);
```

Also would prefer the RPC key name was a bit less generic.  e.g. instead of `"data"` it might be more instructive to see `"scaADCData"`.  Although not sure what @jsturdy's policy on this would be moving forward.

2019-05-14 11:57 UTC, bdorney commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
This is provided as an input key in may places.  It may not be appropriate for this PR, but you could imagine in `amc.h`/`amc.cpp` the following function existed:

```C++
uint32_t getOHMask(localArgs *la){
   uint32 scaReady = readReg(la, "GEM_AMC.SLOW_CONTROL.SCA.STATUS.READY");
   uint32 scaError = readReg(la, "GEM_AMC.SLOW_CONTROL.SCA.STATUS.CRITICAL_ERROR");

   return (scaReady & (~scaError & 0xfff));
}
```

The function above could be adapted to have some error/warning inserted into the RPC response (although I think this is not the road @jsturdy advocated at during the meeting today), or throw a runtime error in which the calling code would have to catch, in the event 0x0 (e.g. no unmasked OH's) is determined to be the `ohMask`. 

The following could then be done everywhere:

```C++
uint32_t ohMask = 0x0;
if (request.get_key_exists("ohMask"))
{
   ohMask = request->get_word("ohMask");
} else {
   ohMask = getOHMask(la);
}

If it's not desired to implement this `getOHMask` function in this PR then at minimum we should do the following instead of line 248:

```C++
uint32_t ohMask = 0xfff;
{
   ohMask = request->get_word("ohMask");
}
```

e.g. default behavior if no key is supplied would be to consider all OH's.

2019-05-14 11:58 UTC, bdorney commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
Assume my comment [here](https://github.com/cms-gem-daq-project/ctp7_modules/pull/120/files#r283759749) applies to all instances of this line.

2019-05-14 11:59 UTC, bdorney commented on src/amc/sca.cpp
> +  response->set_word_array("data", outData.data(), outData.size());
Assume my comment [here](https://github.com/cms-gem-daq-project/ctp7_modules/pull/120/files#r283752308) applies to all instances of your usage of the array version of `wisc::RPCMsg::set_word_array` over the `std::vector` version.

2019-05-14 12:01 UTC, bdorney commented on src/amc/sca.cpp
> +      LOGGER->log_message(LogManager::DEBUG, stdsprintf("Value for OH%i, SCA-ADC channel 0x%x = %i ",ohIdx, ch, val));
Unless there is a specific reason from @jsturdy would prefer this log message show SCA ADC channel number in decimal rather than hex.  Comment applies to all instances.

2019-05-14 12:05 UTC, bdorney commented on src/amc/sca.cpp
> +  for (SCAADCChannelT channelName = SCAADCChannel::VTTX_CSC_PT100; channelName<=SCAADCChannel::SCA_TEMP; channelName=SCAADCChannelT(channelName+1)) {
I think you missed a spot where the outer for loop should be like `for(auto const& channelName : chArr) {` with appropriate definition of `chArr`.  Otherwise this for loop may behave unexpectedly if entries are added to the `SCAADCChannel` `enum`.

2019-05-14 12:05 UTC, bdorney requested changes
Code cleanup needed in some places.

2019-05-14 12:06 UTC, ram1123 commented on src/amc/sca.cpp
> +      response->set_word_array("data",outData.data(), outData.size());
@bdorney : Yes, I will change the  response like `response->set_word_array("data", outData);`. For `"data"` to `"scaADCData"` I will wait what @jsturdy  says.

2019-05-14 12:08 UTC, ram1123 commented on include/amc/sca_enums.h
> +	  case (VTTX_GEM_PT100): return true;
I don't know why on github its showing like this. While in my vi editor its fine.

2019-05-14 12:49 UTC, bdorney commented on include/amc/sca_enums.h
> +	  case (VTTX_GEM_PT100): return true;
Do you have your editor configured to convert the tab character `\t` to a specific number of spaces?  If not then the reason is most likely this.

2019-05-14 14:57 UTC, ram1123 commented on include/amc/sca_enums.h
> +	  case (VTTX_GEM_PT100): return true;
yes... `\t` is shifts to 3 spaces. When I enter it keeps indentation. So, it might be because of this.

2019-05-14 15:09 UTC, jsturdy commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
For defaults for non-mandatory keys, I prefer something, a la
```c++
    const uint32_t ohMask   = request->get_key_exists("ohMask") ? request->get_word("ohMask") : 0xfff; // or better yet, some defined constant, e.g., FULL_OH_MASK
```

2019-05-14 15:17 UTC, jsturdy commented on src/amc/sca.cpp
> +  for (SCAADCChannelT channelName = SCAADCChannel::VTTX_CSC_PT100; channelName<=SCAADCChannel::SCA_TEMP; channelName=SCAADCChannelT(channelName+1)) {
The loop is "ok" in this case, but it **will** have *unintended* consequences (that I think I mentioned in an earlier comment), in that it will attempt to sample *every* (even not present) channels.
Sure, one *could* duplicate the `enum` class here just to get an iterable object (as was done in the other functions), but that should really be done in a better way inside the `enum` (class) itself, and also removal of the arrays defined in the other functions, to get iterators for all, temperature, voltage, and rssi channels, independently.
For now, I don't consider this a blocker

2019-05-14 15:18 UTC, jsturdy commented on src/amc/sca.cpp
> +      response->set_word_array("data",outData.data(), outData.size());
I strongly prefer completely generic `"data"` keys for simplicity (here and everywhere else); the calling function knows which function it's calling, so it doesn't need to give a special name to the data...

2019-05-14 15:23 UTC, jsturdy commented on include/amc/sca_enums.h
> +	  case (VTTX_GEM_PT100): return true;
You should remove *completely* any `\t` characters because of issues like this, what @bdorney was asking is if you have your editor configured to do this, which it appears you don't.
I'm not a `vi/vim` user, so I can't advise here, but you can probably search for "how to automatically convert all whitespace to space characters"

2019-05-14 15:43 UTC, bdorney commented on src/amc/sca.cpp
> +      response->set_word_array("data",outData.data(), outData.size());
I see, okay.  I will try to remember this moving forward.  Please address just the `set_word_array` comment above.

2019-05-14 15:45 UTC, bdorney commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
One could add `constexpr uint32_t FULL_OH_MASK = 0xfff` inside of:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/b358ed18fd77ed0625b5f04082df7d19da2d7ff6/include/hw_constants.h#L18-L26

And then `amc::FULL_OH_MASK` could be used here.

2019-05-14 15:46 UTC, bdorney commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
I still favor automatic determination of OH Mask though.

2019-05-14 15:48 UTC, bdorney commented on include/amc/sca_enums.h
> +	  case (VTTX_GEM_PT100): return true;
For `vim` you should add:

```vim
" show existing tab with 4 spaces width
set tabstop=4
```

To your `$HOME/.vimrc` to ensure a tab character is represented always as four space characters `\s`.  For `vi` I don't know; a google search would be needed.

2019-05-15 08:35 UTC, ram1123 commented on include/amc/sca_enums.h
> +	  case (VTTX_GEM_PT100): return true;
Thanks for pointing and suggestations. I will take care of this before making commit.

2019-05-15 08:48 UTC, ram1123 commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
Added like :

```cpp
  const uint32_t ohMask   = request->get_key_exists("ohMask") ? request->get_word("ohMask") : amc::FULL_OH_MASK;
  SCAADCChannelT  ch = static_cast<SCAADCChannelT>(request->get_key_exists("ch") ? request->get_word("ch") : 0x00);
```

2019-05-15 08:49 UTC, ram1123 commented on src/amc/sca.cpp
> +      LOGGER->log_message(LogManager::DEBUG, stdsprintf("Value for OH%i, SCA-ADC channel 0x%x = %i ",ohIdx, ch, val));
@jsturdy : Should I shift to hex?

2019-05-15 14:53 UTC, jsturdy commented on include/amc/sca_enums.h
> +	  case (VTTX_GEM_PT100): return true;
Don't think the suggestion is having the intended effect, see, e.g., [this](https://stackoverflow.com/questions/1878974/redefine-tab-as-4-spaces)

2019-05-15 14:54 UTC, jsturdy commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
You probably do not want to allow a default channel selection

2019-05-15 14:55 UTC, jsturdy commented on src/amc/sca.cpp
> +      LOGGER->log_message(LogManager::DEBUG, stdsprintf("Value for OH%i, SCA-ADC channel 0x%x = %i ",ohIdx, ch, val));
no comment means no preference

2019-05-15 14:58 UTC, ram1123 commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
@jsturdy : Should I throw an exception that no key exists?

2019-05-16 19:41 UTC, ram1123 commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
Changed it like:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/09d87c4195e039efa16615b5169d47c19c018397/src/amc/sca.cpp#L249-L250

2019-05-16 19:56 UTC, jsturdy commented on src/amc/sca.cpp
> +  uint32_t ohMask = request->get_word("ohMask");
You can't (shouldn't) `throw` from the RPC methods, there's nothing to catch it there.
Just do it like you had it before you addressed the comment about `ohMask`; the initial comment applied **only** to `ohMask`

2019-05-21 21:02 UTC, jsturdy approved these changes

2019-05-24 14:20 UTC, jsturdy commented
@mexanick, any objections to merging this?

2019-05-24 14:33 UTC, mexanick approved these changes
Cursory

2019-05-24 14:49 UTC, merged

2019-05-24 22:16 UTC, ram1123 commented
## Output values from the sensors

| Sensor ID | Info | ADC Count | Measured decimal Value| Expected value ([link](https://github.com/cms-gem-daq-project/ctp7_modules/blob/b358ed18fd77ed0625b5f04082df7d19da2d7ff6/include/amc/sca_enums.h#L211-L267))
| -------- | -------- | -------- |--- |---|
| 0x00    |    PT100    |    44    |    19 $^0C$ | -
| 0x04    |    PT100    |    44    |    19 $^0C$ |-
| 0x07    |    PT100    |    45    |    24.40 $^0C$ | -
| 0x08    |    PT100    |    44    |    19 $^0C$ | -
| 0x1F    |    SCA internal temperature | 2743    | 25 $^0C$ | -
| 0x1B    |    FPGA MGT Voltage | 1025 | 1 V | 1 V
| 0x1E    |    FPGA MGT Voltage | 1254 | 1.22 V | 1.2 V
| 0x11    |    FPGA core voltage | 1066| 1.04 V| 1.0 V
| 0x18    |    Power for GBTx and SCA | 1524 | 1.5 V| 1.5 V
| 0x0F    |    FPGA I/O power | 2620 | 2.6 V | 2.5 V
| 0x15    |    Signal strength of VTRX1 | 14 | 13 mV | -
| 0x13    |    Signal strength of VTRX1 | 14 | 13 mV |-
| 0x12    |    Signal strength of VTRX1 | 12 | 12 mV | -

## How the conversions are made

### ADC counts to voltage conversion

The output values are 12 bit ADC and the voltage value varies from 0 to 1 V. Thus, each bit corresponds to 1/2^{12} =~ 0.244 mV.

### PT100 Sensors 

- ADC count = 44
- Corresponding voltage = 44 x 0.244 mV = 10.736 mV
- We are measuring temperature using the platenium resistor from which 100 $\mu$A current is flowing
- Resistance = V/I = 10.736mV / 100 $\mu$ A = 107.36  $\Omega$
- Check the temperature corresponding to the 107.36 $\Omega$ resistance in the R - T table [1]. This corresponds to ~19 $^0 C$.


### SCA Internal temperature

- ADC count = 2743
- Corresponding voltage = 2743 X 0.244 mV = 669.68 mV
- Now look at the V-T graph. The voltage of 669.68 corresponds to ~25 $^0 C$.

<img width="928" alt="upload_70214b9a453866df6201dd01a97f9573" src="https://user-images.githubusercontent.com/5220316/58358921-32d1c500-7e81-11e9-8ae6-ae5c3a6805df.png">

The above V-T graph is taken from page 52 of GBT-SCA manual [2]



### Conversion of ADC for Voltage sensors

- ADC count = 1025
- As we can see from the image below there is a voltage divider having two resistor having values 3k and 1k each. So, need to multiply this by 4.

![upload_65554560d042b44d9ed7369b6cea3992](https://user-images.githubusercontent.com/5220316/58358934-48df8580-7e81-11e9-83c6-d29534acf581.png)

- Voltage  = 1025 * 0.244 * 4 mV ~= 1V

---

## Reference

1. [https://www.intech.co.nz/products/temperature/typert/RTD-Pt100-Conversion.pdf](https://www.intech.co.nz/products/temperature/typert/RTD-Pt100-Conversion.pdf)

2. [https://espace.cern.ch/GBT-Project/GBT-SCA/Manuals/GBT-SCA-UserManual.pdf](https://espace.cern.ch/GBT-Project/GBT-SCA/Manuals/GBT-SCA-UserManual.pdf)