GE2/1 compatilibility
cms-gem-daq-project/ctp7_modules pull request #132
Opened 2019-06-13 08:26 UTC by mexanick

Addressing #131 
## Description

* Adding hw_constants for ge21
* Implementing constants usage
* Minor improvements w.r.t warnings and gbt logging

The changes should be transparent and does not require changes in the other software for the GE1/1 usage

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

The hardware constants has to be defined in one place and corresponding compile-time switch has to be used
## How Has This Been Tested?

Tested with the GE2/1 integration stand setup
### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2019-06-13 15:22 UTC, jsturdy commented
Is this targeting "working now with setups that may be using legacy", if so, needs to target `release/1.1.X`, which is what I understand based on the dependent PRs

2019-06-13 17:53 UTC, bdorney commented on include/hw_constants.h
> +            constexpr std::array<std::array<uint16_t, 3>, 10> ELINK_TO_REGISTERS {
Unrelated to this PR; but now would be a good time to add a GE2/1 heading to the guide similar to this one:

https://github.com/cms-gem-daq-project/sw_utils/blob/develop/v3ElectronicsUserGuide.md#e-link-assignment-in-ge11

2019-06-13 17:56 UTC, bdorney commented on include/utils.h
> +                nTransactions+vfatErrs.nTransactions);
this is in the legacy branch already but one comment here is that I overlooked the possibility that overflow could occur in this addition here.  That is not presently handled and it might be better to change to:

```C++
        return slowCtrlErrCntVFAT(
                overflowTest(crc,vfatErrs.crc),
                overflowTest(packet,vfatErrs.packet),
                ...
                ... 
                overflowTest(nTransactions,vfatErrs.nTransactions));
```

2019-06-13 18:03 UTC, bdorney commented on src/calibration_routines.cpp
> +            for (unsigned int ohN = 0; ohN < amc::OH_PER_AMC; ++ohN) {
Some caution should be used here when designing a loop over the number of OH's; and it's been previously overlooked (now is probably a good time to address this).  Consider the case where you're running on a 4OH FW version; or a GLIB with a quad/octal SFP FMC added, the number of OH's is not 12.  Attempting to loop over `amc::OH_PER_AMC` may actually cause an error.  For example consider lines 651 & 652 below:

```C++
                        sprintf(regBuf,"GEM_AMC.OH.OH%i.FPGA.TRIG.CNT.VFAT%i_SBITS",ohN,vfat);
                        ohTrigRateAddr[ohN][vfat] = getAddress(la, regBuf);	                        ohTrigRateAddr[ohN][vfat] = getAddress(la, regBuf);
```

The `getAddress` call here would generate an error.

When looping over the number of OH's for this reason we may want to only loop over the number of OH's in the actual FW.  This of course requires a reg read to get this value; but perhaps it's also retrievable from the xml...?

2019-06-13 18:04 UTC, bdorney commented on src/calibration_routines.cpp
> +            for (unsigned int ohN = 0; ohN < amc::OH_PER_AMC; ++ohN) {
Alternatively `amc::OH_PER_AMC` could be a constant set at compile time.

2019-06-13 18:05 UTC, bdorney commented on src/calibration_routines.cpp
> +            uint32_t ohTrigRateAddr[amc::OH_PER_AMC][oh::VFATS_PER_OH + 1]; //idx 0->23 VFAT counters; idx 24 overall rate
Trailing comment here needs to be updated.

2019-06-13 18:05 UTC, bdorney commented on src/calibration_routines.cpp
> +            for (unsigned int ohN = 0; ohN < amc::OH_PER_AMC; ++ohN) {
My first comment above should be considered a "global comment" applied everywhere.

2019-06-13 18:07 UTC, bdorney commented on src/calibration_routines.cpp
>                          uint32_t notmask = ~vfatmask[ohN] & 0xFFFFFF;
Correct me if I'm wrong but doesn't this *also* need an update, e.g.:

```C++
uint32_t notmask = ~vfatmask[ohN] & 0xFFFFFF
```

The `0xFFFFFF` is now specific to `ge11` and `ge21` so this would need a constant no?

2019-06-13 18:07 UTC, bdorney commented on src/calibration_routines.cpp
>                          uint32_t notmask = ~vfatmask[ohN] & 0xFFFFFF;
Same comment as [here](https://github.com/cms-gem-daq-project/ctp7_modules/pull/132/files#r293509482) basically apply this everywhere.

2019-06-13 18:09 UTC, bdorney commented on src/calibration_routines.cpp
> +    for (unsigned int idx=0; idx < 3072; ++idx) {
the loop over the channel count is now also GE1/1 and GE2/1 dependent.

e.g. you need:

`ge11::CHANNELS_PER_OH`
`ge21::CHANNELS_PER_OH`

This could also have read "per detector" but since we are using the per amc/oh terminology the above is probably better.

2019-06-13 18:10 UTC, bdorney commented on src/calibration_routines.cpp
> +    for (unsigned int idx=0; idx < 3072; ++idx) {
Not sure where else 3072 comes up but it might be in other locations that aren't illustrated here because no changes were made in the vicinity.

2019-06-13 18:11 UTC, bdorney commented on src/calibration_routines.cpp
>                  int vfatObserved = 7-int(sbitAddress/192)+int((sbitAddress%192)/64)*8;
Is the sbit clustering and addressing system in GE1/1 the same as GE2/1? e.g. will these formulas to unpack the cluster word work for GE2/1?

2019-06-13 18:12 UTC, bdorney commented on src/calibration_routines.cpp
>                  int vfatObserved = 7-int(sbitAddress/192)+int((sbitAddress%192)/64)*8;
For sure there are no longer 1536 possible cluster addresses; so this would *also* need to be protected as a constant, e.g.

```C++
ge11::MAX_SBIT_ADDR_PER_OH
ge21::MAX_SBIT_ADDR_PER_OH
```

2019-06-13 18:12 UTC, bdorney commented on src/calibration_routines.cpp
> +    for (unsigned int idx=0; idx < 3072; ++idx) {
channel count number.

2019-06-13 18:13 UTC, bdorney commented on src/calibration_routines.cpp
> +    uint32_t ohTrigRateAddr[oh::VFATS_PER_OH + 2]; //idx 0->23 VFAT counters; idx 24 rate measured by OH FPGA; idx 25 rate measured by CTP7
trailing comment needs update.

2019-06-13 18:14 UTC, bdorney requested changes
some additional differences between GE1/1 and GE2/1 have been overlooked (e.g. sbit clustering); need additional `gemType` specific constants.  Target branch unclear.

2019-06-13 18:22 UTC, bdorney commented
It’s possible I missed other blocks in the code due to not appearing here. Especially in the calibration toolkit.

2019-06-17 09:36 UTC, lpetre-ulb requested changes
Very few comments in addition to @bdorney's that I fully agree with.

2019-06-17 09:36 UTC, lpetre-ulb commented on src/calibration_routines.cpp
> +std::unordered_map<uint32_t, uint32_t> setSingleChanMask(unsigned int ohN, unsigned int vfatN, unsigned int ch, localArgs *la)
Function signature is not updated in the header file.

2019-06-17 09:36 UTC, lpetre-ulb commented on include/hw_constants.h
> +        constexpr size_t OH_SINGLE_RAM_SIZE = 2*100; ///< Per-OH RAM size: for GE1/1 100 32-bit words of configuration per OH plus the corresponding OH local address
Trailing comment should be updates. In the following constants as well.

2019-06-18 12:10 UTC, mexanick commented on src/calibration_routines.cpp
> +            for (unsigned int ohN = 0; ohN < amc::OH_PER_AMC; ++ohN) {
I'd consider this as a separate issue as it is not really closely related to this PR. Also, IMHO a rule of thumb would be to always have a proper address table for 12 OHs in LMDB on all test stands.

2019-06-18 12:13 UTC, mexanick commented on src/calibration_routines.cpp
>                          uint32_t notmask = ~vfatmask[ohN] & 0xFFFFFF;
No, it is OK here, we never touch the chips above the `oh::VFATS_PER_OH`
So having it here as a maximum value constant is fine

2019-06-18 12:49 UTC, mexanick commented
@bdorney @lpetre-ulb your comments has been addressed except first one from @bdorney which I believe deserves a separate issue

2019-06-19 08:19 UTC, bdorney commented on src/calibration_routines.cpp
> +            for (unsigned int ohN = 0; ohN < amc::OH_PER_AMC; ++ohN) {
> IMHO a rule of thumb would be to always have a proper address table for 12 OHs in LMDB on all test stands.

How feasible is this for AMC's not the CTP7? I don't know enough about how we are doing the GLIB to know this myself.

2019-06-19 08:22 UTC, bdorney commented on src/calibration_routines.cpp
>                          uint32_t notmask = ~vfatmask[ohN] & 0xFFFFFF;
> No, it is OK here, we never touch the chips above the oh::VFATS_PER_OH
So having it here as a maximum value constant is fine

I guess my point here, and also with [this comment](https://github.com/cms-gem-daq-project/ctp7_modules/pull/132#discussion_r293507971) is to ensure a standardization through the repo where all constants/loop variables/etc... of this nature are specified in a single location.

Recall the issues we where debugging in the CSC office in 904 earlier this week?  We were using one namespace protected constant to get the VFAT mask but in another location we where looping over VFATs beyond that.  I think enforcing namespace protected constants in all cases like this would avoid possible issues in the future.

2019-06-19 08:23 UTC, bdorney commented on include/utils.h
> +                nTransactions+vfatErrs.nTransactions);
This comment is still relevant I think.

2019-06-19 08:26 UTC, bdorney commented on src/amc.cpp
> +            mask = mask - (0x1 << vfatN);
To increase reliability of the output of this function we could; in the case that `syncErrCnt == 0x0` add some slow control transaction on this VFAT.  This could be done with `repeatedRegRead` (with a small number of reads to keep this function "fast") or it could be done with a one-off read of say of the hardware version register or something similar.

However I'm fine with letting this go and not being addressed in this PR.

2019-06-19 08:26 UTC, bdorney commented on src/amc.cpp
> +            mask = mask - (0x1 << vfatN);
Also, nice solution.

2019-06-19 08:34 UTC, bdorney commented
After another pass on this PR I think the `struct ADCChannel` also needs to be done for both `ge11` and `ge21` namespaces as there are probably a different number (and location) of temperature sensors between GE2/1 and GE1/1 optohybrids: 

https://github.com/cms-gem-daq-project/ctp7_modules/blob/2c5d65f667e50ca95f733608e8768bf2086fd3f8/include/amc/sca_enums.h#L211-L267

Also I would suggest a look at all `struct`s and `enum`s declared here as they may *also* need namespace protection for things like different channels on the SCA ADC used to monitor different voltages, additional channels being used, additional monitoring, different pin out, etc...

I think we should address this given the board design has been completed in this PR.  Apologies for having missed this earlier.

2019-06-19 08:41 UTC, bdorney commented on src/calibration_routines.cpp
>                  int vfatObserved = 7-int(sbitAddress/192)+int((sbitAddress%192)/64)*8;
I see we added the namespace protected constants; but I think my first comment is still outstanding, e.g.:

> Is the sbit clustering and addressing system in GE1/1 the same as GE2/1? e.g. will these formulas to unpack the cluster word work for GE2/1?

Could we check with @andrewpeck that this is the case; if so then no issue.  Otherwise we will obviously need to handle this.

2019-06-19 08:42 UTC, bdorney commented on src/gbt.cpp
> +    //LOGGER->log_message(LogManager::INFO, stdsprintf("Writing %u to the VFAT #%u phase of OH #%u.", phase, vfatN, ohN));
I guess this was moved to line 194?  If so could we delete this commented line?

2019-06-19 08:44 UTC, bdorney requested changes
Some comments still outstanding and a look at the `sca_enums.h` is needed I think.

2019-06-19 09:42 UTC, jsturdy commented on src/calibration_routines.cpp
> +            for (unsigned int ohN = 0; ohN < amc::OH_PER_AMC; ++ohN) {
`OH_PER_AMC` (number of supported OHs) is a property of the FW, so @mexanick's point is feasible.
One could couple the LMDB fixed to 12, with any arrays fixed to 12 (or better yet, use dynamic containers), and in an implementation with fewer supported OHs, you have a check in whatever function so that you'll know what comes out is the "right size"

However, I agree that this is a separate issue, unless this code is targeting `develop` rather than the current release tree, as `develop` will be picking up the templating and this is much better suited to be addressed at that time.

2019-06-19 10:43 UTC, bdorney commented on src/calibration_routines.cpp
> +            for (unsigned int ohN = 0; ohN < amc::OH_PER_AMC; ++ohN) {
Current target branch is `develop`

2019-06-19 21:49 UTC, andrewpeck commented on src/calibration_routines.cpp
>                  int vfatObserved = 7-int(sbitAddress/192)+int((sbitAddress%192)/64)*8;
Hi Brian, the cluster formula is the same at the moment (which means there is a wasted bit).. eventually we could change it to regain the bit for other purposes but compatibility seems to be a better target right now rather than optimizing bandwidth.. we also have no identified use for the extra bits right now

2019-06-20 09:05 UTC, lpetre-ulb commented on src/calibration_routines.cpp
>                          uint32_t notmask = ~vfatmask[ohN] & 0xFFFFFF;
I fully agree that such constant should specified in a single location.

However, for this precise constant, what about removing it? I think it is only used in loops between 0 and `oh::VFATS_PER_OH` so it would be safe and we would get rid of one constant in both GE1/1 and GE2/1 code.

2019-06-20 09:11 UTC, lpetre-ulb commented on src/gbt.cpp
> +    //LOGGER->log_message(LogManager::INFO, stdsprintf("Writing %u to the VFAT #%u phase of OH #%u.", phase, vfatN, ohN));
Also, do we want to keep the `INFO` log level for this message since it the phase scans produce a lot of them? What about the general semantic of log levels? How can we change the `rpcsvc` log level on the fly? There is no API to change it and it is fixed at compile time... I guess this is how out of the scope of this PR though.

2019-06-20 09:25 UTC, lpetre-ulb requested changes
Some changes are still required, particularly in the SCA enums that I also completely overlooked during my first review. :-(

I think all the aliases should go into a `GEM_VARIANT` protected namespace since the mapping to ADC channels and GPIOs are differents. Once (or before) the ADC readout functions will be merged in the main branch some work will be also be required to make it compatible with GE2/1.

2019-06-20 09:46 UTC, bdorney commented on src/calibration_routines.cpp
>                          uint32_t notmask = ~vfatmask[ohN] & 0xFFFFFF;
If you get rid of this constant how do you determine `notmask`?  Maybe I misunderstood the proposal.  Using only `~vfatmask[ohN]` will flip all bits no, e.g. bits [25, 32].  This could be problematic no?

2019-06-20 09:46 UTC, bdorney commented on src/gbt.cpp
> +    //LOGGER->log_message(LogManager::INFO, stdsprintf("Writing %u to the VFAT #%u phase of OH #%u.", phase, vfatN, ohN));
Yeah this probably needs it's own issue.  Not something for this PR.

2019-06-20 12:14 UTC, lpetre-ulb commented on src/calibration_routines.cpp
>                          uint32_t notmask = ~vfatmask[ohN] & 0xFFFFFF;
As long as `notmask` is only used in `for`-loops it wouldn't be problematic. If it is used in other contexts then I fully support the constant in `hw_constants.h`.

I think the comment also applies to `ohMask` (line 610) : https://github.com/cms-gem-daq-project/ctp7_modules/blob/d384cbb0f58b93871e9b04799d2e3a70c1c1f6f2/src/calibration_routines.cpp#L606-L615

2019-06-20 12:23 UTC, mexanick commented on src/gbt.cpp
> +    //LOGGER->log_message(LogManager::INFO, stdsprintf("Writing %u to the VFAT #%u phase of OH #%u.", phase, vfatN, ohN));
I think the log level should be set by sysmgr, but I'm not 100% sure.

2019-06-20 12:25 UTC, mexanick commented
I agree that SCA enums has to be changed, but I don't have any info on this w.r.t. GE2/1. Can anyone point me to where I can get it?

2019-06-20 12:32 UTC, lpetre-ulb commented
@mexanick, you should be able to find all the information in the GE2/1 OH specification and/or on the GE2/1 OH schematic : http://padley.rice.edu/cms/OH_GE21/ohdesign.html

2019-06-20 12:39 UTC, lpetre-ulb commented on src/gbt.cpp
> +    //LOGGER->log_message(LogManager::INFO, stdsprintf("Writing %u to the VFAT #%u phase of OH #%u.", phase, vfatN, ohN));
Currently it is set [in `rpcsvc`](https://github.com/cms-gem-daq-project/rpcsvc/blob/f75364532253c93dbadece18b8be0fac7140236d/run_client.cpp#L6) and if the level given to `log_message` is below that value, the message is not even sent to the `syslog` daemon. I don't see how the `sysmgr` could help in this case... I'm going to open an issue.

2019-06-25 08:29 UTC, mexanick commented
Should these changes still go to develop or you prefer them to go under legacy/1.1.X branch?

2019-06-25 08:57 UTC, mexanick commented
Changed the target and performed a rebase

2019-06-25 09:10 UTC, bdorney approved these changes

2019-06-25 09:11 UTC, bdorney commented
Approving these changes per discussion in meeting; but if @mexanick you could open a new issue on the repo to address the SCA enum issues we discussed for GE1/1 vs. GE2/1 issues.

2019-06-25 09:47 UTC, jsturdy commented on include/calibration_routines.h
> +/*! \fn std::unordered_map<uint32_t, uint32_t> setSingleChanMask(unsigned int ohN, int vfatN, unsigned int ch, localArgs *la)
any reason `ohN` is changed to unsigned but not `vfatN`? (here and elsewhere)

2019-06-25 09:47 UTC, jsturdy commented on include/hw_constants.h
> +     */
should standardize a type for these constants probably...

2019-06-25 09:47 UTC, jsturdy commented on include/hw_constants.h
> +            constexpr std::array<std::array<uint16_t, 3>, 10> ELINK_TO_REGISTERS {
unrelated to this PR, but related to the comment, now would be a good time to convert the guide to a paginated format, a la gitbook

2019-06-25 09:47 UTC, jsturdy commented on src/amc.cpp
> +    for (unsigned int vfatN=0; vfatN<oh::VFATS_PER_OH; ++vfatN) { //Loop over all vfats
(here and elsewhere) why the affinity for `unsigned int` rather than `uintX_t` (as appropriate) or simply `unsigned`?

2019-06-25 10:52 UTC, mexanick commented on include/calibration_routines.h
> +/*! \fn std::unordered_map<uint32_t, uint32_t> setSingleChanMask(unsigned int ohN, int vfatN, unsigned int ch, localArgs *la)
no good reason - has to be standardized indeed. However a further refactoring should be done under a separate PR (also including other comments like that)

2019-06-25 12:06 UTC, jsturdy commented on include/calibration_routines.h
> +/*! \fn std::unordered_map<uint32_t, uint32_t> setSingleChanMask(unsigned int ohN, int vfatN, unsigned int ch, localArgs *la)
in that case i would suggest to either do all the changes for this PR, or none of the changes for this PR, e.g., revert the changes that have been introduced that are only partial...

2019-07-03 13:13 UTC, mexanick commented
Merging as is, further refactoring foreseen

2019-07-03 13:13 UTC, merged