New Feature: Parallel SBIT Rate Scan vs. Arbitrary Register
cms-gem-daq-project/ctp7_modules pull request #17
Opened 2018-02-12 09:25 UTC by bdorney

## Description

In Optohybrid v3 FW version [3.0.7.A](https://github.com/cms-gem-daq-project/OptoHybridv3/releases/tag/3.0.7.A) a set of new counters was added which measure the rate of sbits being sent from each VFAT individually.  I have added a new SBIT rate scan module `sbitRateScanParallelLocal(...)` which takes advantage of this new FW functionality.

However, due to the issues with Optohybrid FW versions v3.0.7.A (trigger link underflow error) and v3.0.8.A (VFATs kept in hard reset) it has not yet been possible to test yet.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

In the previous sbit rate scan `sbitRateScanLocal(...)` it was only possible to scan one VFAT at a time which caused the scan to take an exceptionally long time (especially in the case of a channel scan).  I had added `sbitRateScanParallelLocal(...)` which uses the new FW functionality (OHv3 version 3.0.7.A or higher) to scan all VFATs in parallel.

### Changes to sbitRateScan(const RPCMsg *request, RPCMsg *response)

The previous functionality, described in https://github.com/cms-gem-daq-project/ctp7_modules/pull/15, has been preserved.  New functionality has been added:

| Argument | Type | Description |
| ---------- | ----- | ----------- |
| `maskOh` | `uint32_t` | If the the `isParallel` flag is true this acts as the standard `vfatmask` otherwise see https://github.com/cms-gem-daq-project/ctp7_modules/pull/15. |
| `isParallel` | `bool` | If true `sbitRateScan(...)` will call `sbitRateScanParallelLocal(...)` instead of the series version `sbitRateScanLocal(...)`. |
| `data_trigRatePerVFAT` | `uint32_t *` | Pointer to an array that holds the trigger rate values for each VFAT for each scan point of `scanReg`. Note the size of the array is assumed to be `24*(dacMax - dacMin + 1)/dacStep`.  The `idx` for `vfatN` is `N*(dacVal-dacMin+1)/dacStep` and the `dacVal` that corresponds to this trigger rate is then `data_dacVal[idx]`. |

Please note `invertVFATPos` is not used in `sbitRateScanParallelLocal(...)` since from OH FW version [3.0.5.A](https://github.com/cms-gem-daq-project/OptoHybridv3/releases/tag/3.0.5.A) the VFAT numbering in the OH matches the "software" convention;  However since OH FW version 3.0.4.A is still the last "stable" FW release I have kept this flag.

Also the `waitTime` is not used in `sbitRateScanParallelLocal(...)` for simplicity.  The counters will increment for a total of 1 second (40,079,000 clock cycles), thus the rate is simply the count.

If `isParallel` is true then `sbitRateScanParallelLocal(...)` will be called and an additional word array will be retuned in the RPC response `data_trigRatePerVFAT`.  If `isParallel` is false then the current functionality will persist.

###  Description of sbitRateScanParallelLocal(...)

| Argument | Type | Description |
| ---------- | ----- | ----------- |
| `la` | `localArgs` | Struct containing the `rtxn`, `dbi` and RPC `response` objects. |
| `outDataDacVal` | `uint32_t *` | Pointer to an array that will hold the DAC values of each scan point of `scanReg`.  Note the size of the array is assumed to be `(dacMax - daxMin + 1) / dacStep`.  The `idx` position of this array represents the same scan point as the `outDataTrigRateOverall` argument. |
| `outDataTrigRatePerVFAT` | `uint32_t *` | Pointer to an array that holds the trigger rate values for each VFAT for each scan point of `scanReg`. Note the size of the array is assumed to be `24*(dacMax - dacMin + 1)/dacStep`.  The `idx` for `vfatN` is `N*(dacVal-dacMin+1)/dacStep` and the `dacVal` that corresponds to this trigger rate is then `outDataDacVal[idx]`. |
| `outDataTrigRateOverall` | `uint32_t *` | As `outDataDacVal` but for the y-values of the array. |
| `ohN` | `uint32_t` | Link on CTP7 to be scanned. | 
| `vfatmask` | `uint32_t` | VFAT mask to be used, e.g. `0x30` means all VFATs except for 4 & 5 will be scanned. |
| `ch` | `uint32_t` | VFAT Channel to be used, all other channels will be masked.  The original mask settings will be returned after the scan has completed.  Expected to be in the range [0,127].  Note if `ch=128` then the channel mask settings will not be altered and the rate measurement will be an `OR` of all channels. |
| `dacMin` | `uint32_t` | Starting value of `scanReg`.|
| `dacMax` | `uint32_t` | Final value of `scanReg`.|
| `dacStep` | `uint32_t` | Step size used to move from `dacMin` to `dacMax` of `scanReg`.|
| `scanReg` | `std::string` | Register to be scanned, the leading `CFG_` of the register name is omitted when passing to this argument. |

## How Has This Been Tested?

Due to a FW bug it hasn't yet.  When @andrewpeck releases the new OHv3a FW version addressing  [OptohybridV3 Issue #7](https://github.com/cms-gem-daq-project/OptoHybridv3/issues/7) testing will resume.

### Screenshots (if appropriate):

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-02-14 13:32 UTC, mexanick requested changes
Please move the commented pieces of the code to the separate methods to reduce code duplication

2018-02-14 13:32 UTC, mexanick commented on src/calibration_routines.cpp
> +    }
Lines 604-610 are often used by various methods. Suggestion: add new method taking the caller's name as a parameter:
```
int fw_version_check(std:: string & caller_name, localArgs *la,)
{
    int iFWVersion = readReg(la->rtxn, la->dbi, "GEM_AMC.GEM_SYSTEM.RELEASE.MAJOR");
    if (iFWVersion < 3){ //v2b electronics behavior
        sprintf(regBuf,"%s is Presently only supported in V3 Electronics", caller_name.c_str());
        la->response->set_string("error",regBuf);
    }
    return iFWVersion;
}
```
use this method where appropriate.

2018-02-14 13:32 UTC, mexanick commented on src/calibration_routines.cpp
> +
Lines 621-646 are used in multiple places. Please move them to a separate method, which should set new mask and return original

2018-02-14 13:32 UTC, mexanick commented on src/calibration_routines.cpp
> +        }
lines 692-694 should be moved the function `setChannelMask` and called as needed

2018-02-15 18:21 UTC, bdorney commented on src/calibration_routines.cpp
> +    }
Here the `caller_name` string is the function name that is calling `fw_version_check` right?

Additionally is there a way for it to determine `caller_name` automatically (e.g. `this->...`?).  Or should this be hard coded?

2018-02-15 18:26 UTC, bdorney commented on src/calibration_routines.cpp
> +        }
There is no such function yet...while there is some code here that is "duplicated" it is not done completely.  For example in the series case there is no loop over all VFATs.

I think adding this function is beyond the scope of this PR and deserves more thought/it's own PR.

2018-02-15 18:27 UTC, bdorney commented on src/calibration_routines.cpp
> +
see comment below.  Argue this is outside the scope of this PR and it deserves it's own issue/PR/

2018-02-15 18:30 UTC, bdorney commented on src/calibration_routines.cpp
> +    }
Also since this affects multiple functions and not just `sbitRateScanParallelLocal(...)` this should warrant it's own PR and is beyond the scope here.

2018-02-15 18:52 UTC, mexanick commented on src/calibration_routines.cpp
> +    }
My comment will apply to the cases below as well. I think it is a good idea to implement my suggestions now *and* make another issue about refactoring rest of the code. Just not make things even more duplicated. However if you insist on merging as is - we can do it. I let you decide. 
P.S. Yes, `caller_name` is the name of the function. It is not possible to pass it as `this`. In principle one can implement a so-called lazy callable, but it would be an over-complication here.

2018-02-15 19:47 UTC, bdorney commented
Baseline testing completed: http://cmsonline.cern.ch/cms-elog/1028798

Will need to consider adding requested functionality.

2018-02-16 10:19 UTC, mexanick approved these changes
Ok, I approve the PR since this is an important feature. However careful refactoring should be done in a very near future

2018-02-16 10:20 UTC, merged