Adopting uniform style in args passing
cms-gem-daq-project/ctp7_modules pull request #178
Opened 2020-03-31 13:40 UTC by mexanick

## Description

- all arguments for exported methods are passed as const T&
- style convention: use const T& t instead of const T &t. Reason: eases the regex parsing
- const T& t are used instead of T const& t in order to avoid confusion

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring

## Motivation and Context

Adresses #173 
## How Has This Been Tested?

The code compiles, functionality didn't change
### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-04-02 10:28 UTC, jsturdy commented on src/vfat3.cpp
> +void vfat3::setChannelRegistersVFAT3Simple::operator()(const uint16_t& ohN, const std::vector<uint32_t> &chanRegData, const uint32_t& vfatMask) const
regexp find/replace missed one at `chanRegData`

2020-04-02 10:42 UTC, jsturdy commented on src/vfat3.cpp
> +void vfat3::setChannelRegistersVFAT3Simple::operator()(const uint16_t& ohN, const std::vector<uint32_t> &chanRegData, const uint32_t& vfatMask) const
the version i was tweaking is https://github.com/cms-gem-daq-project/gembuild/blob/feature/common-formatting/.clang-format

2020-04-02 11:53 UTC, mexanick commented on src/vfat3.cpp
> +void vfat3::setChannelRegistersVFAT3Simple::operator()(const uint16_t& ohN, const std::vector<uint32_t> &chanRegData, const uint32_t& vfatMask) const
thanks, fixed

2020-04-03 16:44 UTC, lpetre-ulb requested changes
Only style comments, but since the PR is for the style...

2020-04-03 16:44 UTC, lpetre-ulb commented on include/ctp7_modules/common/amc/blaster_ram.h
> +            void operator()(BLASTERType const& type, const std::vector<uint32_t>& blob) const;
Should `const` be before `BLASTERType` according to the PR description?

2020-04-03 16:44 UTC, lpetre-ulb commented on include/ctp7_modules/common/amc/sca.h
> +      std::vector<uint32_t> operator()(const uint8_t& ch, const uint8_t& cmd, const uint8_t& len, const uint32_t&, const uint16_t& ohMask=0xfff) const;
The name of the fourth argument (`data`) has disappeared. This does not create any compilation issue, but makes the argument harder to be documented.

2020-04-03 16:44 UTC, lpetre-ulb commented on include/ctp7_modules/common/vfat3.h
> +    void operator()(const uint16_t& ohMask, const std::array<uint32_t, amc::OH_PER_AMC> & vfatMasks, const uint32_t& dacSelect) const;
Extra space in between `amc::OH_PER_AMC>` and `&`.

2020-04-03 16:44 UTC, lpetre-ulb commented on include/ctp7_modules/common/vfat3.h
> +    void operator()(const uint16_t& ohN, const std::vector<uint32_t> &chanRegData, const uint32_t& vfatMask=0xff000000) const;
`T &chanRegData` instead of `T& chanRegData`

2020-04-03 16:44 UTC, lpetre-ulb commented on include/ctp7_modules/common/vfat3.h
> +    std::vector<uint32_t> operator()(const uint16_t& ohN, const uint32_t& vfatMask=0xff000000, const bool &rawID=false) const;
`bool &rawID` instead of `bool& rawID`

2020-04-03 16:47 UTC, lpetre-ulb commented on src/vfat3.cpp
> +void vfat3::setChannelRegistersVFAT3Simple::operator()(const uint16_t& ohN, const std::vector<uint32_t> &chanRegData, const uint32_t& vfatMask) const
> the version i was tweaking is https://github.com/cms-gem-daq-project/gembuild/blob/feature/common-formatting/.clang-format

That's really nice there is a `clang-format` style somewhere! Is there any reason why not using a common style (`LLVM`, `Mozilla`, ...) instead of a heavily custom one? Is this custom style precisely documented?

2020-04-09 16:33 UTC, lpetre-ulb commented
@mexanick, any chance you could fix the latest comments soon? My hope is for this PR to be the final one in `develop` in this repository.

2020-04-09 17:34 UTC, mexanick commented
oh, thanks for reminder - I somehow missed your comments. Will fix soon

2020-04-09 19:52 UTC, lpetre-ulb approved these changes
Thank you for the fixes!

2020-04-09 20:01 UTC, merged