Add calibration routines to build threshold scan
cms-gem-daq-project/ctp7_modules pull request #2
Opened 2017-10-03 00:57 UTC by cbravo135

## Description

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

## How Has This Been Tested?

### Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-10-03 10:05 UTC, bdorney commented on src/calibration_routines.cpp
> +    if(ch==128)
Are VFAT3 channels indexed [1,128] or are they [0,127] with 128 being the calibration channel?

2017-10-03 10:07 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    if(ch==128)
Configuring the module to use "channel 128" will give an OR behavior of all 128 channels.

2017-10-03 10:07 UTC, bdorney commented on src/calibration_routines.cpp
> +        writeReg(la->rtxn, la->dbi, "GEM_AMC.GEM_TESTS.VFAT_DAQ_MONITOR.CTRL.VFAT_CHANNEL_SELECT", 0, la->response);
I see here the "channel" argument is 0, but ch in the if statement is checked against 128.  Why do we pass 0 here instead of 128?

2017-10-03 10:10 UTC, cbravo135 commented on src/calibration_routines.cpp
> +        writeReg(la->rtxn, la->dbi, "GEM_AMC.GEM_TESTS.VFAT_DAQ_MONITOR.CTRL.VFAT_CHANNEL_SELECT", 0, la->response);
It doesn't matter what VFAT_CHANNEL_SELECT is since VFAT_CHANNEL_GLOBAL_OR is written to 1.

2017-10-03 10:10 UTC, bdorney commented on src/calibration_routines.cpp
> +        uint32_t linkErrors = readReg(la->rtxn, la->dbi, std::string(regBase)+".SYNC_ERR_CNT");
Can we have `regBase`, `linkGood`, and `linkErrors` declared outside this loop (just below `goodVFATs`) rather than allocating the memory each iteration?

We can have them reset after line 38 if needed.

2017-10-03 10:12 UTC, cbravo135 commented on src/calibration_routines.cpp
> +        uint32_t linkErrors = readReg(la->rtxn, la->dbi, std::string(regBase)+".SYNC_ERR_CNT");
This is compiled C and not python, the memory is allocated on the stack at compilation anyways. These are just local buffers for building the strings needed to use the address table, it is important to think of scope of variables in C.

2017-10-03 10:13 UTC, bdorney commented on src/calibration_routines.cpp
> +struct localArgs {
This is declared as a global variable, is it possible that we put this, and all other function definitions here, inside of a namespace, e.g. `calibration`?

2017-10-03 10:13 UTC, cbravo135 commented on src/calibration_routines.cpp
> +struct localArgs {
This is C, so no namespaces.

2017-10-03 10:13 UTC, bdorney commented on src/calibration_routines.cpp
> +    struct localArgs la = {.rtxn = rtxn, .dbi = dbi, .response = response};
At line 4 you've declared `localArgs` as a struct globally, why are you re-declaring locally a `localArgs` struct?

2017-10-03 10:15 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    struct localArgs la = {.rtxn = rtxn, .dbi = dbi, .response = response};
It is not instantiated at line 4, just defined. https://www.tutorialspoint.com/cprogramming/c_structures.htm

2017-10-03 10:16 UTC, bdorney commented on src/calibration_routines.cpp
> +void vfatSyncCheck(const RPCMsg *request, RPCMsg *response)
I'm missing why this function is needed in addtion to `vfatSyncCheckLocal(...)`?  Is that because `vfatSyncCheckLocal(...)` local doesn't take RPCMsg request/response as arguments?  It's my ignorance but what is `vfatSyncCheck(...)` doing that `vfatSyncCheckLocal(...)` isn't?  Or how do they fit together in the bigger picture?

2017-10-03 10:17 UTC, cbravo135 commented on src/calibration_routines.cpp
> +void vfatSyncCheck(const RPCMsg *request, RPCMsg *response)
The non-local version of each function can be called externally by the host machine. The local version exists so we can use them locally without having to parse the address table again.

2017-10-03 10:17 UTC, bdorney commented on src/calibration_routines.cpp
> +void vfatSyncCheck(const RPCMsg *request, RPCMsg *response)
I guess I have the same question about all the other function pairs below:

- `ttcGenConfLocal(...)`, `ttcGenConf(...)`
- `thresholdScanLocal(...)`, `thresholdScan(...)`,
- etc...

I guess there's some architecture reason/design that I missed from last night?

2017-10-03 10:23 UTC, bdorney commented on src/calibration_routines.cpp
> +    for(int vfatN = 0; vfatN < 24; vfatN++) if((notmask >> vfatN) & 0x1)
for coding style/readability can we have these on two separate lines with braces modified appropriately.

2017-10-03 10:25 UTC, bdorney commented on src/calibration_routines.cpp
> +        for(int vfatN = 0; vfatN < 24; vfatN++) if((notmask >> vfatN) & 0x1)
same comment as above, split lines.

2017-10-03 10:25 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    for(int vfatN = 0; vfatN < 24; vfatN++) if((notmask >> vfatN) & 0x1)
This style of C is legitimate. This is easy to read as for every vfat not masked. I really don't like tons of extra unnecessary braces.

2017-10-03 10:28 UTC, cbravo135 commented on src/calibration_routines.cpp
> +        for(int vfatN = 0; vfatN < 24; vfatN++) if((notmask >> vfatN) & 0x1)
I argue this is more readable than your proposal.

2017-10-03 10:32 UTC, bdorney commented on src/calibration_routines.cpp
> +            outData[idx] = readRawReg(la->rtxn, la->dbi, regBuf, la->response);
Can we add a check somewhere that `outData` has this many elements?  e.g. This function should ensure the user passes it a pointer to an array of appropriate size.

2017-10-03 10:34 UTC, bdorney commented on src/calibration_routines.cpp
> +    response->set_word_array("data",outData,24*(dacMax-dacMin+1)/dacStep);
How does the user access `outData`?  It looks like Line 155 is written `outData` to a buffer?  Where/how does the user get this?

2017-10-03 10:34 UTC, cbravo135 commented on src/calibration_routines.cpp
> +            outData[idx] = readRawReg(la->rtxn, la->dbi, regBuf, la->response);
See line 153.

2017-10-03 10:35 UTC, jsturdy commented on src/calibration_routines.cpp
> +    for(int vfatN = 0; vfatN < 24; vfatN++) if((notmask >> vfatN) & 0x1)
The complaint is **not** about useless braces, rather about the "one statement per line" readability philosophy:
```c
for(int vfatN = 0; vfatN < 24; vfatN++)
  if((notmask >> vfatN) & 0x1) {
...
  } // closes if
```

2017-10-03 10:35 UTC, bdorney commented on src/calibration_routines.cpp
> +    RPCMsg *response;
Can we stick with a white space convention here like we do with our other repo's?  e.g. looks like some `\t` characters are present here.

2017-10-03 10:36 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    response->set_word_array("data",outData,24*(dacMax-dacMin+1)/dacStep);
I am still trying to get Misha to explain how that magic part works. The user will never access outData but rather what is packaged into the "data" word_array placed in response.

2017-10-03 10:36 UTC, bdorney commented on src/calibration_routines.cpp
> +    startScanModule(local_args->rtxn, local_args->dbi, local_args->response);
Where is `startScanModule(...)` defined?  Why is it now used in `thresholdScanLocal(...)`?

2017-10-03 10:38 UTC, bdorney commented on src/calibration_routines.cpp
> +    struct localArgs args = {.rtxn = rtxn, .dbi = dbi, .response = response};
Same comment as above regarding local vs. global `localArgs`

2017-10-03 10:38 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    startScanModule(local_args->rtxn, local_args->dbi, local_args->response);
This is not operational code, it is historic from when Misha was putting this initial version of this. The latency scan code does not work yet.

2017-10-03 10:39 UTC, bdorney requested changes
Changes requested and some clarifications needed.

2017-10-03 10:39 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    startScanModule(local_args->rtxn, local_args->dbi, local_args->response);
I will point out it is not used int threhsoldScanLocal, but rather latencyScanLocal.

2017-10-03 10:40 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    struct localArgs args = {.rtxn = rtxn, .dbi = dbi, .response = response};
This is C, don't know what else to tell you. It was never instantiated globally as you are implying.

2017-10-03 10:40 UTC, bdorney commented on src/calibration_routines.cpp
> +    if(ch==128)
Let's add a comment that states this here

2017-10-03 10:41 UTC, bdorney commented on src/calibration_routines.cpp
> +        writeReg(la->rtxn, la->dbi, "GEM_AMC.GEM_TESTS.VFAT_DAQ_MONITOR.CTRL.VFAT_CHANNEL_SELECT", 0, la->response);
In that case can we remove line 17 entirely so that only the `VFAT_CHANNEL_GLOBAL_OR` is present?

2017-10-03 10:42 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    RPCMsg *response;
Def'n no \t char here. I changed the spacing to be 4 instead of 2 for the whole file, that is what you are seeing.

2017-10-03 10:46 UTC, bdorney commented on src/calibration_routines.cpp
> +        uint32_t linkErrors = readReg(la->rtxn, la->dbi, std::string(regBase)+".SYNC_ERR_CNT");
I know the scope of the variables here. I'm asking to make this more efficient rather than having to allocate memory every iteration

2017-10-03 10:47 UTC, bdorney commented on src/calibration_routines.cpp
> +void vfatSyncCheck(const RPCMsg *request, RPCMsg *response)
Okay I see...so we should view the non-local version as executed only on the CTP7?  And the non-local version as what would be executed from the DAQ PC?

For this system we write software that is executed from the DAQ PC and then is run on the CTP7?  Then the user never calls the local versions?

2017-10-03 10:48 UTC, bdorney commented on src/calibration_routines.cpp
> +    struct localArgs la = {.rtxn = rtxn, .dbi = dbi, .response = response};
Sorry misread the line, didn't notice the `la =` part

2017-10-03 10:51 UTC, bdorney commented on src/calibration_routines.cpp
> +            outData[idx] = readRawReg(la->rtxn, la->dbi, regBuf, la->response);
I think this comes back to my comment above, how is `thresholdScanLocal(...)` used: 

1. Is it only ever called by `thresholdScan(...)`?  
2. Or is there some usage case where it would be called standalone?

If the usage case is #1 then yeah line 153 is sufficient, however if there would be a case where it is called standalone then a check of the array size is a good idea.

2017-10-03 10:51 UTC, bdorney commented on src/calibration_routines.cpp
> +    response->set_word_array("data",outData,24*(dacMax-dacMin+1)/dacStep);
Okay got it.  We wait for @mexanick.

2017-10-03 10:52 UTC, bdorney commented on src/calibration_routines.cpp
> +    startScanModule(local_args->rtxn, local_args->dbi, local_args->response);
Okay.  Suggest to add a comment that states this, or probably better to comment it out/delete it for now.

2017-10-03 10:54 UTC, bdorney commented on src/calibration_routines.cpp
> +    struct localArgs args = {.rtxn = rtxn, .dbi = dbi, .response = response};
Yeah, sorry I misread the line, didn't notice the 'args =' part

2017-10-03 11:16 UTC, cbravo135 commented on src/calibration_routines.cpp
> +void vfatSyncCheck(const RPCMsg *request, RPCMsg *response)
The local version exists so we can use them locally without having to parse the address table again. Parsing the address table takes several seconds.

2017-10-03 11:19 UTC, cbravo135 commented on src/calibration_routines.cpp
> +void vfatSyncCheck(const RPCMsg *request, RPCMsg *response)
It is impossible for the user to call the local versions, they are not registered in the library. See the end of the file to see the registered functions.

2017-10-03 11:21 UTC, cbravo135 commented on src/calibration_routines.cpp
> +        uint32_t linkErrors = readReg(la->rtxn, la->dbi, std::string(regBase)+".SYNC_ERR_CNT");
The memory is allocated on the stack at compilation, and is only accessed each iteration. Your proposal would be not be any more efficient, and if ever reset for some reason it would become less efficient.

2017-10-03 11:23 UTC, cbravo135 commented on src/calibration_routines.cpp
> +        writeReg(la->rtxn, la->dbi, "GEM_AMC.GEM_TESTS.VFAT_DAQ_MONITOR.CTRL.VFAT_CHANNEL_SELECT", 0, la->response);
Evaldas recommended to write it to 0 as I have done in this case.

2017-10-03 11:24 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    for(int vfatN = 0; vfatN < 24; vfatN++) if((notmask >> vfatN) & 0x1)
"for every vfat not masked" is a single statement expressed by this one line.

2017-10-03 11:26 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    startScanModule(local_args->rtxn, local_args->dbi, local_args->response);
We need a comment to say this library is a work in progress and is not complete yet?

2017-10-03 11:32 UTC, cbravo135 commented
This code definitely can be cleaned and optimized. This PR is about functionality. If you don't want this code because of where I declare variables, it doesn't matter to me. I still have the code and can run the scans myself to get results, just thought others might want to have this new functionality.

2017-10-03 11:41 UTC, cbravo135 commented
I would call this code more middleware than software. This goal here is to make it easier for the user to interact with the FW on the CTP7. We no longer have a scan module in fw for V3, so this piece of middleware that runs on the CTP7 will have to take the place of that fw module. The goal here is to provide a library for easy access by the developer of the user system. Modifying this is easier than modifying fw, but not as easy as changing the over arching python code. This is meant to be a module the python code can call, no DOC should ever directly interact with this code. We don't ask the DOCs to look into the fw do we?

2017-10-03 11:46 UTC, mexanick commented on src/calibration_routines.cpp
> +        uint32_t linkErrors = readReg(la->rtxn, la->dbi, std::string(regBase)+".SYNC_ERR_CNT");
Well, to be clear: what you guys say depends on how do you compile and which compilation flags are involved. If your compiler optimizes the code (what's done in this case), then Cameron's comment is spot on. Otherwise there could be options. 
Although this code can benefit from certain refactoring, I would postpone it to the future PRs.

2017-10-03 11:48 UTC, mexanick commented on src/calibration_routines.cpp
> +    for(int vfatN = 0; vfatN < 24; vfatN++) if((notmask >> vfatN) & 0x1)
I support Cameron in this case. No need for few extra lines and aligned blocks.

2017-10-03 11:53 UTC, mexanick commented on src/calibration_routines.cpp
> +            outData[idx] = readRawReg(la->rtxn, la->dbi, regBuf, la->response);
the thresholdScanLocal method can not be called standalone, it doesn't have appropriate interface for this. However, it can be used as a sub-call of other methods, not limiting to threshold scan only.
There's another reason for a such architecture: for the moment all the methods are so-called blocking transactions. I.e. you block and RPC connection during execution time. The goal for future is to spawn detached threads for the calibration routines (executing those local methods) and return the interfacing RPC call ASAP.

2017-10-03 11:56 UTC, mexanick commented on src/calibration_routines.cpp
> +    response->set_word_array("data",outData,24*(dacMax-dacMin+1)/dacStep);
The communication between host module and remote method is based on exchange of RPCMsg objects. There're two such objects: _request_ and _response_. You can find the description of the RPCMsg class here: https://github.com/cms-gem-daq-project/ctp7_modules/blob/master/include/wiscRPCMsg.h#L1

2017-10-03 12:00 UTC, mexanick commented on src/calibration_routines.cpp
> +    startScanModule(local_args->rtxn, local_args->dbi, local_args->response);
@bdorney , the templates for functions which are not implemented aims V2 system design. Actually, certain things has been implemented and work. I can remove them, but I need a management decision that **we are not going to use RPC calls for V2 setup**

2017-10-03 12:25 UTC, jsturdy commented on src/calibration_routines.cpp
> +    for(int vfatN = 0; vfatN < 24; vfatN++) if((notmask >> vfatN) & 0x1)
`for` and `if` are functionally two separate statements; that they combine in your use case to provide some logical construct is irrelevant.
Code readability is **critical** for maintainability, especially in the case that the original developer leaves; please don't underestimate this

2017-10-03 12:29 UTC, jsturdy commented on src/calibration_routines.cpp
> +    startScanModule(local_args->rtxn, local_args->dbi, local_args->response);
I would stress that adding in RPC calls for V2 has always been "in the plan", as we have an actual system where it can be fully tested, and which will ensure that things can be as compatible as possible between V2 and V3 (which has also, always been the plan)

2017-10-03 14:04 UTC, bdorney commented on src/calibration_routines.cpp
> +        uint32_t linkErrors = readReg(la->rtxn, la->dbi, std::string(regBase)+".SYNC_ERR_CNT");
> Although this code can benefit from certain refactoring, I would postpone it to the future PRs.

Since we will be building on this as we move forward in the long run it would save time to commit things right the first time.  As I have said many times, in general we shouldn't do things that only benefit us this week.  

If the group feels this is not an issue then okay.

2017-10-03 14:04 UTC, bdorney commented on src/calibration_routines.cpp
> +struct localArgs {
kk my mistake

2017-10-03 14:05 UTC, bdorney commented on src/calibration_routines.cpp
> +            outData[idx] = readRawReg(la->rtxn, la->dbi, regBuf, la->response);
Okay I understand, thanks to you both for the clarification (here and in the comment above).

2017-10-03 14:06 UTC, bdorney commented on src/calibration_routines.cpp
> +    response->set_word_array("data",outData,24*(dacMax-dacMin+1)/dacStep);
I guess I'm still confused on how you write a script on the local PC that executes all this and reads back the data.  Maybe we are not there yet though?

2017-10-03 14:06 UTC, bdorney commented on src/calibration_routines.cpp
> +    RPCMsg *response;
My mistake.  Thanks for pointing this out.

2017-10-03 14:08 UTC, bdorney commented on src/calibration_routines.cpp
> +    startScanModule(local_args->rtxn, local_args->dbi, local_args->response);
I did not realize this was supposed to be for both v2 and v3.  Maybe it's better to have two different branches?  If this code is working for the v2b system but not yet for the v3 I think it's better to have this as a different branch and have this commented out/missing.  But if the group wants a different approach then no problem.

2017-10-03 22:17 UTC, mexanick approved these changes

2017-10-03 22:32 UTC, mexanick requested changes

2017-10-03 22:32 UTC, mexanick commented on src/calibration_routines.cpp
> +            la->response->set_string("error","Brian, it doesn't make sense to calpulse all channels");
Lol. Don't personalize the error message :D

2017-10-03 22:32 UTC, mexanick commented on src/calibration_routines.cpp
> +void genScanLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t mask, uint32_t ch, uint32_t enCal, uint32_t nevts, uint32_t dacMin, uint32_t dacMax, uint32_t dacStep, std::string scanReg)
This function will benefit from logging. Would be nice to log at INFO level what we are scanning, limits and step.

2017-10-03 22:32 UTC, mexanick commented on src/calibration_routines.cpp
> +        la->response->set_string("error",regBuf);
When error is detected I think it would be also good to log it at the same time. Here and in other places as well.

2017-10-03 22:41 UTC, mexanick commented on include/vfat3.h
> +        std::string configFileBase = "/mnt/persistent/gemdaq/vfat3/config_OH"+std::to_string(ohN)+"_VFAT"+std::to_string(vfatN)+".txt";
I would give some more freedom to the config file name/location. We may have few different configuration sets stored at the CTP7 (like in V2 we have different ztrims)

2017-10-04 07:10 UTC, bdorney commented on include/vfat3.h
> +        std::string configFileBase = "/mnt/persistent/gemdaq/vfat3/config_OH"+std::to_string(ohN)+"_VFAT"+std::to_string(vfatN)+".txt";
Can we have the linux partition of the CTP7 mount an external location?  In this way we could use the identical structure to what we have now, e.g. `$DATA_PATH/configs`.

2017-10-04 07:29 UTC, bdorney commented on src/calibration_routines.cpp
> +void genScanLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t mask, uint32_t ch, uint32_t enCal, uint32_t nevts, uint32_t dacMin, uint32_t dacMax, uint32_t dacStep, std::string scanReg)
What are the list of possible values for `scanReg`?  I see this is designed to be an arbitrary scan application.  More of a syntax question. e.g.

- For VT1 `scanReg` = ???
- For latency `scanReg` = ??? 
- etc...

2017-10-04 07:31 UTC, bdorney commented on src/calibration_routines.cpp
> +void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
Did we drop the non-local version of this function?  If so why?

2017-10-04 07:34 UTC, cbravo135 commented on src/calibration_routines.cpp
> +void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
No it just lives in vfat3.h now.

2017-10-04 07:35 UTC, bdorney commented on src/calibration_routines.cpp
> +    writeReg(la->rtxn, la->dbi, "GEM_AMC.TTC.GENERATOR.SINGLE_RESYNC", 0x1, la->response);
Lines 54 & 56, why do we have these here instead of a call of `ttcGenConfLocal(...)`?  Is the user supposed to call `ttcGenConf(...)` before calling `genScan(...)`?

2017-10-04 07:37 UTC, cbravo135 commented on include/vfat3.h
> +        std::string configFileBase = "/mnt/persistent/gemdaq/vfat3/config_OH"+std::to_string(ohN)+"_VFAT"+std::to_string(vfatN)+".txt";
We need to meet and discuss this. Using CTP7 Zynq resources is a limited resource, and we need to agree on a philosophy about how we will use it. I think of it equivalent to an embedded system, and in that case all of this "software" (which I would rather call middleware) would be part of the "firmware" code. This is not really an embedded system, and it is able to run linux. I still think we should treat it as a glorified embedded system and all of this code should be super minimalist and leave the heavy lifting to the host computer. This softens up the fw on the CTP7 and makes it more usable by the sw layer on the host computer. We need to be careful what we ask the CTP7 to do. Adding a network mount, at least to me, is completely out of the question.

2017-10-04 07:37 UTC, bdorney commented on src/calibration_routines.cpp
> +void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
Was it renamed?  I don't see it.  Or maybe you made changes that weren't pushed to your remote yet?

2017-10-04 07:38 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    writeReg(la->rtxn, la->dbi, "GEM_AMC.TTC.GENERATOR.SINGLE_RESYNC", 0x1, la->response);
yes, just as it is done now in all of the scan sw.

2017-10-04 07:41 UTC, bdorney commented on src/calibration_routines.cpp
> +    writeReg(la->rtxn, la->dbi, "GEM_AMC.TTC.GENERATOR.SINGLE_RESYNC", 0x1, la->response);
Okay, thanks.  What about line 56?

2017-10-04 07:43 UTC, cbravo135 commented on src/calibration_routines.cpp
> +void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
Ah no, this configures the daq monitoring, I should rename it. This does not have a non-local version on purpose, only methods in this package should ever be calling this.

2017-10-04 07:44 UTC, cbravo135 commented on src/calibration_routines.cpp
> +void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
vfat configuration is now configureVFAT3s in vfat3.h

2017-10-04 07:52 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    writeReg(la->rtxn, la->dbi, "GEM_AMC.TTC.GENERATOR.SINGLE_RESYNC", 0x1, la->response);
Why would it be in ttcGenConfLocal? The question doesn't make any sense, we are sending a resync right before we start to run the actual scan, this is what we want.

2017-10-04 07:54 UTC, cbravo135 commented on src/calibration_routines.cpp
> +    writeReg(la->rtxn, la->dbi, "GEM_AMC.TTC.GENERATOR.SINGLE_RESYNC", 0x1, la->response);
If anything, we could have it in both places. We want this here, it isn't going away.

2017-10-04 07:54 UTC, bdorney commented on src/calibration_routines.cpp
> +    writeReg(la->rtxn, la->dbi, "GEM_AMC.TTC.GENERATOR.SINGLE_RESYNC", 0x1, la->response);
I don't know, that's why I'm asking.  What does a single resync here do and why is it appropriate here and not in `ttcGenConfLocal(...)`?

2017-10-04 07:55 UTC, bdorney commented on src/calibration_routines.cpp
> +    writeReg(la->rtxn, la->dbi, "GEM_AMC.TTC.GENERATOR.SINGLE_RESYNC", 0x1, la->response);
I'm not asking for it to go away, I'm asking to understand what it does.

2017-10-04 08:05 UTC, cbravo135 commented on src/calibration_routines.cpp
> +void genScanLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t mask, uint32_t ch, uint32_t enCal, uint32_t nevts, uint32_t dacMin, uint32_t dacMax, uint32_t dacStep, std::string scanReg)
VT1 no longer exists. This can be literally any dac on the VFAT3, so please refer to his address table if you want to know the names of the dacs on the VFAT3.

2017-10-04 08:08 UTC, bdorney commented on src/calibration_routines.cpp
> +void genScanLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t mask, uint32_t ch, uint32_t enCal, uint32_t nevts, uint32_t dacMin, uint32_t dacMax, uint32_t dacStep, std::string scanReg)
Yeah I understood it could be any DAC on the VFAT3, do you have the link/filepath of the address table?  Thanks.

2017-10-04 08:12 UTC, bdorney commented on src/calibration_routines.cpp
> +void genScanLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t mask, uint32_t ch, uint32_t enCal, uint32_t nevts, uint32_t dacMin, uint32_t dacMax, uint32_t dacStep, std::string scanReg)
What does `enCal` do or supposed to represent?  It doesn't look it's really used yet.  I guess a future feature?  What is the goal?

2017-10-04 08:23 UTC, mexanick commented on include/vfat3.h
> +        std::string configFileBase = "/mnt/persistent/gemdaq/vfat3/config_OH"+std::to_string(ohN)+"_VFAT"+std::to_string(vfatN)+".txt";
Network mount is not an option. Not because we can't do this or it is "too heavy for Zynq", but because it is slow by construction. Also we have more than enough space to keep couple of versions of the config. However not ALL the config versions will be kept there, just the ones we consider as often-used.

2017-10-04 08:24 UTC, cbravo135 commented on src/calibration_routines.cpp
> +        la->response->set_string("error",regBuf);
Yeah, Evaldas and I were just trying to save time by not putting the ctp7 logging everywhere.

2017-10-04 08:41 UTC, bdorney commented on include/vfat3.h
> +        std::string configFileBase = "/mnt/persistent/gemdaq/vfat3/config_OH"+std::to_string(ohN)+"_VFAT"+std::to_string(vfatN)+".txt";
One thought: what about making a `struct` for the VFAT3 parameters if one does not already exist?  

Then `configureVFAT3sLocal(...)` could fill this struct by default from the input file but then additional arguments (words) could be added to `configureVFAT3sLocal` (`configureVFAT3s`) to allow for more configurable parameters at runtime from the host PC?

2017-10-04 08:43 UTC, mexanick commented
I'm going to do the forces merge of this PR. Please open issues/questions to discuss the remaning points. The reason of such action is that we need a quick code turnaround to avoid huge PRs.

2017-10-04 08:43 UTC, mexanick approved these changes

2017-10-04 08:43 UTC, merged