Refactoring, documentation and status/monitoring tools
cms-gem-daq-project/ctp7_modules pull request #29
Opened 2018-03-09 18:16 UTC by mexanick

Fixes #21, #25, #27 and adds documentation and status/monitoring tools
Requires https://github.com/cms-gem-daq-project/xhal/pull/54
## Description

**New features**:
* `statusVFAT3s` method 
* `statusOH` method
* added `Doxygen`-style documentation
* Major refactoring, headers and sources are properly populated now, `Makefile` altered to reflect the changes

**Breaking changes**:
* Modules updated according to name conventions described in #6 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Provides documentation and puts code in better order
## How Has This Been Tested?

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-04-03 13:23 UTC, bdorney commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
On the CTP7 I think we should add monitoring for the following registers:

```
eagle60 > kw SBIT_OVERFLOW_CNT
0x66000680 r    GEM_AMC.TRIGGER.OH0.LINK0_SBIT_OVERFLOW_CNT             0x00000000
0x66000680 r    GEM_AMC.TRIGGER.OH0.LINK1_SBIT_OVERFLOW_CNT             0x00000000
eagle60 > kw MISSED_COMMA_CNT
0x66000684 r    GEM_AMC.TRIGGER.OH0.LINK0_MISSED_COMMA_CNT              0x00000000
0x66000684 r    GEM_AMC.TRIGGER.OH0.LINK1_MISSED_COMMA_CNT              0x00000000
eagle60 > kw OVERFLOW_CNT
0x66000680 r    GEM_AMC.TRIGGER.OH0.LINK0_SBIT_OVERFLOW_CNT             0x00000000
0x66000680 r    GEM_AMC.TRIGGER.OH0.LINK1_SBIT_OVERFLOW_CNT             0x00000000
0x6600068c r    GEM_AMC.TRIGGER.OH0.LINK0_OVERFLOW_CNT                  0x00000000
0x6600068c r    GEM_AMC.TRIGGER.OH0.LINK1_OVERFLOW_CNT                  0x00000000
```

I didn't find them presently with a quick `ctrl+F`.

2018-04-03 13:25 UTC, bdorney commented on src/calibration_routines.cpp
> +void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
I think it's more appropriate for this to reside in `amc.cpp`.

2018-04-03 13:26 UTC, mexanick commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
I was following @evka85 guidelines. Also I'd like to underline this method remains same between V2 and V3.

2018-04-03 13:28 UTC, mexanick commented on src/calibration_routines.cpp
> +void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
Disagree. This is calibration-specific method.

2018-04-03 13:45 UTC, bdorney requested changes
Changes requested.  I think for long-term maintenance we should move some functions around and come up with a developer guideline which should be:

> actions performed on a piece of hardware should then go in that hardware's header and source files (e.g. `dacMonConfLocal(...)` and nonlocal version should be in `src/amc.cpp`

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> + *  * v3  electronics: enable = true (false) ignore (take) ttc commands from backplane for this AMC
While this is technically correct, it is misleading.  This is a legacy comment from when I didn't really understand the system.

It should instead read something like `turns on the TTC.GENERATOR` which will disable TTC commands from the backplane, but it will start sending TTC commands to the front-ends using whatever the configuration of the `TTC.GENERATOR` block is configured to do.

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> +                writeReg(la, "GEM_AMC.TTC.GENERATOR.ENABLE", 0x1); //Internal, TTC cmds from backplane are ignored
again here, the comment in the code is technically correct, but misleading, see comment to line 102.

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> +void ttcGenToggleLocal(localArgs * la, uint32_t ohN, bool enable)
Again I would suggest to have `ttcGenToggleLocal(...)` moved to `src/amc.cpp`

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> + *  * v3  electronics: enable = true (false) ignore (take) ttc commands from backplane for this AMC
same comment as line 102.

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> +void ttcGenToggle(const RPCMsg *request, RPCMsg *response)
Suggest to move to `src/amc.cpp`

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> + *    * enable = true (false) ignore (take) ttc commands from backplane for this AMC (affects all links)
same as comment for line 102.

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> +void ttcGenConfLocal(localArgs * la, uint32_t ohN, uint32_t mode, uint32_t type, uint32_t pulseDelay, uint32_t L1Ainterval, uint32_t nPulses, bool enable)
Again should move to `src/amc.cpp`

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> +unsigned int fw_version_check(const char* caller_name, localArgs *la)
Suggest to move this to `src/amc.cpp` as it is more appropriate (it's an AMC related function anyway).

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> +std::unordered_map<uint32_t, uint32_t> setSingleChanMask(int ohN, int vfatN, unsigned int ch, localArgs *la)
this might be more appropriate for `src/vfat3.cpp`.  This isn't really a _calibration scan_

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> +void applyChanMask(std::unordered_map<uint32_t, uint32_t> map_chanOrigMask, localArgs *la)
this might be more appropriate for src/vfat3.cpp. This isn't really a calibration scan

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
>  void ttcGenConf(const RPCMsg *request, RPCMsg *response)
suggest to move to `src/amc.cpp`.  Again, not a _calibration scan_

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> -     *      enable = true (false) ignore (take) ttc commands from backplane for this AMC (affects all links)
same comment as for line 102.

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> +    writeReg(la, stdsprintf("GEM_AMC.OH.OH%i.TRIG.CNT.SBIT_CNT_TIME_MAX",ohN), 0x02638e98); //count for 1 second
Should we use this opportunity to address the following issue brought up by @andrewpeck: https://github.com/cms-gem-daq-project/ctp7_modules/issues/30

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
> +        writeReg(la, stdsprintf("GEM_AMC.OH.OH%i.TRIG.CNT.RESET",ohN), 0x1);
Should we use this opportunity to address the following issue brought up by @andrewpeck: https://github.com/cms-gem-daq-project/ctp7_modules/issues/30

2018-04-03 13:45 UTC, bdorney commented on src/calibration_routines.cpp
>          sprintf(regBuf,"GEM_AMC.OH.OH%i.TRIG.CNT.VFAT%i_SBITS",ohN,vfat);
Should we use this opportunity to address the following issue brought up by @andrewpeck: https://github.com/cms-gem-daq-project/ctp7_modules/issues/30

2018-04-03 13:45 UTC, bdorney commented on src/optohybrid.cpp
> +}
What's our strategy here?  For `v2b` it makes sense to have functions like this in `src/optohybrid.cpp` since the `OHv2b` is actually doing this transaction.  However in `v3` the `CTP7` is doing this via the `GBT` on the `OHv3`.

Should we: 

1. keep these here,
2. move them to `src/amc.cpp` since this card is making the action, or
3. move them to `src/vfat3.cpp` since the hybrid is what is being manipulated?

For reference I speak of:
- `biasAllVFATsLocal(...)`,
- `setAllVFATsToRunModeLocal(...)`,
- `setAllVFATsToSleepModeLocal(...)`,
- `loadVT1local(...)`,
- `loadTRIMDACLocal(...)`,
- `configureVFATs(...)`.

And their non-local counterparts if applicable.

2018-04-03 13:45 UTC, bdorney commented on src/optohybrid.cpp
> +void stopCalPulse2AllChannelsLocal(localArgs *la, uint32_t ohN, uint32_t mask, uint32_t ch_min, uint32_t ch_max){
I think this should move to `src/vfat3.cpp`

2018-04-03 13:45 UTC, bdorney commented on src/optohybrid.cpp
> +    uint32_t fw_maj = readReg(la, "GEM_AMC.GEM_SYSTEM.RELEASE.MAJOR");
Probably make use of `fw_version_check()` here?

2018-04-03 13:45 UTC, bdorney commented on src/optohybrid.cpp
> +void stopCalPulse2AllChannels(const RPCMsg *request, RPCMsg *response){
Probably should move to `src/vfat3.cpp`

2018-04-03 13:47 UTC, bdorney commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
For the monitoring I think we could add a case statement that if `fw_version_check()` gives `v3` we should add these lines.

The user (or a DAQ expert) needs to see those registers above to know if the trigger links for a given OH work.  If those counters are not small or are rolling up then a reset is needed to the trigger block.

2018-04-03 13:49 UTC, bdorney commented on src/calibration_routines.cpp
> +void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
While yes this method is calibration specific, it is not a _calibration scan_.  You could change this to `calibration_utilities.cpp` but since this is manipulating a piece of Hardware (the AMC) I think it's more appropriate to go there.

Overall for long-term maintenance I think this strategy would be more effective (e.g. functions that manipulate a given piece of hardware are found in that hardware's source/header files).  While the calibration scans themselves are located in `src/calibration_scans.cpp`.

2018-04-05 09:26 UTC, mexanick commented on src/calibration_routines.cpp
> +void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
Well, it is `calibration_routines.cpp`... I think this point you made deserves a separate issue. @jsturdy what do you think?

2018-04-05 10:20 UTC, mexanick commented on src/calibration_routines.cpp
>          sprintf(regBuf,"GEM_AMC.OH.OH%i.TRIG.CNT.VFAT%i_SBITS",ohN,vfat);
here I doubt it will be correct as this is a `TRIGGER` block

2018-04-05 10:20 UTC, mexanick commented on src/calibration_routines.cpp
> +        writeReg(la, stdsprintf("GEM_AMC.OH.OH%i.TRIG.CNT.RESET",ohN), 0x1);
done

2018-04-05 10:20 UTC, mexanick commented on src/calibration_routines.cpp
> +    writeReg(la, stdsprintf("GEM_AMC.OH.OH%i.TRIG.CNT.SBIT_CNT_TIME_MAX",ohN), 0x02638e98); //count for 1 second
done

2018-04-05 10:21 UTC, mexanick commented on src/optohybrid.cpp
> +}
again, this is an issue I would consider separately from this refactoring.

2018-04-05 10:23 UTC, mexanick commented on src/optohybrid.cpp
> +    uint32_t fw_maj = readReg(la, "GEM_AMC.GEM_SYSTEM.RELEASE.MAJOR");
eventually yes, a good point for a next refactoring PR. Would leave it as is ftm

2018-04-05 10:25 UTC, mexanick commented
Last commit pushed fixes documentation and issue #30 
I do believe the other comments while being very important, should be addressed in another PR.

2018-04-05 10:33 UTC, bdorney commented on src/calibration_routines.cpp
>          sprintf(regBuf,"GEM_AMC.OH.OH%i.TRIG.CNT.VFAT%i_SBITS",ohN,vfat);
Right this is measured by the CTP7 not the OH, my bad.

2018-04-05 10:36 UTC, bdorney commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
Still need the above registers in the case of the v3 firmware.

2018-04-05 10:39 UTC, bdorney requested changes
Okay, while I don't see why the additional refactoring for long-term organisation and maintenance I have suggested cannot be done now, I can let it go for the moment.

However, we *do* need the additional trigger link monitoring registers in the `getmonTRIGGEROHmainLocal()` function.  Or if there is a more appropriate function then they could go there.  But they are needed.  

If we can put those registers in the trigger monitor then I'll approve this PR.

2018-04-05 10:42 UTC, bdorney commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
For example both [sbitThreshScanSeries.py](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/rpc-playground/sbitThreshScanSeries.py) and [sbitThreshScanParallel.py](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/rpc-playground/sbitThreshScanParallel.py) will return garbage if the trigger links are not good which can be checked by investigating the counters listed above.

2018-04-05 10:55 UTC, mexanick commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
I can add the above registers, but aren't they covered by already existing `LINK0_NOT_VALID_CNT`? We don't want *all* info to go here, but only the most important (also because of interface limitations...) That's why I would like to have @evka85 opinion on this

2018-04-05 10:57 UTC, mexanick commented
I don't want an additional refactoring here because this PR is already big. And there're other in-queue PRs for which these changes are very desired.

2018-04-05 11:04 UTC, bdorney commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
Presently a trigger link valid register doesn't seem to exist in FW (and addrTable) version 3.4.5:

```
eagle60 > kw LINK1_NOT_VALID_CNT
LINK1_NOT_VALID_CNT not found!
eagle60 > kw LINK0_NOT_VALID_CNT
LINK0_NOT_VALID_CNT not found!
```

The reg's I have are:

```
eagle60 > kw TRIGGER
0x66000000 None         GEM_AMC.TRIGGER
0x66000000 None         GEM_AMC.TRIGGER.CTRL
0x66000000 w    GEM_AMC.TRIGGER.CTRL.MODULE_RESET
0x66000004 w    GEM_AMC.TRIGGER.CTRL.CNT_RESET
0x66000008 rw   GEM_AMC.TRIGGER.CTRL.OH_KILL_MASK                       0x00000000
0x66000040 None         GEM_AMC.TRIGGER.STATUS
0x66000040 r    GEM_AMC.TRIGGER.STATUS.OR_TRIGGER_RATE                  0x02638e98
0x66000044 r    GEM_AMC.TRIGGER.STATUS.OR_TRIGGER_CNT                   0xffffffff
0x66000200 None         GEM_AMC.TRIGGER.SBIT_MONITOR
0x66000200 w    GEM_AMC.TRIGGER.SBIT_MONITOR.RESET
0x66000204 rw   GEM_AMC.TRIGGER.SBIT_MONITOR.OH_SELECT                  0x00000000
0x66000208 r    GEM_AMC.TRIGGER.SBIT_MONITOR.CLUSTER0                   0x00000000
0x6600020c r    GEM_AMC.TRIGGER.SBIT_MONITOR.CLUSTER1                   0x00000000
0x66000210 r    GEM_AMC.TRIGGER.SBIT_MONITOR.CLUSTER2                   0x00000000
0x66000214 r    GEM_AMC.TRIGGER.SBIT_MONITOR.CLUSTER3                   0x00000000
0x66000218 r    GEM_AMC.TRIGGER.SBIT_MONITOR.CLUSTER4                   0x00000000
0x6600021c r    GEM_AMC.TRIGGER.SBIT_MONITOR.CLUSTER5                   0x00000000
0x66000220 r    GEM_AMC.TRIGGER.SBIT_MONITOR.CLUSTER6                   0x00000000
0x66000224 r    GEM_AMC.TRIGGER.SBIT_MONITOR.CLUSTER7                   0x00000000
0x66000228 r    GEM_AMC.TRIGGER.SBIT_MONITOR.L1A_DELAY                  0x175fa956
0x66000400 None         GEM_AMC.TRIGGER.OH0
0x66000400 r    GEM_AMC.TRIGGER.OH0.TRIGGER_RATE                        0x02638e98
0x66000404 r    GEM_AMC.TRIGGER.OH0.TRIGGER_CNT                         0xffffffff
0x66000440 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_0_RATE                 0x00000000
0x66000444 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_1_RATE                 0x02638e98
0x66000448 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_2_RATE                 0x00000000
0x6600044c r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_3_RATE                 0x00000000
0x66000450 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_4_RATE                 0x00000000
0x66000454 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_5_RATE                 0x00000000
0x66000458 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_6_RATE                 0x00000000
0x6600045c r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_7_RATE                 0x00000000
0x66000460 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_8_RATE                 0x00000000
0x66000480 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_0_CNT                  0x0000010a
0x66000484 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_1_CNT                  0xffffffff
0x66000488 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_2_CNT                  0x00000000
0x6600048c r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_3_CNT                  0x00000000
0x66000490 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_4_CNT                  0x00000000
0x66000494 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_5_CNT                  0x00000000
0x66000498 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_6_CNT                  0x00000000
0x6600049c r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_7_CNT                  0x00000000
0x660004a0 r    GEM_AMC.TRIGGER.OH0.CLUSTER_SIZE_8_CNT                  0x00000007
0x66000680 r    GEM_AMC.TRIGGER.OH0.LINK0_SBIT_OVERFLOW_CNT             0x00000000
0x66000680 r    GEM_AMC.TRIGGER.OH0.LINK1_SBIT_OVERFLOW_CNT             0x00000000
0x66000684 r    GEM_AMC.TRIGGER.OH0.LINK0_MISSED_COMMA_CNT              0x00000000
0x66000684 r    GEM_AMC.TRIGGER.OH0.LINK1_MISSED_COMMA_CNT              0x00000000
0x6600068c r    GEM_AMC.TRIGGER.OH0.LINK0_OVERFLOW_CNT                  0x00000000
0x6600068c r    GEM_AMC.TRIGGER.OH0.LINK1_OVERFLOW_CNT                  0x00000000
0x66000690 r    GEM_AMC.TRIGGER.OH0.LINK0_UNDERFLOW_CNT                 0x00000004
0x66000690 r    GEM_AMC.TRIGGER.OH0.LINK1_UNDERFLOW_CNT                 0x00000004
0x66000694 r    GEM_AMC.TRIGGER.OH0.LINK0_SYNC_WORD_CNT                 0x00000000
0x66000694 r    GEM_AMC.TRIGGER.OH0.LINK1_SYNC_WORD_CNT                 0x00000000
```

Reg's for link 1 were not shown.

2018-04-05 11:12 UTC, mexanick commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
indeed you're right! I'll check with @evka85

2018-04-13 20:35 UTC, mexanick commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
ok, fixed now.

2018-04-16 17:39 UTC, bdorney requested changes
Realized my comment was still marked as "pending" since I didn't press `submit review` button.  Oops.  Anyway, it is unclear if the last commit `2d22de6` solved the issue in `getmontriggerOHmainLocal(...)` or if this was solved via a FW update by @evka85.  If solved via a FW update could you point to the release on `GEM_AMC` repo where it is solved?

2018-04-16 17:39 UTC, bdorney commented on src/amc.cpp
> +void getmonTRIGGEROHmainLocal(localArgs * la, int NOH)
The code doesn’t look like it changed. Was their a FW update?

2018-04-16 19:25 UTC, mexanick commented
The issue is solved by this commit: https://github.com/cms-gem-daq-project/ctp7_modules/pull/29/commits/2d22de6b1018c2410de5c3f9893c12bc17891c4a
I don't know why it doesn't appear in a main dialog window where you've started a review... Maybe it holds the old one... However the change is there

2018-04-16 19:28 UTC, bdorney approved these changes

2018-04-16 19:28 UTC, merged