[WIP] New Feature: Cross-check SBIT Mapping & Rate Calculation in OH FPGA
cms-gem-daq-project/ctp7_modules pull request #43
Opened 2018-08-03 11:29 UTC by bdorney

## Description

Work in progress.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

## How Has This Been Tested?

### Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-08-16 14:45 UTC, mexanick requested changes

2018-08-16 14:45 UTC, mexanick commented on src/calibration_routines.cpp
> +void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t vfatN, uint32_t mask, bool useCalPulse, bool currentPulse, uint32_t calScaleFactor, uint32_t nevts, uin
Please add somewhere the sbit cluster description

2018-08-16 15:18 UTC, bdorney commented on src/calibration_routines.cpp
> +void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t vfatN, uint32_t mask, bool useCalPulse, bool currentPulse, uint32_t calScaleFactor, uint32_t nevts, uin
Done

2018-08-16 15:28 UTC, mexanick commented on src/calibration_routines.cpp
> +void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t vfatN, uint32_t mask, bool useCalPulse, bool currentPulse, uint32_t calScaleFactor, uint32_t nevts, uin
I meant put this things into description which is picked by documentation handler:
https://github.com/cms-gem-daq-project/ctp7_modules/blob/8d5d5bc6f5d7dd42007acdd21bf1146c2b6ee52f/src/calibration_routines.cpp#L1079

2018-08-16 15:50 UTC, bdorney commented on src/calibration_routines.cpp
> +void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t vfatN, uint32_t mask, bool useCalPulse, bool currentPulse, uint32_t calScaleFactor, uint32_t nevts, uin
I'm not sure I understand, I've added a description here:

> The sbit size is the number of trigger pads from the sbit reported that where part of this cluster, size ranges from 0 to 7.

But I think documentation here should really be in the address table of both the CTP7 and OH firmware (or some guide there in).  This is retrieving info from the `SBIT_MONITOR` block of the CTP7 FW which is being sent sbits on the GEM trigger link from the OH.

It would be better to have this in the FW documentation to prevent it being updated in one place and not forward propagated in another.  

Anyway I can add additional description but I think @andrewpeck and @evka85 should have some documentation for this.

2018-08-17 08:40 UTC, mexanick commented on src/calibration_routines.cpp
> +void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t vfatN, uint32_t mask, bool useCalPulse, bool currentPulse, uint32_t calScaleFactor, uint32_t nevts, uin
I think it is better to have it in two places rather then nowhere =) Please, add these three lines, I believe the code documentation will benefit of this and other software developers will be grateful to have the docs in one place =)

2018-08-17 08:42 UTC, bdorney commented on src/calibration_routines.cpp
> +void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, uint32_t ohN, uint32_t vfatN, uint32_t mask, bool useCalPulse, bool currentPulse, uint32_t calScaleFactor, uint32_t nevts, uin
okay will do.

2018-08-20 13:51 UTC, mexanick approved these changes

2018-08-20 14:11 UTC, merged