[WIP] read the number of OHs from the AMC register
cms-gem-daq-project/ctp7_modules pull request #51
Opened 2018-10-01 11:00 UTC by AndrewLevin

Currently the number of OHs is hardcoded as 12. This pull request reads this number from the NUM_OF_OH AMC register, as requested in the issue https://github.com/cms-gem-daq-project/ctp7_modules/issues/49

## Description

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context
There may be a different number of links on an OH, as explained in https://github.com/cms-gem-daq-project/ctp7_modules/issues/49. Instead of hardcoding the number or passing the number as a parameter to the rpc call, the number can be easily read from the NUM_OF_OH AMC register.

## How Has This Been Tested?
The changes compile. They have not been tested on the ctp7.

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-10-03 15:32 UTC, AndrewLevin commented
@dorney, @sturdy, @mexanick, all tests were successful, so the pull request is ready for your review

2018-10-03 15:39 UTC, bdorney requested changes
Seems like this PR does not provide a check if the key `NOH` exists or not.  This was mentioned in issue #49.  Additionally monitoring functions (now in `daq_monitor.cpp`) could benefit from a similar treatment.  Please add.

2018-10-03 16:32 UTC, AndrewLevin commented
@dorney, so if the `NOH` key exists, I should use it, and if the key does not exist, then I should use the number in the NUM_OF_OH register?

2018-10-03 16:37 UTC, bdorney commented
> @dorney, so if the NOH key exists, I should use it, and if the key does not exist, then I should use the number in the NUM_OF_OH register?

Yes, I would also make a check that the value of the `NOH` key does not exceed `NUM_OF_OH` if it does there should be a `WARN` (or `WARNING`?) level message printed to the CTP7 log and then an automatic reset to `NUM_OF_OH` (this should be included in the log)

e.g. "NOH requested > NUM_OF_OH, reseting NOH to NUM_OF_OH"

2018-10-03 22:49 UTC, AndrewLevin commented
@bdorney, I made the requested change, rebuilt the .so files, tested them on eagle64, and found the test is successful

2018-10-04 13:41 UTC, bdorney commented on src/amc.cpp
> +            NOH = request->get_word("NOH");
Why call this method twice?  Why not set to a temp variable and then assign to `NOH` if the `if` statement evaluates to `true`?

2018-10-04 13:43 UTC, bdorney commented
> @bdorney, I made the requested change, rebuilt the .so files, tested them on eagle64, and found the test is successful

You're missing the requested changes to `daq_monitor` functions.

2018-10-04 13:55 UTC, AndrewLevin commented on src/amc.cpp
> +            NOH = request->get_word("NOH");
@bdorney, I just made an update in which I changed to using a temporary variable

2018-10-04 14:03 UTC, AndrewLevin commented
@bdorney, in daq_monitor.cc, NOH appears both as a function argument (e.g. in getmonTRIGGERmainLocal) and as a request key (e.g. in getmonOHmain). Please clarify how you would like me to treat the two cases. In both cases, should I reset NOH to NUM_OF_OH if the NOH request is larger?

2018-10-04 18:19 UTC, bdorney commented
> @bdorney, in daq_monitor.cc, NOH appears both as a function argument (e.g. in getmonTRIGGERmainLocal) and as a request key (e.g. in getmonOHmain). Please clarify how you would like me to treat the two cases. In both cases, should I reset NOH to NUM_OF_OH if the NOH request is larger?

I think there's no need to change the local function, since it's taken as an argument and if it's called from another function on the card register access is O(50us).

The non-local versions modify as you have done before.  Does that clarify things?

2018-10-04 18:22 UTC, bdorney commented
The real goal is that we want to steer away from hard coding the number of OH's per AMC since this is expected to change in the case of GE2/1; but may of these functions will use pieces of the FW that will be common to all GEM subsystems (e.g. SCA block, Sysmon block, VFAT address space, etc...).

This will reduce overall complexity and increase functionality.  The address space of the FPGA may change, but as long as the node names in remain the same in the xml this can be 100% handled by simply having a different xml and different contents of lmdb on the CTP7.

2018-10-04 20:42 UTC, AndrewLevin commented
@bdorney, I have now implemented the same logic for the NOH variables in daq_monitor that are read from the rpc request, please have a look

2018-10-05 07:17 UTC, bdorney commented
Please update the PR description to reflect the changes made (e.g. functions modified in daq_monitor are not mentioned in the description).

2018-10-05 08:04 UTC, AndrewLevin commented
@bdorney, it is updated now

2018-10-05 08:05 UTC, bdorney approved these changes

2018-10-09 07:58 UTC, mexanick approved these changes

2018-10-09 07:59 UTC, merged