[WIP] add three new structs to pass a large number of arguments cleanly
cms-gem-daq-project/ctp7_modules pull request #63
Opened 2018-10-28 10:12 UTC by AndrewLevin

Some of the functions in calibration_routines.cpp and optohybrid.cpp now take a large number of arguments. There is also large overlap between the arguments that the different functions take. We can use structs to more elegantly pass these arguments.

## Description
Three new structs have been defined in `include/utils.h` for calpulse-related arguments, scan-related arguments, and ttcgen-related arguments:

```
struct ParamCalPulse{
    bool enable; //true (false) turn on (off) calpulse
    bool isCurrent; //true (false) is current injection (voltage pulse)

    uint32_t duration; //duration in BX's (CFG_CAL_DUR)
    uint32_t extVoltStep; //External voltage step 0->disable; 1->enable (CFG_CAL_EXT)
    uint32_t height; //height of calpulse (CFG_CAL_DAC)
    uint32_t phase; //phase of calpulse (CFG_CAL_PHI)
    uint32_t polarity; //polarity of calpulse 0->pos; 1->neg (CFG_CAL_SEL_POL)
    uint32_t scaleFactor; //current pulse scale factor (CFG_CAL_FS)

    ParamCalPulse(){
        enable = false;
        isCurrent = false;

        duration = 0x1ff;
        extVoltStep = 0x0;
        height = 0x0;
        phase = 0x0;
        polarity = 0x0;
        scaleFactor = 0x0;
    }
}; //End ParamCalPulse

struct ParamScan{
    //Hardware selection
    uint32_t ohN;
    uint32_t ohMask;
    uint32_t vfatN;
    uint32_t vfatMask;
    uint32_t chan;      //channel of interest

    //Params
    bool useUltra;
    bool useExtTrig;

    uint32_t dacMax;    //Maximum dac value
    uint32_t dacMin;    //Minimum dac value
    uint32_t dacSelect; //DAC to use for Monitoring
    uint32_t dacStep;   //step size for dac
    uint32_t nevts;     //Number of events
    uint32_t waitTime;  //unit of time; uints depend on function

    std::string scanReg;     //Register to scan against

    ParamScan(){
        vfatMask = 0x0;
        ohMask = 0xfff;

        useUltra = true;
        useExtTrig = false;

        dacMax=254;
        dacMin=0;
        dacStep=1;
        nevts=100;
    }
}; //End ParamScan

struct ParamTtcGen{
    bool enable;

    uint32_t L1Ainterval;
    uint32_t mode;
    uint32_t nPulses;
    uint32_t pulseDelay;
    uint32_t pulseRate;
    uint32_t type;

    ParamTtcGen(){
        enable = false;

        L1Ainterval = 250;
        pulseDelay = 40;
        pulseRate = 40079000 / L1Ainterval;
    }

    uint32_t calcRate(){
        if(L1Ainterval > 0){
            pulseRate = 40079000 / L1Ainterval;
        }
        else{
            pulseRate = 0;
        }

        return pulseRate;
    }
}; //End ParamTtcGen
```
The following 9 functions have been modified to take these structs:

`confCalPulseLocal` in `src/calibration_routines.cpp`
`ttcGenConfLocal` in `src/calibration_routines.cpp`
`genScanLocal` in `src/calibration_routines.cpp`
`sbitRateScanLocal` in `src/calibration_routines.cpp`
`sbitRateScanParallelLocal` in `src/calibration_routines.cpp`
`checkSbitMappingWithCalPulseLocal` in `src/calibration_routines.cpp`
`checkSbitRateWithCalPulseLocal` in `src/calibration_routines.cpp`
`configureScanModuleLocal` in `src/optohybrid.cpp`
`getUltraScanResultsLocal` in `src/optohybrid.cpp`

All of the places where these functions are called have been modified to pass these structs.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context
This change was requested in https://github.com/cms-gem-daq-project/ctp7_modules/issues/62

## How Has This Been Tested?
The changes compile. They have not yet been tested on a ctp7.

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-10-28 11:19 UTC, bdorney reviewed
Know this is WIP but direction should be corrected before you get to far in testing. Propagate comments through to all functions

2018-10-28 11:19 UTC, bdorney commented on src/calibration_routines.cpp
> +/*! \fn void confCalPulseLocal(localArgs *la, ParamCalPulse calParams, ParamScan scanParams)
Pass these as pointers; you’re duplicating the memory needed.

2018-10-28 11:19 UTC, bdorney commented on src/calibration_routines.cpp
> + *  \param scanParams Scan-related arguments (useExtTrig, useUltra, ohN, nevts, vfatMask, chan, dacMin, dacMax, dacStep, scanReg)
This help is not descriptive, what is scanParams? E.g. it’s an instance of the ParamsScan struct.

2018-10-28 11:19 UTC, bdorney commented on src/calibration_routines.cpp
> +    ptg.enable = enable;
Variable names should be descriptive; easy to understand and maintain. Try to use a common convention. E.g. in local functions you’re using scanParams, and in non-local functions you’re using ps. Be consistent.

2018-10-28 11:19 UTC, bdorney commented on src/calibration_routines.cpp
> +    ps.useUltra = useUltra;
You’re duplicating memory here. E.g. you’re creating a book useUltra to store the value from the rpc msg and then you’re only ever using this book to set the corresponding bool in the ParamsScan struct.  This is sloppy and will be hard to maintain in the long run. Just set the struct when getting the value from the rpc message.

2018-10-28 11:20 UTC, bdorney commented on src/calibration_routines.cpp
> +    ps.useUltra = useUltra;
Book = bool

2018-10-28 15:17 UTC, AndrewLevin commented on src/calibration_routines.cpp
> +/*! \fn void confCalPulseLocal(localArgs *la, ParamCalPulse calParams, ParamScan scanParams)
done

2018-10-28 15:17 UTC, AndrewLevin commented on src/calibration_routines.cpp
> + *  \param scanParams Scan-related arguments (useExtTrig, useUltra, ohN, nevts, vfatMask, chan, dacMin, dacMax, dacStep, scanReg)
changed

2018-10-28 15:18 UTC, AndrewLevin commented on src/calibration_routines.cpp
> +    ptg.enable = enable;
fixed

2018-10-28 15:18 UTC, AndrewLevin commented on src/calibration_routines.cpp
> +    ps.useUltra = useUltra;
changed

2018-11-02 10:09 UTC, AndrewLevin commented
@bdorney, which tests would you look to see run for this PR?

2018-11-07 15:16 UTC, bdorney commented
> @bdorney, which tests would you look to see run for this PR?

Every function that you modified should be tested on a real system to ensure behavior hasn't changed.  You should first trace down which rpc modules are used by which SW tools and confirm that they are still usable and give expected results/outputs/behavior.  This might require an afternoon or two of testing on the coffin setup.

2018-11-13 12:07 UTC, AndrewLevin commented
@bdorney, where did you envision that the `calcRate` function in the `ParamTtcGen` `struct` would be used?

2018-11-13 14:17 UTC, bdorney commented
> @bdorney, where did you envision that the calcRate function in the ParamTtcGen struct would be used?

If a user provides an `L1AInterval` but not a rate this `L1AInterval` is then used to determine the pulse rate via `calcRate`.

2018-11-13 15:34 UTC, AndrewLevin commented
ok, in ctp7_modules, it seems that the inverse case, the `pulseRate` is used to calculate the `L1AInterval`, is used:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/ab9f57487ab79e3f37710da4db84835d80b1401f/src/calibration_routines.cpp#L1195-L1201

2018-11-13 16:03 UTC, bdorney commented
> ok, in ctp7_modules, it seems that the inverse case, the `pulseRate` is used to calculate the `L1AInterval`, is used:
> 
> [ctp7_modules/src/calibration_routines.cpp](https://github.com/cms-gem-daq-project/ctp7_modules/blob/ab9f57487ab79e3f37710da4db84835d80b1401f/src/calibration_routines.cpp#L1195-L1201)
> Lines 1195 to 1201 in [ab9f574](/cms-gem-daq-project/ctp7_modules/commit/ab9f57487ab79e3f37710da4db84835d80b1401f)
>  uint32_t L1Ainterval; 
>  if(pulseRate > 0){ 
>      L1Ainterval = int(40079000 / pulseRate); 
>  } 
>  else{ 
>      L1Ainterval = 0; 
>  }

That's only in this specific function which is specifically making a test of rate, the user does not supply `L1AInterval` here, in *other* functions `L1Atime` is specified.

2018-11-19 14:17 UTC, bdorney commented
You'll need to update your local copy of `develop` and rebase this PR off of that since https://github.com/cms-gem-daq-project/ctp7_modules/pull/71 was merged.

2018-12-17 14:37 UTC, jsturdy requested changes
Couple of tweaks, couple of suggested improvements

2018-12-17 14:37 UTC, jsturdy commented on include/utils.h
> +/*! \struct ParamTtcGen
Re comments in other threads, style should be to use "almost" camel case: for types (`struct`s and `class`es, use `PascalCase`, variables use `CamelCase`, the distinction is that the first letter is capitalized for `PascalCase`)
Then, within the name, any acronym, e.g., `TTC`, `DAC`, should *always* be capitalized completely, or completely uncapitalized, based on how the style rule would otherwise apply, e.g., 
```c++
ParamTTCGen ttcConfig;
```

2018-12-17 14:37 UTC, jsturdy commented on include/utils.h
> +    uint32_t L1Ainterval; //How often to repeat signals
Here, as in the previous comment, the style rule is not followed, so I would suggest `L1Ainterval` -> `interval` **unless**, the TTC module can be configured to have different intervals, e.g., interval between L1A and some other command (which I see you have already defined below) and "interval" would become ambiguous.

How else can this module be configured?
* Is `nPulses`  just the number of pulses?  Or is it the number of `type` signals? Does the module keep sending L1As after sending `nPulses` pulses?
* I'd suggest dropping `pulse` from the variable names, as it seems that this `struct` could(should?) be rather more generic

2018-12-17 14:37 UTC, jsturdy commented on src/calibration_routines.cpp
> +        dacScanResults = dacScanLocal(&la, &scanParams, useExtRefADC);
Got some extra whitespace here.

2018-12-17 14:37 UTC, jsturdy commented on include/utils.h
> +
Ignorance here, but are `ohN` and `ohMask` ever used concurrently? Does the function using this `ParamScan` `struct` know whether it's operating on a single OH or on multiples? (same comment for `vfatN` and `vfatMask`)
If they are used simultaneously, the structure makes sense, if not, you can get by with just `oh` and `vfat` and the code that uses this `struct` would appropriately fill the parameter with either the specific device, or the masked list of devices (on the other end, the code receiving the `struct` should also not get confused, so the first question should be answered also for that)

2018-12-17 14:37 UTC, jsturdy commented on include/utils.h
> +    uint32_t dacStep;   //step size for dac
Is `dac` really necessary here? Why not just `min/max/select/step`?

2018-12-18 09:10 UTC, AndrewLevin commented on include/utils.h
> +/*! \struct ParamTtcGen
done

2018-12-18 09:11 UTC, AndrewLevin commented on src/calibration_routines.cpp
> +        dacScanResults = dacScanLocal(&la, &scanParams, useExtRefADC);
done

2018-12-18 09:14 UTC, AndrewLevin commented on include/utils.h
> +    uint32_t dacStep;   //step size for dac
I would say they are needed, since this struct is used for many types of scans, and just having `min` and `max` could lead to confusion. For example, in an scurve scan min and max could potentially refer to the minimum and maximum channel number to be scanned.

2018-12-18 09:37 UTC, jsturdy commented on include/utils.h
> +    uint32_t dacStep;   //step size for dac
Can they?  Is it not understood (documented) that these are for the thing being scanned (channel is very rarely (never?) *the* thing that is being scanned).  The `struct` already has a channel field, no?
Since this `struct` was created with `dac` in the field names, it's clearly **not** been used for this purpose yet.
I suppose this is the trouble with trying to implement a generic object...
Think through all the current use cases (and if there are future ones that are envisioned, but not yet implemented), and then make sure that the `struct` is well documented for the various use cases.  If that is done, then the potential confusion becomes a problem with someone not reading the documentation...

2018-12-18 12:58 UTC, AndrewLevin commented on include/utils.h
> +    uint32_t dacStep;   //step size for dac
OK, I have changed dacMin, dacMax, and dacStep to just min, max, and step. I left dacSelect as dacSelect, since that is a special setting for the DAC scans

2018-12-18 13:38 UTC, AndrewLevin commented on include/utils.h
> +
`vfatN` and `vfatMask` are used simultaneously here:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/d565057cf54791a568cb2f922963c0291cb153e6/src/calibration_routines.cpp#L833-L878

I guess it is because the current pulse needs to be disabled in all channels in all vfats that are present other than the one of interest, and we cannot assume that all vfats 24 vfats are present or alive.

`ohN` and `ohMask` are used simultaneously in a case where `ohMask` actually represents a mask of vfats (see the discussion in https://github.com/cms-gem-daq-project/ctp7_modules/issues/62#issuecomment-433712988):

https://github.com/cms-gem-daq-project/ctp7_modules/blob/d565057cf54791a568cb2f922963c0291cb153e6/src/calibration_routines.cpp#L655-L658

2018-12-18 14:31 UTC, AndrewLevin commented on include/utils.h
> +    uint32_t L1Ainterval; //How often to repeat signals
I have changed `L1AInterval` to `interval` and `pulseDelay` to `delay` and left the other members of ``ParamTTCGen` the same. It is not clear to me either whether`nPulses` only applies to the pulses or other types of signals, but it seems that it is only relevant for v2b electronics

https://github.com/cms-gem-daq-project/ctp7_modules/blob/d565057cf54791a568cb2f922963c0291cb153e6/include/calibration_routines.h#L154-L172

which I thought were already deprecated?

2018-12-18 17:03 UTC, jsturdy commented on include/utils.h
> +
* In the first example `ohN` is an index and `vfatN` is as well. `vfatMask` is the mask indicating which VFATs are "alive" but should not "participate".  Is this routine designed to only ever run on a *single* VFAT on a *single* at any given time?  If yes, then any `mask` can be inferred/derived based on the provided `ohN` and `vfatN` fields and the `mask` fields become redundant.

* In the second example I see `ohN` is used as an index, and "`ohMask`" is a bitmask of VFATs.  Again, here one is `OH` specific (`ohN`) and one is `VFAT` specific ("`ohMask`"), and they could equally well be served by a single `ohN` and `vfatN` (or more appropriately named) field

In general, I don't feel that this particular `struct` has been optimally designed as is, but as it is so tightly coupled to this PR, I can't realistically ask you to decouple the developments related to it.

I can't tell you right now what the "best" design would be (as it *strongly* depends on the types of scans that will be serviced by this `struct`), but what I can tell you is that if you have the bare minimum required parameters that *all* scans share, you can work towards which of them can have different meanings, depending on the type of the scan.  Additionally, I would strongly caution that this `struct` should **not** be a catchall for *any* parameter that *any* scan could need, which is what it feels like currently and leads to my aforementioned feeling about the design (apologies, I should have paid closer attention in #62), but from the original function signatures of:
```
confCalPulseLocal in src/calibration_routines.cpp
ttcGenConfLocal in src/calibration_routines.cpp
genScanLocal in src/calibration_routines.cpp
sbitRateScanLocal in src/calibration_routines.cpp
sbitRateScanParallelLocal in src/calibration_routines.cpp
checkSbitMappingWithCalPulseLocal in src/calibration_routines.cpp
checkSbitRateWithCalPulseLocal in src/calibration_routines.cpp
dacScanLocal in src/calibration_routines.cpp
configureScanModuleLocal in src/optohybrid.cpp
getUltraScanResultsLocal in src/optohybrid.cpp
```

I could probably give a more useful set of guidelines, so I'll take a look at each of those individually and reply with some thoughts, but since you've been working closely with them, you probably already have a good idea of where these optimizations can happen.

2018-12-27 11:31 UTC, AndrewLevin commented on include/utils.h
> +
@jsturdy, I replaced `vfatN`, `vfatMask`, `ohN`, and `ohMask` with just `vfat` and `oh`, and in `checkSbitMappingWithCalPulseLocal` and `checkSbitRateWithCalPulseLocal` the mask returned from `vfatSyncCheckLocal` is now used directly as the notmask, and the VFAT mask passed as an rpc parameter is now ignored.

2019-01-09 13:04 UTC, bdorney commented on include/utils.h
> +
> @jsturdy, I replaced `vfatN`, `vfatMask`, `ohN`, and `ohMask` with just `vfat` and `oh`, and in `checkSbitMappingWithCalPulseLocal` and `checkSbitRateWithCalPulseLocal` the mask returned from `vfatSyncCheckLocal` is now used directly as the notmask, and the VFAT mask passed as an rpc parameter is now ignored.

This should specifically *not* be done.  If you use the `vfatmask` that is obtained from `vfatSyncCheckLocal()` and ignore the provided `vfatmask` by the user then you're not doing what the user is requesting.  Moreover you're forcing it to "work" in a situation where an error *should* be thrown: i.e. the user wants VFAT15 to be checked but VFAT15 is not sync'd so it is ignored...then the user wonders why all data for VFAT15 is returned as zero and starts to wonder why.  This causes the user/expert to chase a problem that is different from the real problem.

I need some more time to digest this and will report back.  But for sure what you've described above should *not* be done.  Revert it.

2019-01-09 13:35 UTC, bdorney commented on include/calibration_routines.h
> +void ttcGenToggleLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
You're guilty of the catch-all problem @jsturdy and I are trying to ward against ([discussion](
https://github.com/cms-gem-daq-project/ctp7_modules/pull/63/files#r242623163).  This function has no need of the other parameters in `ParamScan` nor `ParamTTCGen` and three simple arguments are al that is needed.  Revert.

2019-01-09 13:35 UTC, bdorney commented on include/calibration_routines.h
> +void dacMonConfLocal(localArgs * la, ParamScan *scanParams);
[same comment](
https://github.com/cms-gem-daq-project/ctp7_modules/pull/63/files#r246382903).

2019-01-09 13:36 UTC, bdorney commented on include/calibration_routines.h
> +bool confCalPulseLocal(localArgs *la, ParamCalPulse *calParams, ParamScan *scanParams);
This really only needs `ParamCalPulse` as many parameters of `ParamScan` are not used here.  Here `ohN` could simply be `oh` if needed; and `mask` could remain as an argument.

2019-01-09 13:37 UTC, bdorney commented on include/calibration_routines.h
> +void ttcGenConfLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
Again you're trading a single argument `ohN` for a struct where you're only using *one* argument.  The use of `ParamTTCGen` is correct, however the use of `ParamScan` I think is overkill.  Recall don't be catch-all to our functions.

2019-01-09 13:39 UTC, bdorney commented on include/utils.h
> +
To follow-up on the point raised by @jsturdy we can indeed have further simplification.  Having one or more of these struct's serve as a "catch-all" for parameters defeats the purpose of implementing them.  The primary offender in this case appears to be (based on my own bad design) the `ParamScan` `struct`.  Indeed the terms:

 - `ohN` (`vfatN`), and
 - `ohMask` (`vfatmask`)

Can be compressed into two terms `oh` and `vfat` but then the function documentation needs to clearly state what is expected, e.g. a single integer, or an N-bit mask.  Furthermore we can remove from `ParamScan`:

 - `dacSelect` (only used by `dacScanLocal()` and friends), and
 - `useExtTrig` (only used by `genScanLocal() and friends).

These two parameters can just be regular function arguments.

For the case of:

- `checkSbitMappingWithCalPulseLocal()`, and
- `checkSbitRateWithCalPulseLocal()`

Their functionality should not be changed.  And this can be easily accommodated by instead of taking `mask` from `vfatSyncCheckLocal()` taking it as an additional input argument.  This preserves the intended use case.  

Finally, don't trade "up" on complexity, for example there's no reason to replace one single integer with a struct that carries that integer, see discussion [here](https://github.com/cms-gem-daq-project/ctp7_modules/pull/63/files#r246382903).

2019-01-09 13:40 UTC, bdorney requested changes
Don't try to use the struct's as "catch-all's" additionally don't trade up in complexity by passing a struct argument when a simple object would do.

2019-01-09 15:33 UTC, AndrewLevin commented on include/utils.h
> +
done

2019-01-09 15:34 UTC, AndrewLevin commented on include/calibration_routines.h
> +void ttcGenToggleLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
done

2019-01-09 15:34 UTC, AndrewLevin commented on include/calibration_routines.h
> +void dacMonConfLocal(localArgs * la, ParamScan *scanParams);
done

2019-01-09 15:34 UTC, AndrewLevin commented on include/calibration_routines.h
> +bool confCalPulseLocal(localArgs *la, ParamCalPulse *calParams, ParamScan *scanParams);
it is not clear if you saw the `ch` argument, which is also part of ParamScan, can you confirm?

2019-01-09 15:35 UTC, AndrewLevin commented on include/calibration_routines.h
> +void ttcGenConfLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
done

2019-01-17 09:38 UTC, bdorney commented
Not sure if the comments @jsturdy and I left have been addressed.  But this would need to be `rebase`'d off the current `HEAD` of `develop`.

2019-01-17 11:17 UTC, AndrewLevin commented
Yes, I have addressed the comments from you and @jsturdy. I just rebased off the HEAD of develop.

2019-01-17 11:48 UTC, bdorney commented
Can you mark this as WIP until you’ve sufficiently tested all the new changes; or provide a git diff between the current HEAD and the commit where this was tested last.

2019-01-17 12:07 UTC, AndrewLevin commented
@bdorney, here is the diff between the HEAD (7341bbe5ed6798a53c9a653726297873f7db7a7b) and the commit I last tested on the ctp7 (fb8b2a4a38e5fb25d60e15f0bf9e8997b54af633):
```
diff --git a/include/calibration_routines.h b/include/calibration_routines.h
index 437aced..9a368c5 100644
--- a/include/calibration_routines.h
+++ b/include/calibration_routines.h
@@ -101,7 +101,7 @@ void dacMonConfLocal(localArgs * la, ParamScan *scanParams);
  *  \param ohN Optical link
  *  \param enable See detailed mehod description
  */
-void ttcGenToggleLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
+void ttcGenToggleLocal(localArgs * la, ParamScan *scanParams, ParamTtcGen *ttcParams);
 
 /*! \fn void ttcGenToggle(const RPCMsg *request, RPCMsg *response)
  *  \brief Toggles the TTC Generator
@@ -146,7 +146,7 @@ void ttcGenToggle(const RPCMsg *request, RPCMsg *response);
  *  \param nPulses Number of calibration pulses to generate
  *  \param enable If true (false) ignore (take) ttc commands from backplane for this AMC (affects all links)
  */
-void ttcGenConfLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
+void ttcGenConfLocal(localArgs * la, ParamScan *scanParams, ParamTtcGen *ttcParams);
 
 /*! \fn void ttcGenConf(const RPCMsg *request, RPCMsg *response)
  *  \brief Configures TTC generator
@@ -279,7 +279,7 @@ void sbitRateScan(const RPCMsg *request, RPCMsg *response);
  *  \param L1Ainterval How often to repeat signals (only for enable = true)
  *  \param pulseDelay delay between CalPulse and L1A
  */
-void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, ParamCalPulse *calParams, ParamScan *scanParams, ParamTTCGen *ttcParams);
+void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, ParamCalPulse *calParams, ParamScan *scanParams, ParamTtcGen *ttcParams);
 
 /*! \fn void checkSbitMappingWithCalPulse(const RPCMsg *request, RPCMsg *response)
  *  \brief Checks the sbit mapping using the calibration pulse. See the local callable methods documentation for details
@@ -304,7 +304,7 @@ void checkSbitMappingWithCalPulse(const RPCMsg *request, RPCMsg *response);
  *  \param pulseRate rate of calpulses to be sent in Hz
  *  \param pulseDelay delay between CalPulse and L1A
  */
-void checkSbitRateWithCalPulseLocal(localArgs *la, uint32_t *outDataCTP7Rate, uint32_t *outDataFPGAClusterCntRate, uint32_t *outDataVFATSBits, ParamCalPulse *calParams, ParamScan *scanParams, ParamTTCGen *ttcParams);
+void checkSbitRateWithCalPulseLocal(localArgs *la, uint32_t *outDataCTP7Rate, uint32_t *outDataFPGAClusterCntRate, uint32_t *outDataVFATSBits, ParamCalPulse *calParams, ParamScan *scanParams, ParamTtcGen *ttcParams);
 
 /*! \fn void checkSbitRateWithCalPulse(const RPCMsg *request, RPCMsg *response)
  *  \brief Checks the sbit rate using the calibration pulse. See the local callable methods documentation for details
diff --git a/include/utils.h b/include/utils.h
index b12e1fc..9365b36 100755
--- a/include/utils.h
+++ b/include/utils.h
@@ -55,58 +55,63 @@ struct ParamCalPulse{
  */
 struct ParamScan{
     //Hardware selection
-    uint32_t oh;       //optical link number or optical link mask
-    uint32_t vfat;     //VFAT number or VFAT mask
-    uint32_t chan;      //channel number
+    uint32_t ohN;       //optical link number
+    uint32_t ohMask;    //OH mask
+    uint32_t vfatN;     //VFAT number
+    uint32_t vfatMask;  //VFAT mask
+    uint32_t chan;      //channel of interest
 
     //Params
     bool useUltra;   //Set to 1 in order to use the ultra scan
+    bool useExtTrig; //Set to 1 in order to use the backplane triggers
 
-    uint32_t max;    //Maximum dac value
-    uint32_t min;    //Minimum dac value
-    uint32_t step;   //step size for dac
+    uint32_t dacMax;    //Maximum dac value
+    uint32_t dacMin;    //Minimum dac value
+    uint32_t dacSelect; //DAC to use for Monitoring
+    uint32_t dacStep;   //step size for dac
     uint32_t nevts;     //Number of events
     uint32_t waitTime;  //unit of time; uints depend on function
 
     std::string scanReg;     //Register to scan against
 
     ParamScan(){
-        vfat = 0;
-        oh = 0;
+        vfatMask = 0x0;
+        ohMask = 0xfff;
 
         useUltra = true;
+        useExtTrig = false;
 
-        max=254;
-        min=0;
-        step=1;
+        dacMax=254;
+        dacMin=0;
+        dacStep=1;
         nevts=100;
     }
 }; //End ParamScan
 
-/*! \struct ParamTTCGen
+/*! \struct ParamTtcGen
  *  Contains arguments related to ttc generation
  */
-struct ParamTTCGen{
+struct ParamTtcGen{
     bool enable; //If true (false) ignore (take) ttc commands from backplane for this AMC (affects all links)
 
-    uint32_t interval; //How often to repeat signals
+    uint32_t L1Ainterval; //How often to repeat signals
     uint32_t mode; //T1 controller mode
     uint32_t nPulses; //Number of calibration pulses to generate
-    uint32_t delay; //Delay between CalPulse and L1A
+    uint32_t pulseDelay; //Delay between CalPulse and L1A
     uint32_t pulseRate; //rate of calpulses to be sent in Hz
     uint32_t type; //Type of T1 signal to send
 
-    ParamTTCGen(){
+    ParamTtcGen(){
         enable = false;
 
-        interval = 250;
-        delay = 40;
-        pulseRate = 40079000 / interval;
+        L1Ainterval = 250;
+        pulseDelay = 40;
+        pulseRate = 40079000 / L1Ainterval;
     }
 
     uint32_t calcRate(){
-        if(interval > 0){
-            pulseRate = 40079000 / interval;
+        if(L1Ainterval > 0){
+            pulseRate = 40079000 / L1Ainterval;
         }
         else{
             pulseRate = 0;
@@ -114,7 +119,7 @@ struct ParamTTCGen{
 
         return pulseRate;
     }
-}; //End ParamTTCGen
+}; //End ParamTtcGen
 
 /*! \struct localArgs
  *  Contains arguments required to execute the method locally
diff --git a/src/calibration_routines.cpp b/src/calibration_routines.cpp
index e6e9ec5..2739697 100644
--- a/src/calibration_routines.cpp
+++ b/src/calibration_routines.cpp
@@ -38,8 +38,8 @@ void applyChanMask(std::unordered_map<uint32_t, uint32_t> map_chanOrigMask, loca
 
 bool confCalPulseLocal(localArgs *la, ParamCalPulse *calParams, ParamScan *scanParams){
 
-    uint32_t ohN = scanParams->oh;
-    uint32_t mask = scanParams->vfat;
+    uint32_t ohN = scanParams->ohN;
+    uint32_t mask = scanParams->vfatMask;
     uint32_t ch = scanParams->chan;
     
     bool toggleOn = calParams->enable;
@@ -93,9 +93,12 @@ bool confCalPulseLocal(localArgs *la, ParamCalPulse *calParams, ParamScan *scanP
     return true;
 } //End confCalPulseLocal
 
-void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
+void dacMonConfLocal(localArgs * la, ParamScan *scanParams)
 {
 
+    uint32_t ohN = scanParams->ohN;
+    uint32_t ch = scanParams->chan;
+    
     //Check the firmware version
     char regBuf[200];
     switch (fw_version_check("dacMonConf", la)){
@@ -126,9 +129,13 @@ void dacMonConfLocal(localArgs * la, uint32_t ohN, uint32_t ch)
     return;
 }
 
-void ttcGenToggleLocal(localArgs * la, uint32_t ohN, bool enable)
+void ttcGenToggleLocal(localArgs * la, ParamScan *scanParams, ParamTtcGen *ttcParams)
 {
 
+    uint32_t ohN = scanParams->ohN;
+
+    bool enable = ttcParams->enable;
+    
     //Check firmware version
     switch(fw_version_check("ttcGenToggle", la)) {
         case 3: //v3 electronics behavior
@@ -180,23 +187,26 @@ void ttcGenToggle(const RPCMsg *request, RPCMsg *response)
     auto dbi = lmdb::dbi::open(rtxn, nullptr);
 
     struct localArgs la = {.rtxn = rtxn, .dbi = dbi, .response = response};
+    ParamTtcGen ttcParams;
+    ParamScan scanParams;
 
-    uint32_t ohN = request->get_word("ohN");
+    scanParams.ohN = request->get_word("ohN");
     
-    bool enable = request->get_word("enable");
+    ttcParams.enable = request->get_word("enable");
 
-    ttcGenToggleLocal(&la, ohN, enable);
+    ttcGenToggleLocal(&la, &scanParams, &ttcParams);
 
     return;
 } //End ttcGenToggle(...)
  [...]

2019-01-17 12:38 UTC, bdorney commented
> @bdorney, here is the diff between the HEAD ([7341bbe](https://github.com/cms-gem-daq-project/ctp7_modules/commit/7341bbe5ed6798a53c9a653726297873f7db7a7b)) and the commit I last tested on the ctp7 ([fb8b2a4](https://github.com/cms-gem-daq-project/ctp7_modules/commit/fb8b2a4a38e5fb25d60e15f0bf9e8997b54af633)):
> ...
> ...
> I have added [WIP]. Please let me know when I should retest it.

In the future something more like [this](https://github.com/cms-gem-daq-project/ctp7_modules/pull/63/files/7dfedd414a70ae0abb54da8f92d03479f7621f8c..7341bbe5ed6798a53c9a653726297873f7db7a7b) is more useful.  Keep in mind the web GUI can do this.

2019-01-17 12:40 UTC, bdorney commented on include/calibration_routines.h
> +void ttcGenToggleLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
It seems this was not addressed or the commit has not been pushed.

2019-01-17 12:40 UTC, bdorney commented on include/calibration_routines.h
> +void ttcGenConfLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
same

2019-01-17 12:42 UTC, bdorney commented on include/utils.h
> +    uint32_t oh;       //optical link number or optical link mask
optical link is a misnomer.  One OH has 3 bidirectional optical links and 2 unidirectional links.  Update the comment to reflect what this actually is:  OH index or OH Mask

2019-01-17 12:43 UTC, bdorney commented on include/utils.h
> +    uint32_t oh;       //optical link number or optical link mask
Additionally the documentation written in the `doxygen` comment for this struct is woefully inadequate.

2019-01-17 12:43 UTC, bdorney commented on include/utils.h
> +/*! \struct ParamTTCGen
Insufficient `doxygen` documentation.

2019-01-17 12:55 UTC, bdorney commented on src/calibration_routines.cpp
> +    uint32_t vfatmask = scanParams->vfat;
unnecessary white space.

2019-01-17 12:56 UTC, bdorney commented on src/calibration_routines.cpp
> +
unnecessary tab characters.  You should setup your editor to strip this automatically.

2019-01-17 12:58 UTC, bdorney commented on src/calibration_routines.cpp
> +        calParams_disabled.enable = false;
By calling the constructor in this manner you're supplying a pointer.  So now `calParams_disabled` points to `calParams`.  Are you sure it's making a [deep copy and not a shallow copy](https://www.learncpp.com/cpp-tutorial/915-shallow-vs-deep-copying/)?  I suspect not.

For example, in L961 when you set `calParams_disabled.enable` to `false` I suspect this also changes  `calParams.enable`.

2019-01-17 12:59 UTC, bdorney commented on src/calibration_routines.cpp
> +        calParams_disabled.enable = false;
Same comment at line 910.

2019-01-17 15:24 UTC, AndrewLevin commented on src/calibration_routines.cpp
> +    uint32_t vfatmask = scanParams->vfat;
fixed

2019-01-17 15:24 UTC, AndrewLevin commented on src/calibration_routines.cpp
> +
fixed

2019-01-17 15:25 UTC, AndrewLevin commented on include/calibration_routines.h
> +void ttcGenConfLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
Was only modified in the .cpp files, sorry.

2019-01-17 15:25 UTC, AndrewLevin commented on include/calibration_routines.h
> +void ttcGenToggleLocal(localArgs * la, ParamScan *scanParams, ParamTTCGen *ttcParams);
Was only modified in the .cpp file, sorry.

2019-01-17 15:26 UTC, AndrewLevin commented on include/utils.h
> +    uint32_t oh;       //optical link number or optical link mask
I changed the `//` comments to `/*!<`...`*/` comments.

2019-01-17 15:27 UTC, AndrewLevin commented on include/utils.h
> +/*! \struct ParamTTCGen
I changed the `//` comments to `/*!<`...`*/` comments.

2019-01-17 15:29 UTC, AndrewLevin commented
I am using a dereferenced pointer, and the structs do not have any member variables that are pointers, so I am doing a full copy of the data.
________________________________
From: Brian Dorney [notifications@github.com]
Sent: 17 January 2019 13:58
To: cms-gem-daq-project/ctp7_modules
Cc: Andrew Michael Levin; Author
Subject: Re: [cms-gem-daq-project/ctp7_modules] [WIP] add three new structs to pass a large number of arguments cleanly (#63)


@bdorney commented on this pull request.

________________________________

In src/calibration_routines.cpp<https://github.com/cms-gem-daq-project/ctp7_modules/pull/63#discussion_r248659753>:

> @@ -970,12 +957,11 @@ void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, ParamCa
             } //End Loop over clusters
         } //End Pulses for this channel

-        ParamCalPulse calParams_modified(*calParams);
-
-        calParams_modified.enable = false;
+        ParamCalPulse calParams_disabled(*calParams);
+        calParams_disabled.enable = false;


By calling the constructor in this manner you're supplying a pointer. So now calParams_disabled points to calParams. Are you sure it's making a deep copy and not a shallow copy<https://www.learncpp.com/cpp-tutorial/915-shallow-vs-deep-copying/>? I suspect not.

For example, in L961 when you set calParams_disabled.enable to false I suspect this also changes calParams.enable.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/cms-gem-daq-project/ctp7_modules/pull/63#pullrequestreview-193610056>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ADLMwFzJ2l4_3itb0LZnWYV0e77IPWxwks5vEHOLgaJpZM4X94ig>.

2019-01-17 15:29 UTC, AndrewLevin commented
Same comment.
________________________________
From: Brian Dorney [notifications@github.com]
Sent: 17 January 2019 13:59
To: cms-gem-daq-project/ctp7_modules
Cc: Andrew Michael Levin; Author
Subject: Re: [cms-gem-daq-project/ctp7_modules] [WIP] add three new structs to pass a large number of arguments cleanly (#63)


@bdorney commented on this pull request.

________________________________

In src/calibration_routines.cpp<https://github.com/cms-gem-daq-project/ctp7_modules/pull/63#discussion_r248659991>:

> @@ -970,12 +957,11 @@ void checkSbitMappingWithCalPulseLocal(localArgs *la, uint32_t *outData, ParamCa
             } //End Loop over clusters
         } //End Pulses for this channel

-        ParamCalPulse calParams_modified(*calParams);
-
-        calParams_modified.enable = false;
+        ParamCalPulse calParams_disabled(*calParams);
+        calParams_disabled.enable = false;


Same comment at line 910.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/cms-gem-daq-project/ctp7_modules/pull/63#discussion_r248659991>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ADLMwBElmT6mcPBXmhT1cVQ1Ag1bMrImks5vEHO7gaJpZM4X94ig>.

2019-01-17 15:55 UTC, bdorney commented on include/utils.h
> +/*! \struct ParamTTCGen
Can you build the documentation and show a screen shot of how this will look?  I'm not sure this is the intended way `doxygen` should be used.

2019-01-17 16:46 UTC, AndrewLevin commented on include/utils.h
> +/*! \struct ParamTTCGen
Yes:

![screenshot1](https://user-images.githubusercontent.com/3329216/51334089-6473f300-1a7f-11e9-86da-aa1abbc07935.png)
![screenshot2](https://user-images.githubusercontent.com/3329216/51334097-68077a00-1a7f-11e9-820d-7a23f286a29a.png)
![screenshot3](https://user-images.githubusercontent.com/3329216/51334102-6b026a80-1a7f-11e9-8140-fc768eaa0481.png)

2019-04-30 09:18 UTC, jsturdy commented
Will be revisited

2019-04-30 09:18 UTC, closed without merging