[WIP] New Feature: Phase Align Function
cms-gem-daq-project/ctp7_modules pull request #69
Opened 2018-11-13 19:20 UTC by bdorney

## Description

Addresses #65.  Migrated from `uhal` based methods in `cmsgemos`.

Provided local and nonlocal functions for `uhal` based equivalent functions in `cmsgemos`:

- `checkPllLock(...)`, and
- `ttcMMCMPhaseShift(...)`

The keys for the RPC request match input arguments.  No rpc response is returned by `ttcMMCMPhaseShift(...)` but for `checkPllLock(...)` the key `lockCnt` is inserted into the rpc response.

Note that `checkPllLock(...)` is provided for standalone functionality but `ttcMMCMPhaseShiftLocal(...)` calls `checkPllLockLocal(...)` preserving the functionality.  I am not sure if the uhal based `checkPllLock(...)` function is being used elsewhere in `cmsgemos` so I included a remote function just in case.

Also implemented the requested readback check in `ttcMMCMPhaseShiftLocal(...)`.  

Finally in the cases where exceptions where suggested in the comments I've set the `error` string in the RPC response.  The calling function from the DAQ machine should check for the presence of this key (e.g. `response->get_key_exists("error")`) and raise the appropriate exception or take the appropriate follow-up action.  Note that when the `"error"` key is set it definitely means the procedure *didn't* work or was not executed.

Not sure if additional keys should be inserted into the rpc response, e.g. in the case where `CMSGEMOS_WARN` logger was used one could thing that the `"warning"` key could be inserted into the rpc response but I'm not sure how `cmsgemos` is handling it...from the code snippet presented in #65 it seemed there was no exception being raised so if it's not necessary I'll just leave it as is.  

In all cases logging is now managed by logger in RPC land and will show up in the local/remote log file for the CTP7 (not the xdaq output which I suspect was previously being done). 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

#65 

## How Has This Been Tested?

Not tested yet, would need `eagle34` in 904 to have a "good linux image" or would need some time during interfill period to try to test on `eagle61` in P5. @jsturdy 

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-11-14 09:37 UTC, jsturdy commented on include/amc.h
> +uint32_t checkPllLockLocal(localArgs * la, int readAttempts);
Don't know if this was a direct copy (and in `cmsgemos` it might have been a direct copy from @evka85's original script), but I strongly prefer capitalization that correlates with actuality, e.g., `Pll` -> `PLL`, `Ttc` -> `TTC` (it's already done for `MMCM`, so this is more of a consistency request).
If these types of indicators occur in the middle of variables/function names, they should be all caps, if they are at the beginning, then they should be all lower case.

2018-11-14 09:38 UTC, jsturdy commented on src/amc.cpp
> +    std::unordered_map<std::string, uint32_t> map_ttcCtrlRegs;
If `unordered` means that things don't happen in a given order, this is not the intention, the sequence of `write`s  should be understood to be as given

2018-11-14 09:49 UTC, bdorney commented on src/amc.cpp
> +    std::unordered_map<std::string, uint32_t> map_ttcCtrlRegs;
Got it; I'll update...for sure this won't preserve the sequence illustrated.

2018-11-14 09:50 UTC, bdorney commented on include/amc.h
> +uint32_t checkPllLockLocal(localArgs * la, int readAttempts);
I was following camel case; but I'll try to update.

2018-11-16 10:34 UTC, bdorney commented on src/amc.cpp
> +    std::unordered_map<std::string, uint32_t> map_ttcCtrlRegs;
It's now changed to a `std::vector<std::pair<std::string, uint32_t> >` object.  This will preserve the ordering.

2018-11-19 15:29 UTC, jsturdy commented on src/amc.cpp
> +        writeReg(la,"GEM_AMC.TTC.CTRL.MMCM_RESET", 0x1);
This was a bug in the `cmsgemos` implementation, it should be a `MODULE_RESET`

2018-11-19 15:31 UTC, jsturdy commented on src/amc.cpp
> +    vec_ttcCtrlRegs.push_back(std::make_pair("PA_MANUAL_PLL_RESET"           , 0x1));
These resets are strobed, so they shouldn't be read back (the readback below could probably be optional altogether)

2018-11-19 15:33 UTC, jsturdy commented on src/amc.cpp
> +    for(auto ttcRegIter = vec_ttcCtrlRegs.begin(); ttcRegIter != vec_ttcCtrlRegs.end(); ++ttcRegIter){
Can simplify this block a bit with range based `for` loop syntax, e.g.,
```c++
for (auto &ttcRegIter: vec_ttcCtrlRegs) {
  writeReg(la, strTTCCtrlBaseNode + ttcRegIter.first, ttcRegIter.second);
  std::this_thread::sleep_for(std::chrono::microseconds(250));
  if ((ttcRegIter.first).rfind("RESET") != std::string::npos)
    continue;
...
}
```

2018-11-19 15:34 UTC, jsturdy commented on src/amc.cpp
> +        writeReg(la, strTTCCtrlBaseNode + "CNT_RESET", 0x1);
This should also be removed (was an artifact in the `cmsgemos` implementation from an older version, it has some unintended consequences in the logic)

2018-11-19 15:36 UTC, jsturdy commented on src/amc.cpp
> +        if (!reversingForLock && (gthShiftCnt == 39)) {
before this block (right after the current L348) should have the following (again, wasn't in the `cmsgemos` version, but was in the `python` version
```c++
uint32_t tmpGthShiftCnt  = readReg(la,"GEM_AMC.TTC.STATUS.CLK.PA_MANUAL_GTH_SHIFT_CNT");
uint32_t tmpMmcmShiftCnt = readReg(la,"GEM_AMC.TTC.STATUS.CLK.PA_MANUAL_SHIFT_CNT");

bool mmcmShiftRequired = false;
if (reversingForLock)
  mmcmShiftRequired = mmcmShiftTable[gthShiftCnt];
else
  mmcmShiftRequired = mmcmShiftTable[gthShiftCnt+1];
```

2018-11-19 15:37 UTC, jsturdy commented on src/amc.cpp
> +        if (mmcmShiftTable[gthShiftCnt+1]) {
With the change suggested at L350, this would become:
```c++
if (mmcmShiftRequired) {
```

2018-11-19 15:37 UTC, jsturdy commented on src/amc.cpp
> +            tmpMmcmShiftCnt = readReg(la,"TTC.STATUS.CLK.PA_MANUAL_SHIFT_CNT");
This (and a couple of other places) are missing the `GEM_AMC` base

2018-11-19 15:40 UTC, jsturdy commented
Currently, even with the changes mentioned thus far, the procedure is working for a while, and then getting stuck in a funky state (seems it finds 1 good lock, and then just gets "bad" lock status for 1000 straight shifts).  The `python` CTP7 local version is working, so I hope tracking down the logic difference is the reason (so far, a line-by-line comparison hasn't yielded any fruit...)

2018-11-20 08:27 UTC, jsturdy requested changes
I'll create a PR to your branch with all the things I modified, this latest one is the biggest, the rest were little things here and there (and some formatting/whitespace as I was tracking backwards to the source of the issue)
If you don't have time/don't feel like merging that PR in, let me know, and I'll supersede this PR instead

2018-11-20 08:27 UTC, jsturdy commented on src/amc.cpp
> +                    else {
Found it (another bug in the `cmsgemos` implementation, but not in the `python` version)!
This `else` block (L552 up to L592/3) belongs to `if (shiftOutOfLockFirst)`.
After closing it, the `if (!firstUnlockFound)` should be closed on L594 leading into the `else { // shift to first good PLL locked`

2018-12-11 17:23 UTC, bdorney commented
@jsturdy I merged your PR into my repo...is any new testing required or where the commits you pushed to my repo sufficient (and tested)?

2018-12-11 18:26 UTC, jsturdy submitted a review, later dismissed
I don't think there was anything else outstanding, but I didn't rigorously test it

2018-12-11 18:31 UTC, jsturdy commented
Though, if you could `rebase` off of `cms-gem-daq-project/develop`, I think that would be better than pressing the "Update branch" button

2019-01-09 14:06 UTC, bdorney commented
> Though, if you could `rebase` off of `cms-gem-daq-project/develop`, I think that would be better than pressing the "Update branch" button

Rebased.

2019-01-09 14:13 UTC, jsturdy approved these changes

2019-01-09 14:14 UTC, merged