[WIP] Implement RPC methods for configuring the GBTX's
cms-gem-daq-project/ctp7_modules pull request #73
Opened 2018-11-28 16:49 UTC by lpetre-ulb

## Description

This PR implements 4 new RPC methods which are related to the GBTX configuration :

* `writeGBTXConfiguration` updates the configuration of one selected GBTX.
* `writeGBTXPhase` updates the RX phases of one OH.
* `scanGBTXPhase` scans the phases on one OH.
* `scanGBTXPhaseMultiLink` scans the phases for multiples OH.

This is WIP, because it has not been tested yet. I'm going to write `xHAL` for that purpose since the interface in `cmsgemos` in not yet finalized.

Modifications, mostly keys and uniformity, and additions, mostly `writeGBTXConfigurationMultiLink` are expected.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

This PR solves issue #72.

## How Has This Been Tested?

It has no been tested yet, hence the WIP tag.

## Checklist:

- [ ] My code follows the code style of this project.
       Still need to carefully check that point.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-11-29 09:10 UTC, jsturdy reviewed
My first suggestion would be to put these `GBT` related functions into a separate module, e.g., `gbt.cpp/h`.
Sure, the GBTs physically live only on an OptoHybrid, but these modules don't do any sort of object oriented encapsulation so I don't think there's any real reason to group them with "OptoHybrid" functions, and "scoping" the functionality at the file level is probably easier to organize

2018-11-29 09:16 UTC, mexanick commented
Actually, the modules themselves provide a sort of encapsulation as in order to perform a call the the caller should load an appropriate module and the call its method. I agree with @jsturdy that functional module separation should take place here for the better code organization.

2018-11-29 16:02 UTC, lpetre-ulb commented
Ok, thank you for the suggestion, I've moved the methods to a new RPC module and new files. I've also added all the "multi-link" variants (see the updated first post).

2018-12-04 10:49 UTC, bdorney commented
What's the status of this PR? This is a mission critical action and I was hoping that we would have made more progress on it.

2018-12-04 10:53 UTC, lpetre-ulb commented
I've performed the tests yesterday afternoon. Writing the configuration, setting and scanning the phases work as expected. I'm committing last changes before review. I'm also porting the `gbt.py` tool in `reg_utils` for using the new RPC methods.

2018-12-04 13:20 UTC, lpetre-ulb commented
I've updated the first post to keep it up-to-date with the status of the PR. The only missing part is the new `gbt.py` tool of which its PR should be ready before the end of the day.

2018-12-04 21:45 UTC, lpetre-ulb commented
With the last [PR for the `gbt.py` tool](https://github.com/cms-gem-daq-project/reg_utils/pull/42), the PR's are made in all four repositories. The GBT tool functionalities are working from the DAQ machine with the version 3.7.0 of the CTP7 firmware.

2018-12-05 08:01 UTC, bdorney commented on include/gbt.h
> + *  \brief Scan the GBT phases of one optical link
What is `optical link` here?  e.g. does this only scan `GBT2` of `OHX`?  Or does it scan for *all* `GBT`'s on `OHX`?  Please update documentation to improve clarity.

2018-12-05 08:02 UTC, bdorney commented on include/gbt.h
> + *  \brief Write the configuration of one GBTX
Does this write the *full* configuration? e.g. all e-link phases on this `GBTx`? Or does it write just a single phase? From the functional arguments I assume the single phase case.  Please update the documentation to resolve this ambiguity.

2018-12-05 08:06 UTC, bdorney commented on src/gbt.cpp
> +}
These are specific to GE1/1 but we will have soon (Q1 2019) GE2/1 OH's that will have different hardware link assignments.  How do we intend to handle this?

One approach would be to use different namespaces for the different hardware.  Or a different naming convention.  I think this should be finalized *before* this PR is merged.

Beyond the scope of this PR I would like to see a header file that has all hard-coded hardware specific parameters in a single location; I suspect some refactoring would be needed to achieve this.

2018-12-05 08:11 UTC, bdorney commented on src/gbt.cpp
> +void writeGBTRegLocal(localArgs *la, const uint32_t ohN, const uint32_t gbtN, const uint16_t address, const uint8_t value){
In the header file this is the last function you declare but in this file it's the first definition you provide.  Perhaps for maintainability this should follow the order in which it's declared.

2018-12-05 08:12 UTC, bdorney commented on src/gbt.cpp
> +}
@jsturdy @mexanick

2018-12-05 08:15 UTC, bdorney commented on src/gbt.cpp
> +        writeGBTRegLocal(la, ohN, gbtN, static_cast<uint16_t>(address), config[address]);
You're assuming that `config` matches the expected size and order (e.g. index 0 is address 0) without:

1. actually checking that the size meets expectation, or
2. including a statement in the function documentation stating how the elements of `config` should be ordered and what it's size is expected to be (e.g. less than 366).

2018-12-05 08:22 UTC, bdorney commented on src/gbt.cpp
> +        return;
This information is *not* contained in the function documentation in the header file.  This should be addressed.

2018-12-05 08:28 UTC, bdorney commented on src/gbt.cpp
> +    }
This information is *not* contained in the function documentation in the header file. This should be addressed.

2018-12-05 08:30 UTC, bdorney commented on src/gbt.cpp
> +    }
If you look at the structure of all functions the rpc request and response have keys that match the local callable functions; and in that case their documentation is provided by the local callable function.  But here you're using the keys `ohMask` and `gbtMasks` that are neither documented in this function documentation nor used by the local callable function.

Consider the `\details` field in `doxygen` to provide this information.  A developer/expert user should be able to understand what is needed for successful execution from looking at the function API and right now this is not possible.

2018-12-05 08:31 UTC, bdorney commented on src/gbt.cpp
> +    }
Not included in function documentation.

2018-12-05 08:32 UTC, bdorney commented on src/gbt.cpp
> +        response->set_string("error", stdsprintf("The provided number of gbtMask's does not fullfill the expectations (%u).", ohUnmaskedNumber));
add the provided `gbtMasks` in these error statements.

2018-12-05 08:40 UTC, bdorney commented on src/gbt.cpp
> +    }
It seems like you're relying on someone to provide both an `ohMask` (12 bit number) and then a vector that contains 3-bit numbers, coupled with a check on the number of unmasked bits in the `ohMask`.  With this information you're looping over using this to define which GBT's are programmed.  But this is overly complicated in my view.  There's a better way.

All you need is the `gbtMasks` key.  Force the `i^th` element of `gbtMasks` to correspond to the `i^th` optohybrid.  Then a value of `0x0` implies the OH is masked; any nonzero value then implies the OH is not masked and provides the GBT's to be considered.

This requires minimal modification to the loop in Lines 134-147 while simplifying the rpc input.

2018-12-05 08:45 UTC, bdorney commented on src/gbt.cpp
> +void writeGBTPhase(const RPCMsg *request, RPCMsg *response){
How you have made this function is more like `writeAllGBTPhases(...)` and while this *is* potentially useful it was not what was requested in #72.  We are looking for a function that takes a single VFAT position and a phase value and sets that phase for the corresponding elink.

Keep this function, but rename it to  `writeAllGBTPhases(...)`, update the documentation to reflect that this is for *all* VFATs on an optohybrid and then make a new function `writeGBTPhase(...)` that is the remote callable method for writing just one VFAT worth of info (as requested in #72).

2018-12-05 08:45 UTC, bdorney commented on src/gbt.cpp
> +void writeGBTPhaseMultiLink(const RPCMsg *request, RPCMsg *response){
Rename to `writeAllGBTPhaseMultiLink` and update function documentation accordingly.

2018-12-05 08:48 UTC, bdorney commented on src/gbt.cpp
> +    const std::bitset<32> vfatMask(request->get_word("vfatMask"));
Multi link functions should *not* take a `vfatMask` from the rpc message but determine the *optohybrid specific* `vfatMask` at runtime, see for example:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/314cec21c7b565f898e461b487e1504907b78d6c/src/calibration_routines.cpp#L1282-L1284

2018-12-05 08:48 UTC, bdorney commented on src/gbt.cpp
> +    const std::bitset<32> vfatMask(request->get_word("vfatMask"));
(otherwise you *force* all OH's to use *the same* `vfatMask` which is not correct).

2018-12-05 08:49 UTC, bdorney commented on src/gbt.cpp
> +    }
Information not in function definition.

2018-12-05 08:50 UTC, bdorney commented on src/gbt.cpp
> +    }
Moreover you have not described the expected ordering.

2018-12-05 08:50 UTC, bdorney commented on src/gbt.cpp
> +    }
Change error message to:

`There must be 24 VFAT phases per OH`

e.g. `by OH` does not make sense.

2018-12-05 08:53 UTC, bdorney commented on src/gbt.cpp
> +    for(uint8_t phase = phaseMin; phase <= phaseMax; phase += phaseStep){
At minimum you should check that `phaseMax` makes sense; e.g. an 8-bit number goes to 255 while the max phase that can be set is 15 (16? I don't remember if indexing starts at 1 or 0).

2018-12-05 08:57 UTC, bdorney commented on src/gbt.cpp
> +void scanGBTPhase(const RPCMsg *request, RPCMsg *response){
I was expecting that this would *also* take a key that would determine the number of scans that would be performed as described [here](https://github.com/cms-gem-daq-project/ctp7_modules/issues/72#issuecomment-441643357).  The goal is to have a tool that makes `N` scans in a single RPC call (otherwise you lose a lot of time to the RPC message) and that this can be used to potentially determine the GBT phase settings.

We saw that between long & short boards the phase values differ and that even performing multiple scans on the *same* OH+GEB pair one after another give different results (edge effects).

2018-12-05 08:57 UTC, bdorney commented on src/gbt.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(300));
Why are these wait times *so* long?  Especially if this scan application is run multiple times this would take *forever*.

2018-12-05 08:59 UTC, bdorney commented on src/gbt.cpp
> +    std::vector<uint32_t> results;
In the function documentation you have not described the contents, nor the order, of this container.  Use the `\returns` field in `doxygen`.

2018-12-05 09:08 UTC, bdorney commented on src/gbt.cpp
> +    const uint8_t phaseStep = request->get_word("phaseStep");
Should *also* check here that `phaseMax` makes sense.  Keep the check in both places since the local callable function can be called elsewhere.

2018-12-05 09:09 UTC, bdorney commented on src/gbt.cpp
> +    response->set_word_array("results", results);
Needs to be explained in function documentation.

2018-12-05 09:09 UTC, bdorney commented on src/gbt.cpp
> +    const uint8_t phaseStep = request->get_word("phaseStep");
check that `phaseMax` makes sense.

2018-12-05 09:10 UTC, bdorney commented on src/gbt.cpp
> +void scanGBTPhaseMultiLink(const RPCMsg *request, RPCMsg *response){
Again was expecting this to take a parameter that would define the number of scans to be performed in *this* rpc call.

2018-12-05 09:10 UTC, bdorney commented on src/gbt.cpp
> +    response->set_word_array("results", results);
documentation needed

2018-12-05 09:11 UTC, bdorney requested changes
Lacking appropriate function documentation.  One key function is missing (e.g. `writeGBTPhase` what is provided is actually a `writeAllGBTPhases`). Additionally architectural changes needed in several functions to reduce complexity.

2018-12-05 15:59 UTC, lpetre-ulb commented on include/gbt.h
> + *  \brief Scan the GBT phases of one optical link
It scans _all_ the `GBT`'s on `ohN`. I used `optical link` because it was used somewhere else where it seems to means the OH index. I'll clarify that point.

2018-12-05 15:59 UTC, lpetre-ulb commented on include/gbt.h
> + *  \brief Write the configuration of one GBTX
It write just a single phase. I forgot to update the `\brief line`...

2018-12-05 16:11 UTC, lpetre-ulb commented on src/gbt.cpp
> +}
What could be done is to use `#ifdef` when the values are different between GE1/1 and GE2/1. It is then possible to chose at compile time if modules are for GE1/1 or GE2/1 (with the `-D` option of the compiler). In fact, this solution does not requires to centralize all the constants in a single location. It might however be cleaner, particularly if the constants are sorted within namespaces.

2018-12-05 16:14 UTC, lpetre-ulb commented on src/gbt.cpp
> +        writeGBTRegLocal(la, ohN, gbtN, static_cast<uint16_t>(address), config[address]);
Yes, right, it should be in documentation. The size is already checked in the non-local versions and using it with a incorrect size vector will only not work (but silently).

2018-12-05 16:16 UTC, lpetre-ulb commented on src/gbt.cpp
> +    }
Ok, I will add these informations.

2018-12-05 16:31 UTC, lpetre-ulb commented on src/gbt.cpp
> +    }
Yes, that's a better possibility, even if the keys will loose in uniformity. However, I would still need to keep track of the number of OH or GBT's which have been configured. Except, it the user writes padding in the `config` blob at the place of masked OH's/GBT's, but the data will be less compressed.

2018-12-05 16:32 UTC, lpetre-ulb commented on src/gbt.cpp
> +void writeGBTPhase(const RPCMsg *request, RPCMsg *response){
Ok, I'll add the function.

2018-12-05 16:34 UTC, lpetre-ulb commented on src/gbt.cpp
> +    const std::bitset<32> vfatMask(request->get_word("vfatMask"));
Indeed, forcing all the OH's to use the same `vfatMask` is maybe not the best solution. But using `getOHVFATMaskLocal` won't work. For example, after a phase scan, all the phases are left at value 15 which never works. I'll instead provide a array of `vfatMask` (like the gbtMasks).

2018-12-05 16:35 UTC, lpetre-ulb commented on src/gbt.cpp
> +    for(uint8_t phase = phaseMin; phase <= phaseMax; phase += phaseStep){
Of course, I missed that.

2018-12-05 16:37 UTC, lpetre-ulb commented on src/gbt.cpp
> +void scanGBTPhase(const RPCMsg *request, RPCMsg *response){
I misunderstood that request; I understood it as the `phaseMin`, `phaseMax` and `phaseStep` parameters. I'll add a `N` scans parameters. As the number of phases is very small, does it worth keeping the `phaseMin`, `phaseMax` and `phaseStep` parameters ?

2018-12-05 16:58 UTC, lpetre-ulb commented on src/gbt.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(300));
These are the wait times from the original `gbt.py` tool : https://github.com/cms-gem-daq-project/reg_utils/blob/7b9cf050c63dae5f3a9b5803389130cff2f039fa/python/reg_interface/arm/gbt_utils.py#L69-L72
I don't know if they can reliably reduced.

2018-12-05 18:16 UTC, bdorney commented on src/gbt.cpp
> +        writeGBTRegLocal(la, ohN, gbtN, static_cast<uint16_t>(address), config[address]);
Right, but the local version could be called by some other function so it too should work as a standalone object with proper handling.

2018-12-05 18:17 UTC, bdorney commented on src/gbt.cpp
> +    }
I’m not sure I understand this issue. Could you elaborate?

2018-12-05 18:21 UTC, bdorney commented on src/gbt.cpp
> +    const std::bitset<32> vfatMask(request->get_word("vfatMask"));
Yes you’re right. On further reflection why do we need the VFAT mask at all here?  Can it be dropped? The only thing that seems to actually matter is the attempt to read CFG_RUN and this could be handled by catching in the bus error that would be raised by a failed read.  Or did I miss something?

2018-12-05 18:22 UTC, bdorney commented on src/gbt.cpp
> +    const std::bitset<32> vfatMask(request->get_word("vfatMask"));
I would propose dropping VFAT mask, accepting scanning over dead/empty VFATs, and catching bus errors.  I don’t think this would be a significant issue.

2018-12-05 18:23 UTC, bdorney commented on src/gbt.cpp
> +void scanGBTPhase(const RPCMsg *request, RPCMsg *response){
You’ve already coded them so if it’s easier to keep them why not; just assign default values to them in the header file, e.g. min 0, max 15, step size 1.

2018-12-05 18:24 UTC, bdorney commented on src/gbt.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(300));
Ah I see. Mmhmm, can you contact @evka85 to see if they can be reliably reduced or what the rational is behind their length?

2018-12-05 19:33 UTC, lpetre-ulb commented on src/gbt.cpp
> +    const std::bitset<32> vfatMask(request->get_word("vfatMask"));
I don't understand exactly what you mean; this is the `writeAllGBTPhaseMultiLink` function. In the scan phase function, the scan indeed runs over the dead/empty VFAT's.

My idea behind an array of `vfatMask` is to be able to write some phases spread over all links in a single RPC call while leaving untouched the phases we do not want to change. Isn't it useful ?

2018-12-05 19:36 UTC, lpetre-ulb commented on src/gbt.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(300));
Ok, I'll send him an email. In the meantime, I'll leae the wait times untouched.

2018-12-05 19:51 UTC, lpetre-ulb commented on src/gbt.cpp
> +    }
My idea for the `writeGBTConfigMultiLink` function was to be able to use a different GBTX configuration file for each GBT to program, in a single RPC call. It allows to easily mix short and long chambers. These configurations must be concatenated in order to fit in key system, but there are multiple packing possibilities :
1. Concatenate all configurations. If the corresponding GBT is masked, you can add 366 zeroes, but the data is not compressed in any way.
2. Concatenate the 3 configurations only for the unmasked OH's. (This is what I did by imitation with the single link function call.)
3. Concatenate only the configurations of the unmasked GBT's. (This is what I plan to do.)

The the last two possibilities require to keep track of the position in the packed configuration data. But there are ways to keep the tracking clean.

2018-12-05 19:58 UTC, lpetre-ulb commented on src/gbt.cpp
> +        writeGBTRegLocal(la, ohN, gbtN, static_cast<uint16_t>(address), config[address]);
Ok, I'll do as you suggest.

But that raise a question for me. Where do you expect the checks to be done ? For example, in the `writeGBTRegLocal` function, I should check that `ohN` is inferior to the number of OH's supported by the CTP7. However, the performances will suffer from a systematic access to the `GEM_AMC.GEM_SYSTEM.CONFIG.NUM_OF_OH` register. This is the reason why I removed some checks before committing.

2018-12-06 09:36 UTC, bdorney commented on src/gbt.cpp
> +}
For this PR don't worry about it because it's outside the scope.  I just continue to raise this issue.

2018-12-06 09:40 UTC, bdorney commented on src/gbt.cpp
> +        writeGBTRegLocal(la, ohN, gbtN, static_cast<uint16_t>(address), config[address]);
Yes it makes sense to have a register check only when necessary since this causes a transaction on the bus which is O(us) but the CTP7's Zynq processor is 667 MHz [[1]](http://iopscience.iop.org/article/10.1088/1748-0221/11/02/C02011/pdf) so checks that do not require register access are "cheap."

Does this clarify things?

2018-12-06 09:51 UTC, bdorney commented on src/gbt.cpp
> +    }
Okay; I look forward to seeing the implementation.  But I think you got my primary concern: namely we don't need to provide two inputs that could potentially contradict.  This can be done just with `gbtMasks` and the `ohMasks` input is not needed.

2018-12-06 09:53 UTC, bdorney commented on src/gbt.cpp
> +    const std::bitset<32> vfatMask(request->get_word("vfatMask"));
Can you provide a use case in which you would *want* to do that?  This function in my mind is called at configure.  Then everything is configured.  In which case would you want to write only some phases?  I can't think of a case for that.

2018-12-06 13:28 UTC, lpetre-ulb commented on src/gbt.cpp
> +        writeGBTRegLocal(la, ohN, gbtN, static_cast<uint16_t>(address), config[address]);
Not really... Indeed, checks that require access to the registers are "expensive", that was the point of my question. Maybe it will be clearer if I rephrase it.

When is a check absolutely necessary ? It is possible to check every input parameter at each function call, but there is a (potentially massive) performance hit. So I decided to check only parameters coming from the RPC keys (even if I forgot `phase...`). The internal interface has then minimal checks and is supposed to be used correctly by the developer (of course, I should have written more documentation).

It is a matter of development choice. Can I conclude that you prefer that all input parameters are checked at each function call, except if the check requires register access ?

2018-12-06 13:40 UTC, lpetre-ulb commented on src/gbt.cpp
> +    const std::bitset<32> vfatMask(request->get_word("vfatMask"));
My use case was the correction of multiple VFAT phases in test stands while leaving the others at their default value. I could also argue that if the only use case is at configure, this `writeAllPhasesMultiLink` method is well performed with an on-the-fly modification of the configuration blob. But, OK, I'll remove the `vfatMasks`.

2018-12-10 13:21 UTC, bdorney commented
Status update on this PR?

2018-12-10 16:44 UTC, lpetre-ulb commented
Yes, I tested the modifications on the hardware this afternoon. The methods still work as expected. As I better understand what you expect, I preferred to start a new clean PR which addresses the points you raised : https://github.com/cms-gem-daq-project/ctp7_modules/pull/75.

2018-12-10 16:44 UTC, closed without merging