Use the new cached ADC registers introduced in release 3.7.1 of the ctp7 FW
cms-gem-daq-project/ctp7_modules pull request #74
Opened 2018-11-30 21:27 UTC by AndrewLevin

@evka85 released a new version of the ctp7 FW which uses caching for the registers `ADC0` and `ADC1` (https://github.com/evka85/GEM_AMC/releases/tag/v3.7.1). The corresponding changes to the ctp7 software are in the pull request.

## Description
The `dacScanLocal` function in `calibration_routines.cpp` has been changed to use the cache registers `ADC0_CACHED` and `ADC1_CACHED` if they exist, while also maintaining backward compatibility. The cache registers need to be updated before every read by reading or writing to the registers `ADC0_UPDATE` and `ADC1_UPDATE`, and then a 20 microsecond delay is needed to allow the cache registers to be updated.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context
This change was required for the ctp7 software to be consistent with the ctp7 firmware release v3.7.1, and to resolve an issue we found with reads of ADC0 and ADC1 timing out: http://cmsonline.cern.ch/cms-elog/1074808

## How Has This Been Tested?
The change has been tested by running 11 DAC scans on eagle64. Details, including the summary plot for one of the DAC scans, are in this elog:

http://cmsonline.cern.ch/cms-elog/1076528

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-12-03 09:10 UTC, bdorney commented on src/calibration_routines.cpp
> +                        std::this_thread::sleep_for(std::chrono::microseconds(20));
I would increase this to 25us (increases time to scan a single DAC by 0.12s) instead of using the 20us statement from Evaldas.  Without knowing if there is a spread in this update time you might just be sampling the same value and not a new value and then this doesn't accurately reflect the system.

2018-12-03 09:10 UTC, bdorney requested changes
Increase slightly the cached register update time wait.

2018-12-03 17:16 UTC, jsturdy submitted a review, later dismissed
I think this PR is probably fine, but reading a few surrounding bits and found a few bugs in the module, you could fix them in this PR, but it isn't strictly mandatory

2018-12-03 17:16 UTC, jsturdy commented on src/calibration_routines.cpp
>                      Temp = readRawAddress(adcAddr[vfatN], la->response);
This isn't related to this PR per se, but this is a rather poorly named variable.
On top of that, it's not even clear that it's necessary as it is declared outside the loop, assigned to the read value, and then immediately added to the value that matters.

2018-12-03 17:16 UTC, jsturdy commented on src/calibration_routines.cpp
>                      Temp = readRawAddress(adcAddr[vfatN], la->response);
Related, in [L1223](https://github.com/cms-gem-daq-project/ctp7_modules/blob/1fdc445546755ecdf388cf2f4b582227f707e9c3/src/calibration_routines.cpp#L1223) and [L1234](https://github.com/cms-gem-daq-project/ctp7_modules/blob/1fdc445546755ecdf388cf2f4b582227f707e9c3/src/calibration_routines.cpp#L1234), things would be better served by a `nReads` variable declared elsewhere

Additionally, it doesn't look like `adcVal` is ever reset after finishing the loop on a given `DAC` for a given `VFAT` at a given `DAC` set point; I can't imagine that this is the desired behaviour.
```pseudocode
init adcVal to 0
for minVal to maxVal
  for vfat
    for read
      adcVal += readVal
    adcVal /= 100 # this is now the initial value for the next VFAT
    storeRetVal(index,adcVal)
```

2018-12-03 17:37 UTC, evka85 commented on src/calibration_routines.cpp
> +                        std::this_thread::sleep_for(std::chrono::microseconds(20));
The 20us I quoted already has about 50% margin built in, so that should be safe. But of course I'm not opposed to increasing to 25us -- this won't increase the total run time by any noticeable amount, unless this is read at least a million times.

2018-12-04 09:54 UTC, bdorney commented on src/calibration_routines.cpp
> +                        std::this_thread::sleep_for(std::chrono::microseconds(20));
Ah okay; thanks for pointing this out! If the 25us is already implemented then I would leave it as is; unless additional changes are pending.

I expect this to be a “short term” solution anyway; with final solution coming from an upgrade of the Linux core by UWISC

2018-12-05 07:53 UTC, bdorney submitted a review, later dismissed

2018-12-05 10:06 UTC, jsturdy requested changes
https://github.com/cms-gem-daq-project/ctp7_modules/blob/6c8d018d5a87f96fc6ec63b51672a22491be656a/src/calibration_routines.cpp#L1224 
should move to:
https://github.com/cms-gem-daq-project/ctp7_modules/blob/6c8d018d5a87f96fc6ec63b51672a22491be656a/src/calibration_routines.cpp#L1206 (it doesn't need to be inside two loops, and could conceivably be passed in as a function parameter)

Then, https://github.com/cms-gem-daq-project/ctp7_modules/blob/6c8d018d5a87f96fc6ec63b51672a22491be656a/src/calibration_routines.cpp#L1235 should reference this value, instead of the old hardcoded value

2018-12-05 13:26 UTC, jsturdy approved these changes

2018-12-05 15:30 UTC, merged