Implement RPC methods for configuring the GBTX's v2
cms-gem-daq-project/ctp7_modules pull request #75
Opened 2018-12-10 16:42 UTC by lpetre-ulb

## Description

[This PR is the continuation of the [previous PR about GBTX's](https://github.com/cms-gem-daq-project/ctp7_modules/pull/73). I started the new PR in order to keep the git log clean, but also the GitHub comments readable.]

Addresses https://github.com/cms-gem-daq-project/ctp7_modules/issues/72.

This PR adds a new RPC module which implements 3 new methods related to the GBTX configuration :

* `writeGBTConfig` updates the configuration of one chosen GBTX.
* `writeGBTPhase` updates one VFAT RX phase of one OH.
* `scanGBTPhases` scans the phases on one OH.

It lacks the MultiLink versions, but all the important functionalities are working. If the code and the documentation meet the expectation, I will add these methods.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

This PR fixes issue https://github.com/cms-gem-daq-project/ctp7_modules/issues/72.

## How Has This Been Tested?

These tests were performed to see if the functionalities implemented in the `gbt.py` were still working with the RPC modules and so the new CTP7 releases :

* Writing the GBTX configurations. It has been tested for different OH and multiple GBTX's.
* Setting the GBTX RX phases for 1 VFAT at a time.
* Scanning the GBTX RX phases for one OH.

The environment was the following :
* CTP7 : eagle63
* CTP7 firmware : 3.7.0
* CTP7 build-id : CTP7-GENERIC-20180529T153916-0500-4935611
* `xHAL` commit (in progress).
* `cmsgemos` commit (in progress).
* The new `gbt.py` used for these tests comes from commit (in progress).

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2018-12-11 17:27 UTC, bdorney commented on Makefile
> +lib/gbt.so: src/gbt.cpp include/gbt.h include/gbt_constants.h include/moduleapi.h include/memhub.h include/utils.h lib/utils.so
I'm not sure I understand this make file line? Why is the target list here so long? In some cases these are already built.  The following line should be sufficient to ensure they are all linked correctly and they are found by the compiler.

2018-12-11 17:30 UTC, bdorney commented on include/gbt.h
> + *  - `string error` : If an error occurs, this keys exists and contains the error message.
Are you lines 17 through 26 will be included in the `doxygen` build? Why aren't you using the `\details` field?

2018-12-11 17:32 UTC, bdorney commented on include/gbt.h
> + *  \return Returns `false` in case of success; `true` in case of error. The precise error is logged and written to the `error` RPC key.
If this is declared as `void` how can it return something?  This documentation doesn't make sense.

2018-12-11 17:41 UTC, bdorney commented on include/gbt.h
> + *  - [23:0] : result of the N scans (and) for the i^th VFAT. A `1` indicates a good phase while a `0` indicates a bad phase.
From this documentation I do not understand how bits `[23:0]` should be interpreted.  Are you trying to say this should be interpreted as a 24 bit number where the i^th bit corresponds to the i^th VFAT?  

This was not really what was requested [here](https://github.com/cms-gem-daq-project/ctp7_modules/issues/72#issuecomment-441643357):

>For each GBT e-link (VFAT Pos) this should return in the RPC response a key which stores a word array where the array position corresponds to e-link phase and the array contents is the number of times that phase was "good."

I apologize if this was not clear but I was hoping more for something like the following:

- RPC Response contains for the X^th OH and Y^th GBT on this OH a key `OHX.GBTY`,
- This key returns a word array of 16 elements.
- For the i^th element in this array this stores the number of time `M` out of scans `N` where the i^th phase was "good".

This is a bit easier to understand and unpack than what you have done here (and also follows very nicely the examples in daq_monitor).

2018-12-11 17:44 UTC, bdorney commented on include/gbt.h
> + *  \return Returns `false` in case of success; `true` in case of error. The precise error is logged and written to the `error` RPC key.
Apply this comment to all function documentation below.

2018-12-11 17:51 UTC, bdorney commented on include/gbt.h
> + *  - `string error` : If an error occurs, this keys exists and contains the error message.
Apply this comment to all documentation below.

2018-12-11 17:52 UTC, bdorney commented on include/gbt.h
> +bool scanGBTPhasesLocal(localArgs *la, std::vector<uint32_t> &results, const uint32_t ohN, const uint32_t N = 1, const uint8_t phaseMin = gbt::phaseMin, const uint8_t phaseMax = gbt::phaseMax, const
Why are we passing a vector by reference here?  Why not just have this return a vector and store this in the RPC response?  The `set_word_array` function can take a `std::vector<uint32_t>` input.

2018-12-11 17:53 UTC, bdorney commented on include/gbt.h
> + *  \return Returns `false` in case of success; `true` in case of error. The precise error is logged and written to the `error` RPC key.
If this is defined as `void` how can it return something? This documentation doesn't make sense.

2018-12-11 17:57 UTC, bdorney commented on include/gbt.h
> +/*! \brief Scan the GBT phases of one OptoHybrid.
There is some confusion over this documentation; it's hard to follow which function this documentation block corresponds to.  You need to be using `doxygen` syntax and for each function the `\fn` field is expected at the *start* of the documentation block.  If you notice all other functions in this repo are organized like:

```C++
/*! \fn function declaration
     \brief text
     \param param1
     ...
     \returns text if returns something
     */
     function without any white space in between documentation and function
```

Inserting other `doxygen` fields where appropriate (e.g. `\details`).

2018-12-11 18:08 UTC, jsturdy commented on Makefile
> +lib/gbt.so: src/gbt.cpp include/gbt.h include/gbt_constants.h include/moduleapi.h include/memhub.h include/utils.h lib/utils.so
It looks like it is designed to determine what changes will trigger a rebuild of the `gbt.so` shared object; whether **all** of the targets are *necessary*, I can't say...

2018-12-11 18:08 UTC, jsturdy commented on include/gbt.h
> +/*! \brief Scan the GBT phases of one OptoHybrid.
FYI, and I'll probably go through an overhaul and cleanup at some point in the (not near) future, the `\fn` declaration is *only* required if the documentation block does **not** immediately precede the function it's documenting (it doesn't hurt, but it adds unnecessary lines)

2018-12-11 18:18 UTC, bdorney commented on include/gbt_constants.h
> +namespace gbt{
This namespace is great; but I was hoping this would be one generic hardware constant file as a central location. e.g. not `gbt_constants.h` but `hw_constants.h`.  Could you rename the file?

2018-12-11 18:19 UTC, bdorney commented on include/gbt_constants.h
> +    constexpr uint32_t gbtsPerOH = 3;
This is specific to GE1/1; but we need a way to distinguish from GE2/1 and ME0.  I suggest an outer namespace, e.g. `GE11`.  The our namespaces will be:

```C++
GE11
GE11::gbt
GE11::gbt::elinkMappings
GE21
GE21::gbt
GE21::gbt::elinkMappings
```

Then we can reference these in an appropriate way later on.

2018-12-11 18:20 UTC, bdorney commented on src/gbt.cpp
> +    return error_code; }
Seems like this would be a multi-use function and would be more suited to `utils.h`.

2018-12-11 18:24 UTC, bdorney commented on src/gbt.cpp
> +        }
What is the purpose of lines 102 to 105?  Won't this potentially skip some vfats?

2018-12-11 18:26 UTC, bdorney commented on src/gbt.cpp
> +    }
What's the purpose of lines 251 & 252?  Why return here?  Doesn't this risk skipping `regN = 1` or `regN = 2`?

2018-12-11 18:30 UTC, bdorney requested changes
Phase scan tool doesn't meet output expectations.

2018-12-11 20:11 UTC, jsturdy commented on include/gbt_constants.h
> +    constexpr uint32_t gbtsPerOH = 3;
Naively I would actually suggest the opposite; there will certainly be constants which are subproject specific, but there would also likely be some which are the same across all subprojects.
In that case, the `gbt` namespace could house all the `gbt` related constants/`typedef`s, and then within that namespace, a more scoped set could be defined for each subproject separately.

I wouldn't go too far down this road without sketching out a class/namespace diagram to try to understand the various interconnected pieces related to this design though

I would, however, suggest an all-caps-with-underscores naming convention for any constants/`enums` being defined

2018-12-11 20:28 UTC, jsturdy requested changes

2018-12-11 20:28 UTC, jsturdy commented on include/gbt_constants.h
> +namespace gbt{
Depending on how many of these eventually get put in, having them in separate files is a nice clean way to keep them organized.
I'd apply the same comment I made later about sketching out a design for this before developing too much further

2018-12-11 20:28 UTC, jsturdy commented on src/gbt.cpp
> +
It seems that lines 75-89 replicate lines 48-57 (ish), and would probably be better served by a generic GBT phase parameter checker function (or only do the check in the local function)

2018-12-11 20:28 UTC, jsturdy commented on src/gbt.cpp
> +
Same comment as in `scanGBTPhase` viz, checking the arguments

2018-12-11 20:28 UTC, jsturdy commented on src/gbt.cpp
> +
Again, parameter checking comment

2018-12-11 23:33 UTC, lpetre-ulb commented on Makefile
> +lib/gbt.so: src/gbt.cpp include/gbt.h include/gbt_constants.h include/moduleapi.h include/memhub.h include/utils.h lib/utils.so
Indeed, it is designed to trigger a rebuilt of `gbt.so` if one of the listed files change. Each of these files is directly required for a proper compilation of `gbt.so`. For example, if one brings modifications to `gbt_constants.h`, `make build` will trigger a compilation of `gbt.so`. It avoids to force a `make clean`.

2018-12-11 23:36 UTC, lpetre-ulb commented on include/gbt.h
> + *  - `string error` : If an error occurs, this keys exists and contains the error message.
Yes, it is included in the `doxygen` build. The `\details` fields does not seem to allow the \`...\` syntax and the `\returns` field is not consistent with a `void` function. It simply appears as details (but not `\details`) under the parameters list.

2018-12-11 23:39 UTC, lpetre-ulb commented on include/gbt.h
> +bool scanGBTPhasesLocal(localArgs *la, std::vector<uint32_t> &results, const uint32_t ohN, const uint32_t N = 1, const uint8_t phaseMin = gbt::phaseMin, const uint8_t phaseMax = gbt::phaseMax, const
I pass the vector by reference because I want to be able to return the status of the scan (success/failure) and so the return value is already used. Ideally, I would have used exceptions and catch them in the RPC method, but it is not used anywhere else.

2018-12-11 23:41 UTC, lpetre-ulb commented on include/gbt_constants.h
> +namespace gbt{
Yes, I will. See next comment for more details.

2018-12-11 23:57 UTC, lpetre-ulb commented on include/gbt_constants.h
> +    constexpr uint32_t gbtsPerOH = 3;
Here is a quick suggestion that I could immediately apply for this PR before walking through the code searching for a better solution and sketching some diagrams.

* Merge all the constants in a single file : `hw_constants.h`. If ever the file grows too much, it could be divided later.
* Separate the constants/`enum`'s/`typedef`'s in namespaces.
* If the values are different for each subproject, create a sub namespace, then inject the sub namespace values in the parent namespace at compile time.

The file would look like :

``` c++
// Could also be set as compiler parameter
#define GEM_VARIANT GE11

namespace gbt{
    constexpr uint16_t configSize = 366;
    ...

    namespace GE11{
        constexpr uint32_t gbtsPerOH = 3;
        ....
    }

    using namespace GEM_VARIANT;
}
```

Also, yes, I can capitalize the constants/`enum`'s, but wouldn't that be a too heavy name convention ?

2018-12-11 23:59 UTC, lpetre-ulb commented on src/gbt.cpp
> +    return error_code; }
Indeed, I just wanted to be as little intrusive as possible.

2018-12-11 23:59 UTC, lpetre-ulb commented on src/gbt.cpp
> +
Indeed, that would be much better.

2018-12-12 00:02 UTC, lpetre-ulb commented on src/gbt.cpp
> +        }
Indeed some VFAT's could be skipped. But this happens only when the phase cannot be set properly. Therefore, the scan would be irrelevant anyway. So, I think, it is best to stop it as soon as possible and return the error.

2018-12-12 00:04 UTC, lpetre-ulb commented on src/gbt.cpp
> +    }
Yes, it will. But if the write of one register fails, the GBTX configuration is corrupted anyway. So, just stop there and report the error as soon as possible.

2018-12-12 00:13 UTC, lpetre-ulb commented on src/gbt.cpp
> +
Indeed, checking the arguments in a separate function could be more elegant. However, to keep some generality the gain in LOC would be minimal compared to the phase case. Also, that does not respect the coding style of the other modules. I can change that if really required (maybe for initiating a new coding style).

The checks of the arguments in both the "RPC" method and the local function follows some comments from [previous PR](https://github.com/cms-gem-daq-project/ctp7_modules/pull/73). See for example [this one](https://github.com/cms-gem-daq-project/ctp7_modules/pull/73#discussion_r238980114) where @bdorney told me that the local functions could be used from else where and so the arguments need to be checked.

2018-12-12 00:21 UTC, lpetre-ulb commented on include/gbt.h
> + *  - [23:0] : result of the N scans (and) for the i^th VFAT. A `1` indicates a good phase while a `0` indicates a bad phase.
This is indeed what I'm trying to say. The `(and)` is a "typo". It should say (with some improvements) :
> [23:0] : results of the scan. This 24 bits vector is the _and_ of the N scans which were performed. The i^th bith correspond to the i^th VFAT with the following convention : a `1` indicates a good phase while a `0` indicates a bad phase. 

Ok, I did not understand it like that. I'm sorry. But would it be easier to unpack ? In my testing script, the unpacking is extremely simple; more than playing with strings concatenation I think. Each word of the array is self contained.

2018-12-12 00:25 UTC, lpetre-ulb commented on include/gbt.h
> +/*! \brief Scan the GBT phases of one OptoHybrid.
Yes, this is why I did not write the `\fn` declaration. Also, it is really easier to maintain because we can change the function name, parameter ordering and types without manually adapting the documentation; `doxygen` in smart enough to find them.

@jsturdy, I'm not sure what your cleanup will be. Will you remove or add the `\fn` everywhere it is possible ? I think it is best if I follow what you will do.

2018-12-12 08:22 UTC, jsturdy commented on include/gbt.h
> +/*! \brief Scan the GBT phases of one OptoHybrid.
> @jsturdy, I'm not sure what your cleanup will be. Will you remove or add the `\fn` everywhere it is possible?

I would remove `\fn` everywhere that it is not used as `doxygen` intends

2018-12-12 08:31 UTC, jsturdy commented on include/gbt_constants.h
> +    constexpr uint32_t gbtsPerOH = 3;
I don't think you want to do this injection at compile time, since the same system will eventually be used to control, e.g., `GE11` *and* `GE21` at the same time

> Also, yes, I can capitalize the constants/enum's, but wouldn't that be a too heavy name convention ?

I'm not sure I understand the concern here, capitalized `consts` (`_` delimited, if that wasn't clear) is a fairly standard practice (probably coming from `C` land where this was done with `define`s), and we have adopted it in other GEM code, notably in `cmsgemos`.  The primary goal is to make clear that when used, the intent the expression is a constant

2018-12-12 08:33 UTC, jsturdy commented on src/gbt.cpp
> +        }
Are you writing an `error`/`warning` message to the logger when this happens?
I didn't trace things back, but here all I see is the `return true`

2018-12-12 08:38 UTC, jsturdy commented on src/gbt.cpp
> +
> Also, that does not respect the coding style of the other modules.

I'm not sure I know what the "coding style" is here (I'm not sure it's rigorously defined), but I'll chat with @mexanick and @bdorney and see if we can't all agree on some style standards that would be clear to all

> See for example this one where @bdorney told me that the local functions could be used from else where and so the arguments need to be checked.

I see, this was why I suggested that the check could be done *only* in the local function, as the RPC callback is just a passthrough, and the "local" function will be called in both cases

2018-12-12 10:52 UTC, bdorney commented on include/gbt.h
> + *  - `string error` : If an error occurs, this keys exists and contains the error message.
> Yes, it is included in the doxygen build. 

Can you provide a url for this build in the `ctp7_modules` channel on mattermost and give the mattermost link here?  You can host it on the ULB machine if need be.

2018-12-12 10:54 UTC, bdorney commented on include/gbt.h
> + *  - [23:0] : result of the N scans (and) for the i^th VFAT. A `1` indicates a good phase while a `0` indicates a bad phase.
> Ok, I did not understand it like that. I'm sorry. But would it be easier to unpack ? In my testing script, the unpacking is extremely simple; more than playing with strings concatenation I think. Each word of the array is self contained.

If I understand your function output the analysis tool has to loop over a vector with N element and then track the status of each (elink, ohN, GBT) triplet from a complex container.  

In my design the output looks at for each (ohN, GBT) pair a vector of 16 elements and immediately reads off the number of successes without further complication.  This second method is easier to process and understand (even by eye).

Please implement the requested change.

2018-12-12 10:58 UTC, bdorney commented on src/gbt.cpp
> +    return error_code; }
Right but if someone wants to use this definition they now have to include `gbt.cpp` which would make the dependencies complicated.  The above comment should have been understood as:

> move this definition to `utils.h`.

2018-12-12 11:05 UTC, bdorney commented on src/gbt.cpp
> +        }
> Are you writing an `error`/`warning` message to the logger when this happens?
> I didn't trace things back, but here all I see is the `return true`

After some digging `scanGBTPhasesLocal(...)` calls `writeGBTPhaseLocal(...)` which will call `writeGBTRegLocal(...)` which will call `writeReg(...)`.  At each stage if an input parameter is not understood it looks like the `error` key is assigned to the RPC response and written to the CTP7 Log.  Then finally if an actual register transaction fails from `writeReg(...)` in `writeGBTRegLocal(...)` the corresponding bus error will be written to the log/rpc repsonse `error`.

I am not sure I like this return true/false methodology you've adopted here as it makes things a bit harder to track; but off the top of my head I cannot think of a better approach except for exception handling.  I'll let it slide for now baring further comment from @jsturdy or @mexanick.

2018-12-12 11:18 UTC, lpetre-ulb commented on include/gbt.h
> +/*! \brief Scan the GBT phases of one OptoHybrid.
Thank you for the clarification. I'll keep the documentation as it is then.

2018-12-12 11:19 UTC, lpetre-ulb commented on src/gbt.cpp
> +    return error_code; }
Yes, of course, this was implicit in my previous answer.

2018-12-12 11:20 UTC, bdorney commented on src/gbt.cpp
> +    }
I see; after some discussion with @jsturdy we will open a separate issue to see if there's a way to have a cleaner implementation at a lower level to catch failed writes (and not just here).

So the current method here is good.  Thanks for the clarification.

2018-12-12 11:22 UTC, bdorney commented on src/gbt.cpp
> +
> I'm not sure I know what the "coding style" is here (I'm not sure it's rigorously defined), but I'll chat with @mexanick and @bdorney and see if we can't all agree on some style standards that would be clear to all

Yes we should have a defined standard.  I agree it is not present as overtime we improved things as we (I) gained experience.  In most cases @jsturdy usually has a better architecture design idea than I do.

2018-12-12 11:24 UTC, lpetre-ulb commented on src/gbt.cpp
> +        }
Yes, this is how it works.

I don't like much this methodology either (very C-style while the project is mostly C++), but exceptions are not used anywhere else. If I could use exceptions, the result would be nicer.

2018-12-12 11:24 UTC, bdorney commented on Makefile
> +lib/gbt.so: src/gbt.cpp include/gbt.h include/gbt_constants.h include/moduleapi.h include/memhub.h include/utils.h lib/utils.so
Got it.  Thanks for clarification.

2018-12-12 11:31 UTC, lpetre-ulb commented on src/gbt.cpp
> +
> I see, this was why I suggested that the check could be done _only_ in the local function, as the RPC callback is just a passthrough, and the "local" function will be called in both cases

Yes, I'll do that where possible.

There is also the check for `ohMax` which is special because it requires a "slow" register access. Maybe, should I implement some easy cache system ? If ever the value of the register changes, it means that the CTP7 firmware has changed and so the RPC process is reloaded anyway.

2018-12-12 11:43 UTC, lpetre-ulb commented on include/gbt_constants.h
> +    constexpr uint32_t gbtsPerOH = 3;
> > If the values are different for each subproject, create a sub namespace, then inject the sub namespace values in the parent namespace at compile time.
> 
> I don't think you want to do this injection at compile time, since the same system will eventually be used to control, e.g., `GE11` _and_ `GE21` at the same time

So, how should I refer to the constants in the code ? If it explicitly refers to the `GE11` or `GE21` namespace, the purpose of clearly separating the constants is partly defeated. Or maybe that some mechanism will load the "constants" at run-time ?

Also, will `GE11` and `GE21` be mixed within the same CTP7/ATCA board ? If so, the RPC modules will be more complex in order to determine the variant on-the-fly for each link.

> > Also, yes, I can capitalize the constants/enum's, but wouldn't that be a too heavy name convention ?
> 
> I'm not sure I understand the concern here, capitalized `consts` (`_` delimited, if that wasn't clear) is a fairly standard practice (probably coming from `C` land where this was done with `define`s), and we have adopted it in other GEM code, notably in `cmsgemos`. The primary goal is to make clear that when used, the intent the expression is a constant

Yes, I'll modify the constant names (with `_` delimiters).

This is however a controversial subject. Personally, I prefer (in C/C++) to reserve the capitalized names to preprocessor define's/macro's where the C/C++ syntax may not be respected. The name then shouts for a good reason. As for the constants, there are in a namespace, so the `::` already raises an alert and I think about what I'm going to do.

2018-12-12 11:49 UTC, lpetre-ulb commented on include/gbt.h
> + *  - [23:0] : result of the N scans (and) for the i^th VFAT. A `1` indicates a good phase while a `0` indicates a bad phase.
> If I understand your function output the analysis tool has to loop over a vector with N element and then track the status of each (elink, ohN, GBT) triplet from a complex container. And in this case I imagine N is large (i.e. N >> 100).

Hmm, no, this is not what in my implementation returns. The results are already merged in the RPC module, so you only receive the status of the phase (GOOD/BAD) after the N scans; if it fails once, the phase is considered BAD. So whatever N is, you receive 16 words (1 per phase) each of them being self-contained; there is no need to keep track of anything, just save the result.

> In my design the output looks atm for each (ohN, GBT) pair, a vector of 16 elements and immediately reads off the number of successes at each phase without further complication. This second method is easier to process and understand (even by eye).
> 
> Please implement the requested change.

I'll do.

2018-12-12 11:56 UTC, lpetre-ulb commented on include/gbt.h
> + *  - `string error` : If an error occurs, this keys exists and contains the error message.
Here it is : https://mattermost.web.cern.ch/cms-gem-daq/pl/jqm787toyfbpfjghsyded13bbw

2018-12-12 16:32 UTC, jsturdy commented on include/gbt_constants.h
> +    constexpr uint32_t gbtsPerOH = 3;
> So, how should I refer to the constants in the code ? If it explicitly refers to the `GE11` or `GE21` `namespace`, the purpose of clearly separating the constants is partly defeated. Or maybe that some mechanism will load the "constants" at run-time?

Actually I glossed over this earlier, but you're right: either there needs to be a run time determination of this (easy to separate `GE11`/`GE21`/`ME0` within a given back-end card, less so if the code is running on a development platform that doesn't have access to expensive back-end cards and the methods are residing on a PC), **OR** the modules are compiled for their target system (and your current implementation is mostly sufficient, passing in the `GEM_VARIANT` as a compile-time option, rather than as a `define` in some header)

As I mentioned earlier, I don't think that fleshing out this complete design should be a part of this PR, as it will require quite some careful thought about the implementation, so I would say just keep what you have now, and add the compiler flag `-DGEM_VARIANT=\"${GEM_VARIANT}\"` that should be `GE11` by default now (well `ge11` if I'm going to nitpick, as I would make all namespaces lower case)

> This is however a controversial subject

**All** style based subjects are :-D

2018-12-12 16:34 UTC, jsturdy commented on src/gbt.cpp
> +
Reading that one register is an inexpensive transaction at this level, I wouldn't change things just to avoid that.

2018-12-12 16:48 UTC, bdorney commented on include/gbt_constants.h
> +    constexpr uint32_t gbtsPerOH = 3;
> > So, how should I refer to the constants in the code ? If it explicitly refers to the `GE11` or `GE21` `namespace`, the purpose of clearly separating the constants is partly defeated. Or maybe that some mechanism will load the "constants" at run-time?
> 
> Actually I glossed over this earlier, but you're right: either there needs to be a run time determination of this (easy to separate `GE11`/`GE21`/`ME0` within a given back-end card, less so if the code is running on a development platform that doesn't have access to expensive back-end cards and the methods are residing on a PC), **OR** the modules are compiled for their target system (and your current implementation is mostly sufficient, passing in the `GEM_VARIANT` as a compile-time option, rather than as a `define` in some header)

If we want a runtime variant we could again rely on the uTCA AMC/aTCA blade firmware version.  From @evka85 we know GE11 and GE21 will have different CTP7 FW versions so this naturally could be encoded into the software like it was presently done for v2b vs. v3 functionality.  This could then be used to determine the functionality at runtime.  Just my two cents.

2018-12-12 16:49 UTC, bdorney commented on src/gbt.cpp
> +        }
Is there a reason why we can't implement exception handling in `ctp7_modules` repo? @mexanick

2018-12-12 22:56 UTC, lpetre-ulb commented on src/gbt.cpp
> +
It is inexpensive, but not negligible. For example, if the `ohMax` check is done in `writeGBTRegLocal`, writing a GBT configuration would require 366 accesses to `GEM_AMC.GEM_SYSTEM.CONFIG.NUM_OF_OH`, 365 of them being unnecessary. Considering a register access taking ~10µs, configuring one GBT is ~3.6ms longer for nothing. If one wants to write all the GBT's of one CTP7, that makes more than useless 100ms.

The cache mechanism could be very simple and integrated within the new check functions :
```c++
inline bool checkOhN(localArgs *la, const uint32_t ohN){
    static uint32_t ohMax = -1;
    if (ohMax == -1)
        ohMax = readReg(&la, "GEM_AMC.GEM_SYSTEM.CONFIG.NUM_OF_OH");
        // Maybe a check on readReg ?

    if (ohN >= ohMax)
        EMIT_RPC_ERROR(la->response, stdsprintf("The ohN parameter supplied (%u) exceeds the number of OH's supported by the CTP7 (%u).", ohN, ohMax), true) 
}
```
It is a way of "defining a constant at run-time with information from the CTP7/back-end board".

2018-12-14 00:15 UTC, jsturdy commented on src/gbt.cpp
> +        }
It *can* be done, but it has to be done *right*, and this involves deciding what `throw` semantics each class of function should employ, i.e, you probably *don't* want the RPC callbacks to `throw`, unless the `rpcsvc` can `catch` and handle those exceptions.
It would make sense that "local" functions can `throw`, and the RPC callback (or external code) would be responsible for handling and returning data in a good state
This is *definitely* not within the scope of this PR, so should be moved to an issue and refined there

2018-12-14 00:20 UTC, jsturdy commented on src/gbt.cpp
> +
OK, in that case your proposed solution makes sense (though I'd think long and hard about whether `writeGBTRegLocal` should be a public interface function in this case, or should only be used internally by other functions that would do the sanity checks themselves...)

One could also consider what other FW version specific constants could benefit being exposed this way

2018-12-16 21:40 UTC, lpetre-ulb commented
I brought the requested changes.

Regarding the [discussion about `ohN` parameter check](https://github.com/cms-gem-daq-project/ctp7_modules/pull/75#discussion_r241608923), I haven't added the method yet and kept the warning in `writeRegLocal`. A more careful reflection should be made for parameter checking and the utility of a cache. Also, the gain in code is rather small (except for phases) if exceptions are not used; indeed, the return value of each check function call must must checked itself in order to terminate the function if needed.

More reflection should be made on constants, parameter checking and exceptions. These can (should ?) however be addressed in other issues and PR's.

2018-12-17 10:01 UTC, jsturdy requested changes
Couple of tweaks/clarifications

2018-12-17 10:01 UTC, jsturdy commented on src/gbt.cpp
> +        return true;
I think you either want a check and action on `false` (definitely not `return true` here) (also L57), don/t you?

2018-12-17 10:01 UTC, jsturdy commented on src/gbt.cpp
> +        EMIT_RPC_ERROR(response, stdsprintf("The provided configuration has not the correct size. It is %u registers long while this methods expects %hu 8-bits registers.", configSize, gbt::CONFIG_SI
There's a trailing comma, and potentially missing final parameter, though I may have glossed over the usage of `EMIT_RPC_ERROR`...
If you're returning `void`, I'd make it explicit.

2018-12-17 10:01 UTC, jsturdy commented on Makefile
> +CFLAGS += -DGEM_VARIANT="ge11"
This is fine for now, but it should pick "ge11" (or other) up from the `make` environment, not from the `Makefile` (unless there will be a separate `Makefile` for all variants

2018-12-17 17:47 UTC, lpetre-ulb commented on src/gbt.cpp
> +        return true;
No, I definitely want to return `true`. The contract for the local functions is simple : return `true` in case of error and write enough debugging informations (i.e. `LOGGER` and RPC key `error`). The convention may not be very well chosen in this case (it comes from the historical C world with the `exit()` function), but I think it is best to use a uniform convention.

2018-12-17 17:50 UTC, lpetre-ulb commented on src/gbt.cpp
> +        EMIT_RPC_ERROR(response, stdsprintf("The provided configuration has not the correct size. It is %u registers long while this methods expects %hu 8-bits registers.", configSize, gbt::CONFIG_SI
Indeed, it returns `void`; the last parameter of the `EMIT_RPC_ERROR` macro can be empty (this is why I like to use capitals for macros). In the same idea, the trailing semi-colon is not necessary but does not hurt. I could pass `(void)""` as the last parameter to make it explicit.

2018-12-17 17:53 UTC, lpetre-ulb commented on Makefile
> +CFLAGS += -DGEM_VARIANT="ge11"
Yes that would be better, but as the variable does not exist yet I chose this simpler solution. I'll change it to do q check on `GEM_VARIANT` existence and default back to `ge11`.

2019-01-10 08:55 UTC, jsturdy commented
@lpetre-ulb, @bdorney, coming back to this, was there anything outstanding in this PR that we *didn't* decide to postpone to a later PR?
In either case, @lpetre-ulb, can you `rebase` this onto the current `develop` branch?

2019-01-10 08:56 UTC, jsturdy submitted a review, later dismissed

2019-01-10 11:05 UTC, mexanick commented on src/gbt.cpp
> +        EMIT_RPC_ERROR(response, stdsprintf("The provided configuration has not the correct size. It is %u registers long while this methods expects %hu 8-bits registers.", configSize, gbt::CONFIG_SI
I stand with @jsturdy. For the sake of readability, I would add a void last parameter, or, even better, define the error code table and return an actual error code

2019-01-10 11:05 UTC, mexanick submitted a review, later dismissed

2019-01-10 17:22 UTC, lpetre-ulb commented on src/gbt.cpp
> +        EMIT_RPC_ERROR(response, stdsprintf("The provided configuration has not the correct size. It is %u registers long while this methods expects %hu 8-bits registers.", configSize, gbt::CONFIG_SI
Sure, I forgot with the Christmas break... Done ! Yes, an actual error code would be better (or maybe exceptions). However, in this precise case, this is the RPC function which must return `void`.

2019-01-10 17:24 UTC, lpetre-ulb commented
> @lpetre-ulb, @bdorney, coming back to this, was there anything outstanding in this PR that we _didn't_ decide to postpone to a later PR?

I don't think there is. Registers cache (could also be useful for VFATs chipID with error correcting code), exceptions and multi-link versions are postponed to later PR's.

> In either case, @lpetre-ulb, can you `rebase` this onto the current `develop` branch?

Done !

2019-01-11 10:38 UTC, jsturdy submitted a review, later dismissed

2019-01-16 12:51 UTC, jsturdy commented
@bdorney any outstanding issues from you? I see this is blocked by "changes requested"

2019-01-16 13:44 UTC, bdorney commented
Let me do a cursory review this afternoon/evening.  I see most of my comments are marked with `outdated` so I assume they have been addressed...but still, I'll have a look this afternoon.

2019-01-16 14:46 UTC, bdorney commented on Makefile
> +
One comment is that "lower level" so's should be built before higher level so's.  But in this case since presently `gbt.so` is not used by any of the others it doesn't matter.  Just keep in mind for future (e.g. if you built `amc.so` last you'd have a bad day).

2019-01-16 14:50 UTC, bdorney commented on include/gbt.h
> + *  \return Returns `false` in case of success; `true` in case of error. The precise error is logged and written to the `error` RPC key.
General comment is that I think in addition to setting the `error` key it might be good to one day develop exception handling and such for these RPC functions.  That is beyond the scope of this PR though.

2019-01-16 14:58 UTC, jsturdy commented on Makefile
> +
Yeah, this is improved significantly in #77, which will be rebased and merged after these changes are merged.

2019-01-16 14:59 UTC, bdorney submitted a review, later dismissed

2019-01-16 15:07 UTC, lpetre-ulb commented
Before merging, let me push one more commit that I am currently testing about the delays for the phase scan (very minimal modification). It should only take a few tens of minutes, but it would speed up the phase scan by a lot.

2019-01-16 15:30 UTC, bdorney approved these changes
last commit introduced a trivial change. still good.

2019-01-16 15:35 UTC, lpetre-ulb commented
As @bdorney suggested in the previous PR (https://github.com/cms-gem-daq-project/ctp7_modules/pull/73#discussion_r238976795), the wait times in the phase scan were *very long*. @evka85 has explained me how he choose these values and how much they can be reduce :
> I just picked these delays somewhat arbitrarily, and they are definitely overkill.
> The first one (100ms) I think was to give time for the GBTX to do the phase shift or something like that, but in fact I think this is not really needed at all.
The second one is to give time for the LINK_GOOD flag to initialize after a link reset. This flag works like this:
> * every orbit (every ~90us) the sync verify command is sent to VFATs, which then reply with a "sync good" message if they receive the verify command.
> * for the LINK_GOOD to go high, it has to see 10 "sync good" messages from the VFATs in a row (in other words, the communication with the VFAT has to be good for 10 consecutive orbits). After the LINK_GOOD is high, it can only go low if there's 100 orbits without "sync_good" messages from VFATs.
> 
> So given this behavior of the LINK_GOOD flag, there must be a delay of at least 10 orbits (around 1ms) after the link reset. So in principle the 300ms could be reduced to 1ms, but I would give it some wiggle room and just wait for 5 or 10ms or so.

Following his advise, I picked 10ms of wait time. After a few tests, the phase scan still works seamlessly and so one can launch a scan with a bigger number of repetitions without waiting "forever".

2019-01-16 15:37 UTC, jsturdy reviewed
~~Was there a reason these delays were set to 300ms before?~~
@lpetre-ulb @bdorney

Too slow, OK

2019-01-16 15:39 UTC, jsturdy approved these changes

2019-01-16 15:41 UTC, merged

2019-01-16 15:41 UTC, lpetre-ulb commented
> Was there a reason these delays were set to 300ms before?
> @lpetre-ulb @bdorney

I copied these from @evka85's original `gbt.py` script, but as he wrote in his email, he "picked these delays somewhat arbitrarily, and they are definitely overkill".