WIP: cmsgemos feature port for AMC
cms-gem-daq-project/ctp7_modules pull request #77
Opened 2019-01-07 21:50 UTC by jsturdy

## Description
Start porting functionality from `cmsgemos` to `ctp7_modules`
* Includes functionality from `HwGenericAMC`
* Includes some reworking of the `Makefile` for adapting to source -> objects -> shared objects make process
  * Multiple objects built into single shared object (`CTP7` "module")
  * Retain current number of "modules", but allow distinct features to be scoped per file, e.g., `TTC`, DAQ, etc.
* Further functionality will be added in a separate PR for the OH specific code and adaptations for the blaster interface

### Types of changes
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context
Starting the necessary movement to have the core `cmsgemos` SW compatible with the RPC architecture

## How Has This Been Tested?
* Libraries compiled
* Copied to CTP7
* Test function executed
* Final testing needed, but machine failure in 904 prevented this

### Testing notes
* The *exact* version of the linked libraries matters, i.e., @mexanick and I discovered a problem that was due to the module being compiled against a version of the `xhal` library that was not on the card.
* At runtime this resulted in undefined behaviour due to the change in the LMDB structure that was not present.
* The interplay of all this needs to be finalized, with the versioning of the libraries and installed packages on the CTP7 (work in progress with `smart` package manager)

## Checklist:
- [ ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have ~added~ *run* tests to cover my changes.
- [ ] All new and existing tests passed.

2019-01-10 11:32 UTC, mexanick commented on include/utils.h
> +extern memsvc_handle_t memsvc; /// \var global memory service handle required for registers read/write operations
Where this variable is defined?

2019-01-10 11:32 UTC, mexanick commented on include/utils.h
> +// FIXME: to be replaced with the above function when the struct is properly implemented
Is the macro below tested and proven to be working? I personally don't see much difference with the previous attempt to implement a function, which failed to allocate the memory correctly...

2019-01-10 13:29 UTC, jsturdy commented on include/utils.h
> +// FIXME: to be replaced with the above function when the struct is properly implemented
The failure was in the return of the pointer to the struct, I believe, so the macro just wraps the call until one can get the setup function to work properly.  The macro behaves no differently than having the lines that are currently in every other callback

2019-01-10 13:36 UTC, jsturdy commented on include/utils.h
> +extern memsvc_handle_t memsvc; /// \var global memory service handle required for registers read/write operations
`utils.cpp`

2019-01-10 13:44 UTC, mexanick submitted a review, later dismissed

2019-01-10 16:45 UTC, jsturdy commented
I may prefer to finally merge this once #75 is merged, as I expect the changes in the `Makefile` to be conflicting, and I'll need to sort them out after rebasing this branch on top of those changes

2019-01-16 16:04 UTC, jsturdy commented
Rebased following the merge of #75, ready for re-review
@mexanick @bdorney

2019-01-17 09:42 UTC, bdorney commented
Before this is merged could we have the current branch of `develop` c323274d9344ebb922500832a53c9a2af11eede4 set as a legacy branch.  It will take some time for the python API to be rebuilt and the test suite to be updated and so the sustained operation measurements (and maybe some QC8 things) will need a "stable" point to work off of in the short term (for `$USER`s) while the developers update the toolset.

2019-01-17 09:47 UTC, mexanick commented
#79 should do this. Please review

2019-01-17 09:49 UTC, mexanick submitted a review, later dismissed
Cursory approval, as the multiple changes requires hardware testing/debugging

2019-01-17 09:51 UTC, bdorney commented on src/amc/daq.cpp
> +}
So I'm a bit confused by methods of this nature.  They appear to call a local method which in theory is going to perform just 1 (or a few) read/write transaction.  This will come in with a huge time penalty due to the TCP/IP transaction time.

I thought the goal was to use uhal for these "simple" actions and then rpc methods for register intensive actions.  The local methods above seem to make sense (as they could be called by some "master" RPC function to do some complex task, but having a remote method that just does one thing seems strange).

2019-01-17 09:53 UTC, bdorney commented on include/amc/ttc.h
> + * \file amc/ttc.h
If this is supposed to be the home of `TTC` modules shouldn't we migrate those functions in `calibration_routines.*` that deal with `TTC.GENERATOR` to this file?

2019-01-17 09:55 UTC, bdorney commented on src/daq_monitor.cpp
> +  struct localArgs la = {.rtxn = rtxn, .dbi = dbi, .response = response};
this will eventually be replaced by `GETLOCALARGS`?

2019-01-17 09:56 UTC, bdorney commented on src/utils.cpp
> +}
Who is supposed to be doing this? `GETLOCALARGS` or this function?  I saw some discussion above.  Not sure if it's appropriate to discuss there or here.

2019-01-17 10:05 UTC, jsturdy commented on src/amc/daq.cpp
> +}
Current implementation was a direct copy/paste from `HwGenericAMC`.
I fully expect to not utilize these single transaction RPC methods anywhere and to remove them during a future cleanup.

2019-01-17 10:06 UTC, jsturdy commented on include/amc/ttc.h
> + * \file amc/ttc.h
Almost definitely (cf. future cleanup)

2019-01-17 10:06 UTC, jsturdy commented on src/daq_monitor.cpp
> +  struct localArgs la = {.rtxn = rtxn, .dbi = dbi, .response = response};
No legacy code was modified, but, yes, during the aforementioned cleanup, all these will be updated.

2019-01-17 10:07 UTC, jsturdy commented on src/utils.cpp
> +}
This function, however current usage and implementation do not work, so the macro is the cleanup placeholder

2019-01-17 10:09 UTC, jsturdy commented on include/amc/ttc.h
> + * \file amc/ttc.h
And in that case, I'd probably block #63 and redo that as part of said cleanup

2019-01-17 14:28 UTC, bdorney commented on include/amc/ttc.h
> + * \file amc/ttc.h
I would be fine with that.  The git commit history that #63 introduces is somewhat messy (multiple commits adding/removing the same text).  Might want to make a comment there to @AndrewLevin then.

2019-02-04 09:46 UTC, jsturdy commented
OK, @mexanick, @bdorney, I'm currently satisfied with the content of this PR and won't push anything other than requested fixes.
Blaster interface and VFAT3 Reed--Muller ChipID grow from the tip of this PR

2019-02-04 10:02 UTC, mexanick requested changes

2019-02-04 10:02 UTC, mexanick commented on Makefile
> +	g++ -O0 -g3 -fno-inline -o test/$@ $< $(INC) $(LDFLAGS) -lwiscrpcsvc
If the new way of compilation is properly tested, I would clean up the commented part here, starting from line 143. If not - we need to test and fix it =)

2019-02-04 10:02 UTC, mexanick commented on src/utils.cpp
> +  LOGGER->log_message(LogManager::WARNING, stdsprintf("Called readReg on %s", regName.c_str()));
Do we really want all these log messages till l309 to be of "WARNING" level? I would make them rather "DEBUG" or even "TRACE"

2019-02-04 10:11 UTC, bdorney commented on src/amc/sca.cpp
> +  writeReg(la, "GEM_AMC.SLOW_CONTROL.SCA.CTRL.MODULE_RESET", 0x1);
This will cause a reset to all links; do we want to either add to this function a mask to be used with `GEM_AMC.SLOW_CONTROL.SCA.CTRL.SCA_RESET_ENABLE_MASK` or do we want to add a separate function to set this mask?  Probably the latter and not the former.

2019-02-04 10:11 UTC, jsturdy commented on src/utils.cpp
> +  LOGGER->log_message(LogManager::WARNING, stdsprintf("Called readReg on %s", regName.c_str()));
Oops, in fact, these should all be removed I think, we tracked down the issue that I was trying to debug with them, but must have accidentally committed them

2019-02-04 10:12 UTC, bdorney commented on src/amc/ttc.cpp
> +  // writeReg(la, "GEM_AMC.TTC.CTRL.MODULE_RESET", 0x1);
Why comment this out?

Also what about the associated TTC Generator functions presently in `calibration_routines`.  Shouldn't they be moved here/expanded upon?

2019-02-04 10:13 UTC, jsturdy commented on Makefile
> +	g++ -O0 -g3 -fno-inline -o test/$@ $< $(INC) $(LDFLAGS) -lwiscrpcsvc
yeah, this is further cleaned up in [this](https://github.com/jsturdy/ctp7_modules/compare/feature/hw-feature-port...jsturdy:feature/reedmuller-chipid) branch, where the Reed--Muller additions are coming

2019-02-04 10:14 UTC, bdorney commented on src/utils.cpp
> +  LOGGER->log_message(LogManager::WARNING, stdsprintf("Called readReg on %s", regName.c_str()));
Indeed this will fill the log file with *every* read transaction...

2019-02-04 10:15 UTC, bdorney commented on src/utils.cpp
> +    LOGGER->log_message(LogManager::WARNING, stdsprintf("Mask obtained 0x%x", mask));
Same comment as above, these should probably not be at the `WARNING` level.  Maybe `INFO` but most likely `DEBUG` or below.

2019-02-04 10:21 UTC, jsturdy commented on src/amc/sca.cpp
> +  writeReg(la, "GEM_AMC.SLOW_CONTROL.SCA.CTRL.MODULE_RESET", 0x1);
This is just a port of the functionality in `cmsgemos`, which was done based on the V2 FW.
Absolutely, improving the interface will be done in the followup, and the discussion of behaviour can be made there. (One could there ask whether resetting the SCA module should be accompanied by *any* link resets, or whether the link resets should *always* be separate)

2019-02-04 10:21 UTC, jsturdy commented on src/amc/ttc.cpp
> +  // writeReg(la, "GEM_AMC.TTC.CTRL.MODULE_RESET", 0x1);
Probably, as mentioned several times above, this PR is not intending to modify any existing functionality.

2019-02-04 10:21 UTC, jsturdy commented on src/utils.cpp
> +    LOGGER->log_message(LogManager::WARNING, stdsprintf("Mask obtained 0x%x", mask));
Should all be gone now.

2019-02-13 09:40 UTC, jsturdy commented
bump @mexanick

2019-02-13 09:46 UTC, mexanick submitted a review, later dismissed

2019-02-13 09:47 UTC, mexanick commented
PR approved, please rebase on top of the current develop before merging

2019-02-13 13:00 UTC, jsturdy commented
> PR approved, please rebase on top of the current develop before merging

Will do, though will require another approval

2019-02-13 13:15 UTC, merged