[WIP] New Feature: Added Link Monitoring
cms-gem-daq-project/ctp7_modules pull request #82
Opened 2019-01-30 16:58 UTC by bdorney

## Description

Addresses issue #66.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Provides link monitoring.  Is needed for connectivity testing proposal, see [steps 2 & 5](https://mattermost.web.cern.ch/cms-gem-ops/pl/brc3p9q95t8o3bd7uiubdy3hxa). 

## How Has This Been Tested?

In progress.

### Screenshots (if appropriate):

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2019-02-19 12:44 UTC, mexanick submitted a review, later dismissed

2019-02-21 11:46 UTC, bdorney commented
@jsturdy @mexanick ready for review.

2019-02-21 21:16 UTC, bdorney commented
rebased off of `develop`

2019-02-25 09:11 UTC, jsturdy requested changes
Cleanup

2019-02-25 09:11 UTC, jsturdy commented on src/daq_monitor.cpp
> +    }
Is there no appropriate local function to do a link reset? (also in the GBT function)

2019-02-25 09:11 UTC, jsturdy commented on src/gbt.cpp
> +    const uint32_t N = request->get_word("nScans");
Single letter (capital to boot) variables are a poor design choice, why not just use `nScans`?

2019-02-25 09:11 UTC, jsturdy commented on src/daq_monitor.cpp
> +  auto dbi = lmdb::dbi::open(rtxn, nullptr);
I would replace this block in all *newly* added/implemented functions with the wrapper, making the future cleanup simpler

2019-02-25 09:43 UTC, mexanick requested changes

2019-02-25 09:43 UTC, mexanick commented on src/calibration_routines.cpp
> +            //dacScanResults.resize( (dacMax+1)*24/dacStep );
please remove outdated commented line

2019-02-25 09:43 UTC, mexanick commented on src/daq_monitor.cpp
> +            respName = stdsprintf("OH%i.GBT%i.READY",ohN,gbtN);
Shouldn't we use here something like:
```cpp
std::string basename = "GEM_AMC.OH_LINKS.";
for (...){
    respName = stdsprintf("OH%i.GBT%i.READY",ohN,gbtN);
    la->response->set_word(respName,readReg(la,stdsprintf("%s%s", basename.c_str(), respName.c_str())));
}
```

2019-02-25 09:43 UTC, mexanick commented on src/daq_monitor.cpp
> +  struct localArgs la = {.rtxn = rtxn, .dbi = dbi, .response = response};
seconding @jsturdy request about lmdb-la

2019-02-25 09:43 UTC, mexanick commented on src/daq_monitor.cpp
> +    }
do you think we really need such function in order to perform on write transaction?

2019-02-25 09:43 UTC, mexanick commented on src/daq_monitor.cpp
> +            //Sync Error Counters
same comment as above

2019-02-25 10:51 UTC, bdorney commented on src/gbt.cpp
> +    const uint32_t N = request->get_word("nScans");
Um that's what I've done...it was originally committed with `N` which is for sure an oversight.

2019-02-25 10:52 UTC, bdorney commented on src/daq_monitor.cpp
> +  auto dbi = lmdb::dbi::open(rtxn, nullptr);
Which one should be used? The macro:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/360913c693ae4caa11ed20626bf6cd9595f392db/include/utils.h#L43-L53

Or the function:

https://github.com/cms-gem-daq-project/ctp7_modules/blob/360913c693ae4caa11ed20626bf6cd9595f392db/src/utils.cpp#L5-L18

???

2019-02-25 10:52 UTC, bdorney commented on src/calibration_routines.cpp
> +            //dacScanResults.resize( (dacMax+1)*24/dacStep );
whoops, oversight.

2019-02-25 10:56 UTC, bdorney commented on src/daq_monitor.cpp
> +  struct localArgs la = {.rtxn = rtxn, .dbi = dbi, .response = response};
this was rebased off of `develop` and originally targeted `master` since I absolutely *need* this functionality in the lab asap.  So this function wasn't present.  I can place it here for the `develop` PR but I need a separate branch compatible with legacy build instructions and legacy `xhal`.  E.g. `develop` will not build if `xhal` is on the legacy branch on the machine (needed).

Also see comment [here](https://github.com/cms-gem-daq-project/ctp7_modules/pull/82#discussion_r259770985)

2019-02-25 10:57 UTC, bdorney commented on src/daq_monitor.cpp
> +    }
@jsturdy no there is not, and @mexanick I don't think we really need one to perform a *one* line transaction.

2019-02-25 10:59 UTC, bdorney commented on src/daq_monitor.cpp
> +            respName = stdsprintf("OH%i.GBT%i.READY",ohN,gbtN);
I don't really see how concatenating off a base string improves anything in this context.

2019-02-25 10:59 UTC, bdorney commented on src/daq_monitor.cpp
> +            //Sync Error Counters
same as above.

2019-02-25 11:22 UTC, mexanick commented on src/daq_monitor.cpp
> +            respName = stdsprintf("OH%i.GBT%i.READY",ohN,gbtN);
quite less lines of code

2019-02-25 11:23 UTC, mexanick commented on src/daq_monitor.cpp
> +  auto dbi = lmdb::dbi::open(rtxn, nullptr);
Macro for the moment

2019-02-25 11:24 UTC, mexanick commented on src/gbt.cpp
> +    const uint32_t N = request->get_word("nScans");
I guess @jsturdy mean method variable (`const uint32_t N =...` part)

2019-02-25 12:48 UTC, bdorney commented on src/gbt.cpp
> +    const uint32_t N = request->get_word("nScans");
updated.

2019-02-25 12:50 UTC, bdorney commented on src/daq_monitor.cpp
> +            respName = stdsprintf("OH%i.GBT%i.READY",ohN,gbtN);
Not really...it takes the same lines of code.  I think we are splitting hairs here and there are more important things to focus on.

2019-02-25 12:55 UTC, bdorney commented on src/gbt.cpp
> +    const uint32_t N = request->get_word("nScans");
Resolved.

2019-02-25 12:55 UTC, bdorney commented on src/daq_monitor.cpp
> +  auto dbi = lmdb::dbi::open(rtxn, nullptr);
Got it, thanks for feedback; macro is now used in newly defined functions in this PR.

2019-02-27 14:01 UTC, mexanick approved these changes

2019-02-27 14:03 UTC, mexanick approved these changes

2019-02-27 14:05 UTC, bdorney commented
@jsturdy was there something else that was needed?

2019-02-27 17:28 UTC, jsturdy approved these changes
Critical OK

2019-02-27 17:28 UTC, jsturdy commented on src/daq_monitor.cpp
> +            respName = stdsprintf("OH%i.GBT%i.READY",ohN,gbtN);
Code simplification postponed

2019-02-27 17:28 UTC, jsturdy commented on src/daq_monitor.cpp
> +    }
It's likely a common enough operation that a reset function alias is useful (I'm not at all talking about exposing this through the RPC)

2019-03-01 16:58 UTC, merged