Add Reed--Muller decoding function for VFAT3 ChipID
cms-gem-daq-project/ctp7_modules pull request #95
Opened 2019-03-01 16:48 UTC by jsturdy

## Description
Adds function `uint16_t decodeChipID(uint32_t encChipID)` to decode Reed--Muller encoded chip IDs

### Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Motivation and Context
Necessary to decode the Reed--Muller encoded VFAT3 chip IDs

## How Has This Been Tested?
* Hasn't been tested with hardware, due to previous lack of compatible hybrids.
* Encoding and decoding has been tested with command line function.

2019-03-04 09:29 UTC, mexanick requested changes
Few minor comments to address. Additionally, I think it might be useful to have the `warning` or `debug` log issued upon bit-flip encountered, if possible. (not sure whether it can/should be accomplished in this method...

2019-03-04 09:29 UTC, mexanick commented on src/vfat3.cpp
> +uint16_t decodeChipID(uint32_t encChipID)
While I understand the intention of returning a smaller data type, the standard data word size in the `RPCSvc` is 32 bit. I would then operate `uint32_t` throughout.

2019-03-04 09:29 UTC, mexanick commented on src/vfat3.cpp
> +  // static std::shared_ptr<int> encoded = 0;
Consider removing commented out lines as not needed.

2019-03-04 09:43 UTC, jsturdy commented on src/vfat3.cpp
> +uint16_t decodeChipID(uint32_t encChipID)
This function is local only, and it is expected that the thing actually using it will put the data in the appropriate return type for any RPC message.

2019-03-04 09:47 UTC, mexanick commented on src/vfat3.cpp
> +uint16_t decodeChipID(uint32_t encChipID)
I see your point, but my personal preference would be to return `uint32_t` to avoid confusions and possible errors in the code which uses this function. However it is up to you whether to address this comment or not. I should note that in case of using it in multiple instance of other methods, the conversion will have to be performed in multiple places which is code dups and not the best coding practice...

2019-03-04 10:15 UTC, jsturdy commented on src/vfat3.cpp
> +  // static std::shared_ptr<int> encoded = 0;
Fixed by enabling `std=c++14` in the Zynq mfDefs, and using `unique_ptr`

2019-03-04 10:15 UTC, jsturdy commented
> not sure whether it can/should be accomplished in this method...

This method will throw if 4 bit flips have occurred, fewer than that, and it simply corrects, more than that and it may throw or not, the algorithm is not guaranteed for more than 4.
It can not alert that fewer than 4 bit flips have occurred, and we probably don't care.

Again, it is expected that the function actually calling this decoder will handle the errors and emit them as desired.

2019-03-06 13:23 UTC, jsturdy commented
Rebased and ready for sign-off @bdorney @mexanick

2019-03-06 13:26 UTC, mexanick approved these changes
I approuve, but the users/developers should beware of 16bit return of `decodeChipID` method

2019-03-06 13:27 UTC, merged